#include "Abode.h"

__attribute__((no_callee_saves, XOR32rr_REV))
float __fastcall CalculateScoreForAddingVillagerToAbode__5AbodeFP8Villager(struct Abode* this, const void* edx, struct Villager* villager)
{
    float result;
    asm volatile (
        "sub                esp, 0x10\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "%{disp8%} mov        edi, dword ptr [esp + 0x1c]\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "mov.s              esi, ecx\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0xaf8]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00404ba1\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x28]\n\t"
        "%{disp32%} mov       eax, dword ptr [ecx + 0x00000178]\n\t"
        "xor.s              edx, edx\n\t"
        "cmp.s              eax, edx\n\t"
        "%{disp8%} jne        LAB__addr_0x00404b76\n\t"
        "%{disp32%} fld       dword ptr [_rdata_float0p0]\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "add                esp, 0x10\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x00404b76:\n\t"
        "xor.s              ecx, ecx\n\t"
        "%{disp32%} mov       cl, byte ptr [esi + 0x000000b7]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], edx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x1c], ecx\n\t"
        "%{disp8%} fild       dword ptr [esp + 0x1c]\n\t"
        "%{disp8%} fidiv      dword ptr [esp + 0x08]\n\t"
        "%{disp32%} fcom      dword ptr [_rdata_float1p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x00404bef\n\t"
        "%{disp8%} jmp        LAB__addr_0x00404be7\n"
        "LAB__addr_0x00404ba1:\n\t"
        "%{disp8%} mov        edx, dword ptr [esi + 0x28]\n\t"
        "%{disp32%} mov       eax, dword ptr [edx + 0x00000174]\n\t"
        "xor.s              edx, edx\n\t"
        "cmp.s              eax, edx\n\t"
        "%{disp8%} jne        LAB__addr_0x00404bbe\n\t"
        "%{disp32%} fld       dword ptr [_rdata_float0p0]\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "add                esp, 0x10\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x00404bbe:\n\t"
        "xor.s              ecx, ecx\n\t"
        "%{disp32%} mov       cl, byte ptr [esi + 0x000000b4]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], edx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x1c], ecx\n\t"
        "%{disp8%} fild       dword ptr [esp + 0x1c]\n\t"
        "%{disp8%} fidiv      dword ptr [esp + 0x08]\n\t"
        "%{disp32%} fcom      dword ptr [_rdata_float1p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x00404bef\n"
        "LAB__addr_0x00404be7:\n\t"
        "fstp               st(0)\n\t"
        "%{disp32%} fld       dword ptr [_rdata_float1p0]\n"
        "LAB__addr_0x00404bef:\n\t"
        "%{disp32%} fsubr     dword ptr [_rdata_float1p0]\n\t"
        "%{disp32%} fcom      dword ptr [_rdata_float0p0]\n\t"
        "%{disp8%} fst        dword ptr [esp + 0x08]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp32%} jne       LAB__addr_0x00404cab\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x000000a0]\n\t"
        "fstp               st(0)\n\t"
        "cmp.s              eax, edx\n\t"
        "%{disp32%} fld       dword ptr [_rdata_float0p0]\n\t"
        "%{disp8%} je         LAB__addr_0x00404c42\n\t"
        "%{disp8%} mov        ecx, dword ptr [edi + 0x28]\n\t"
        "%{disp32%} mov       ecx, dword ptr [ecx + 0x000001f8]\n\t"
        "push               ebx\n"
        "LAB__addr_0x00404c26:\n\t"
        "%{disp8%} mov        ebx, dword ptr [eax + 0x28]\n\t"
        "cmp                dword ptr [ebx + 0x000001f8], ecx\n\t"
        "%{disp8%} jne        LAB__addr_0x00404c37\n\t"
        "%{disp32%} fadd      dword ptr [_rdata_float1p0]\n"
        "LAB__addr_0x00404c37:\n\t"
        "%{disp32%} mov       eax, dword ptr [eax + 0x000000e4]\n\t"
        "cmp.s              eax, edx\n\t"
        "%{disp8%} jne        LAB__addr_0x00404c26\n\t"
        "pop                ebx\n"
        "LAB__addr_0x00404c42:\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x000000a4]\n\t"
        "cmp.s              eax, edx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x1c], 0x3f800000\n\t"
        "%{disp8%} je         LAB__addr_0x00404c78\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], edx\n\t"
        "%{disp8%} fild       qword ptr [esp + 0x10]\n\t"
        "fdivr              st, st(1)\n\t"
        "%{disp32%} fsubr     dword ptr [_rdata_float1p0]\n\t"
        "%{disp32%} fadd      dword ptr [_rdata_float1p0]\n\t"
        "%{disp32%} fmul      dword ptr [_rdata_float0p5]\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x1c]\n"
        "LAB__addr_0x00404c78:\n\t"
        "push               0x43fa0000\n\t"
        "fstp               st(0)\n\t"
        "add                edi, 0x14\n\t"
        "push               edi\n\t"
        "%{disp8%} lea        ecx, dword ptr [esi + 0x14]\n\t"
        "call               _GetDistanceInMetres__6GUtilsFRC9MapCoordsRC9MapCoords_2\n\t"
        "push               ecx\n\t"
        "fstp               dword ptr [esp]\n\t"
        "call               _GetDistanceModifier__6GUtilsFff@8\n\t"
        "%{disp32%} fadd      dword ptr [_rdata_float1p0]\n\t"
        "add                esp, 0x08\n\t"
        "%{disp32%} fmul      dword ptr [_rdata_float0p5]\n\t"
        "%{disp8%} fmul       dword ptr [esp + 0x1c]\n\t"
        "%{disp8%} fmul       dword ptr [esp + 0x08]\n"
        "LAB__addr_0x00404cab:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "add                esp, 0x10"
        : "=t"(result) :: "eax", "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves))
void __fastcall ChildToAdult__5AbodeFP8Villager(struct Abode* this, const void* edx, struct Villager* villager)
{
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp32%} mov       al, byte ptr [esi + 0x000000b7]\n\t"
        "test               al, al\n\t"
        "push               edi\n\t"
        "%{disp8%} je         LAB__addr_0x00404cd6\n\t"
        "dec                al\n\t"
        "%{disp32%} mov       byte ptr [esi + 0x000000b7], al\n"
        "LAB__addr_0x00404cd6:\n\t"
        "%{disp32%} mov       dl, byte ptr [esi + 0x000000b4]\n\t"
        "%{disp8%} mov        edi, dword ptr [esp + 0x0c]\n\t"
        "inc                dl\n\t"
        "%{disp32%} mov       byte ptr [esi + 0x000000b4], dl\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x44c]\n\t"
        "%{disp32%} mov       dl, byte ptr [esi + 0x000000b5]\n\t"
        "test               eax, eax\n\t"
        "setne              cl\n\t"
        "add.s              dl, cl\n\t"
        "%{disp32%} mov       byte ptr [esi + 0x000000b5], dl\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00404d1f\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               ?ChildToAdult@Town@@QAEXPAVVillager@@@Z\n"
        "LAB__addr_0x00404d1f:\n\t"
        "pop                edi\n\t"
        "pop                esi"
        ::: "eax", "ecx", "edx", "memory"
    );
}

uint32_t __fastcall GetResource__5AbodeF13RESOURCE_TYPE(struct GameThing* this, const void* edx, enum RESOURCE_TYPE type)
{
    return ((struct Abode*)this)->resources[type];
}

__attribute__((no_callee_saves, msvc6_regalloc))
uint32_t __fastcall JustAddResource__5AbodeF13RESOURCE_TYPEUlb(struct GameThing* this, const void* edx, enum RESOURCE_TYPE param_1, uint32_t param_2, bool param_3)
{
    register uint32_t type asm("edx");
    register uint32_t amount asm("eax");
    asm volatile(
        "%{disp8%} mov edx, dword ptr [esp + 0x04]\n\t"
        "%{disp8%} mov eax, dword ptr [esp + 0x08]"
        : "=d"(type), "=a"(amount) :: "memory"
    );
    *(uint32_t*)((char*)this + 0xbc + type * 4) += amount;
    return amount;
}

__attribute__((no_callee_saves))
uint32_t __fastcall JustRemoveResource__5AbodeF13RESOURCE_TYPEUlPb(struct GameThing* this, const void* edx, enum RESOURCE_TYPE param_1, uint32_t param_2, bool* param_3)
{
    uint32_t result;
    asm volatile (
        "%{disp8%} mov eax, dword ptr [esp + 0x08]\n\t"
        "push esi\n\t"
        "%{disp8%} mov esi, dword ptr [esp + 0x08]\n\t"
        "%{disp32%} mov edx, dword ptr [ecx + esi * 0x4 + 0x000000bc]\n\t"
        "cmp.s edx, eax\n\t"
        "%{disp8%} jae 0f\n\t"
        "mov.s eax, edx\n"
        "0:\n\t"
        "sub.s edx, eax\n\t"
        "%{disp32%} mov dword ptr [ecx + esi * 0x4 + 0x000000bc], edx\n\t"
        "pop esi"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves))
uint32_t __fastcall AddResource__5AbodeF13RESOURCE_TYPEUlP16GInterfaceStatusbRC9MapCoordsi(struct GameThing* this, const void* edx, enum RESOURCE_TYPE type, uint32_t param_2, struct GInterfaceStatus* param_3, bool param_4, const struct MapCoords* coords, int param_6)
{
    uint32_t result;
    asm volatile (
        "%{disp8%} mov        eax, dword ptr [ecx + 0x74]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x04]\n\t"
        "push               esi\n\t"
        "%{disp8%} je         LAB__addr_0x00404dc8\n\t"
        "cmp                edx, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x00404da6\n\t"
        "cmp                edx, -0x02\n\t"
        "%{disp8%} jne        LAB__addr_0x00404dc8\n"
        "LAB__addr_0x00404da6:\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x14]\n\t"
        "mov                esi, dword ptr [eax]\n\t"
        "push               0x0\n\t"
        "push               0x0\n\t"
        "push               ecx\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x1c]\n\t"
        "push               ecx\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x1c]\n\t"
        "push               ecx\n\t"
        "push               edx\n\t"
        "mov.s              ecx, eax\n\t"
        "call               dword ptr [esi + 0x9c]\n\t"
        "pop                esi\n\t"
        "ret                0x0018\n"
        "LAB__addr_0x00404dc8:\n\t"
        "%{disp8%} mov        esi, dword ptr [esp + 0x1c]\n\t"
        "mov                eax, dword ptr [ecx]\n\t"
        "push               esi\n\t"
        "%{disp8%} mov        esi, dword ptr [esp + 0x1c]\n\t"
        "push               esi\n\t"
        "%{disp8%} mov        esi, dword ptr [esp + 0x1c]\n\t"
        "push               esi\n\t"
        "%{disp8%} mov        esi, dword ptr [esp + 0x1c]\n\t"
        "push               esi\n\t"
        "%{disp8%} mov        esi, dword ptr [esp + 0x1c]\n\t"
        "push               esi\n\t"
        "push               edx\n\t"
        "call               dword ptr [eax + 0x8e4]\n\t"
        "pop                esi"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV, ret_cleanup_override(0x18)))
uint32_t __fastcall DoResourceAdding__5AbodeF13RESOURCE_TYPEUlP16GInterfaceStatusbRC9MapCoordsi(struct MultiMapFixed* this, const void* edx, enum RESOURCE_TYPE type, struct GInterfaceStatus* iface, bool param_3, struct MapCoords* param_4, int param_5)
{
    uint32_t result;
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "mov.s              edi, eax\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x14]\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x00404ee3\n\t"
        "test               edi, edi\n\t"
        "%{disp32%} je        LAB__addr_0x00404ee3\n\t"
        "push               ebx\n\t"
        "%{disp8%} mov        ebx, dword ptr [esp + 0x10]\n\t"
        "xor.s              ecx, ecx\n\t"
        "test               ebx, ebx\n\t"
        "setne              cl\n\t"
        "push               ebp\n\t"
        "mov.s              ebp, ecx\n\t"
        "%{disp8%} lea        ecx, dword ptr [edi + 0x34]\n\t"
        "push               ebp\n\t"
        "call               _jmp_addr_0x00745d80\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x14]\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x20]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x18]\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               eax\n\t"
        "push               ecx\n\t"
        "push               ebx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x8c]\n\t"
        "push               ebp\n\t"
        "%{disp8%} lea        ecx, dword ptr [edi + 0x34]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x24], eax\n\t"
        "call               _jmp_addr_0x00745d80\n\t"
        "%{disp8%} fsubr      dword ptr [esp + 0x14]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x1c]\n\t"
        "mov                edx, dword ptr [ecx]\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x14]\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "mov.s              ebp, eax\n\t"
        "push               ebx\n\t"
        "mov.s              ecx, ebp\n\t"
        "call               ?GetPlayerNumber@GPlayer@@QBEEXZ\n\t"
        "push               eax\n\t"
        "mov.s              ecx, edi\n\t"
        "call               _jmp_addr_0x00740030\n\t"
        "%{disp8%} fmul       dword ptr [esp + 0x14]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x18]\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x14]\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x14]\n\t"
        "push               eax\n\t"
        "push               ecx\n\t"
        "%{disp8%} mov        ecx, dword ptr [ebp + 0x60]\n\t"
        "push               ebx\n\t"
        "push               esi\n\t"
        "call               _jmp_addr_0x00414520\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "cmp.s              ebp, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00404ea6\n\t"
        "%{disp8%} mov        eax, dword ptr [edi + 0x28]\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x14]\n\t"
        "%{disp32%} fmul      dword ptr [eax + 0x000000fc]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00404eaa\n"
        "LAB__addr_0x00404ea6:\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x14]\n"
        "LAB__addr_0x00404eaa:\n\t"
        "%{disp8%} mov        ecx, dword ptr [edi + 0x28]\n\t"
        "%{disp32%} fmul      dword ptr [ecx + 0x000000f8]\n\t"
        "push               0x1\n\t"
        "push               0x1\n\t"
        "push               esi\n\t"
        "push               ecx\n\t"
        "fstp               dword ptr [esp]\n\t"
        "push               ebp\n\t"
        "%{disp32%} lea       ecx, dword ptr [edi + 0x00000798]\n\t"
        "call               _jmp_addr_0x00437eb0\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x1c]\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               eax\n\t"
        "push               ebx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x68c]\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x20]\n\t"
        "pop                ebp\n\t"
        "pop                ebx\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "ret                0x0018\n"
        "LAB__addr_0x00404ee3:\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x18]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x10]\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               eax\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x10]\n\t"
        "push               ecx\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x8c]\n\t"
        "pop                edi\n\t"
        "pop                esi"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves))
uint32_t __fastcall RemoveResource__5AbodeF13RESOURCE_TYPEUlP16GInterfaceStatusPb(struct GameThing* this, const void* edx, enum RESOURCE_TYPE type, uint32_t param_2, struct GInterfaceStatus* param_3, bool* param_4)
{
    uint32_t result;
    asm volatile (
        "%{disp8%} mov        eax, dword ptr [ecx + 0x74]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x04]\n\t"
        "push               esi\n\t"
        "%{disp8%} je         LAB__addr_0x00404f44\n\t"
        "cmp                edx, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x00404f26\n\t"
        "cmp                edx, -0x02\n\t"
        "%{disp8%} jne        LAB__addr_0x00404f44\n"
        "LAB__addr_0x00404f26:\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x14]\n\t"
        "mov                esi, dword ptr [eax]\n\t"
        "push               ecx\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x14]\n\t"
        "push               ecx\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x14]\n\t"
        "push               ecx\n\t"
        "push               edx\n\t"
        "mov.s              ecx, eax\n\t"
        "call               dword ptr [esi + 0xa0]\n\t"
        "pop                esi\n\t"
        "ret                0x0010\n"
        "LAB__addr_0x00404f44:\n\t"
        "%{disp8%} mov        esi, dword ptr [esp + 0x14]\n\t"
        "mov                eax, dword ptr [ecx]\n\t"
        "push               esi\n\t"
        "%{disp8%} mov        esi, dword ptr [esp + 0x14]\n\t"
        "push               esi\n\t"
        "%{disp8%} mov        esi, dword ptr [esp + 0x14]\n\t"
        "push               esi\n\t"
        "push               edx\n\t"
        "call               dword ptr [eax + 0x8e8]\n\t"
        "pop                esi"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV, ret_cleanup_override(0x00)))
uint32_t __fastcall DoResourceRemoving__5AbodeF13RESOURCE_TYPEUlP16GInterfaceStatusPb(struct MultiMapFixed* this, const void* edx, enum RESOURCE_TYPE type, uint32_t param_2, struct GInterfaceStatus* iface, bool param_4)
{
    uint32_t result;
    asm volatile (
        "push               ecx\n\t"
        "push               ebx\n\t"
        "%{disp8%} mov        ebx, dword ptr [esp + 0x0c]\n\t"
        "push               ebp\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               ebx\n\t"
        "call               dword ptr [eax + 0x98]\n\t"
        "%{disp8%} mov        ebp, dword ptr [esp + 0x1c]\n\t"
        "cmp.s              ebp, eax\n\t"
        ".byte              0x72, 0xc\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               0x0\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x69c]\n"
        "LAB__addr_0x00404f88:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "mov.s              edi, eax\n\t"
        "xor.s              eax, eax\n\t"
        "test               ebx, ebx\n\t"
        "setne              al\n\t"
        "%{disp8%} lea        ecx, dword ptr [edi + 0x34]\n\t"
        "push               eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x20], eax\n\t"
        "call               _jmp_addr_0x00745d80\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x18]\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               0x0\n\t"
        "push               ebp\n\t"
        "push               ebx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x90]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x20]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], eax\n\t"
        "%{disp8%} je         LAB__addr_0x0040500e\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x0040500e\n\t"
        "mov                eax, dword ptr [ecx]\n\t"
        "push               ebx\n\t"
        "call               dword ptr [eax + 0x1c]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               ?GetPlayerNumber@GPlayer@@QBEEXZ\n\t"
        "push               eax\n\t"
        "mov.s              ecx, edi\n\t"
        "call               _jmp_addr_0x007400d0\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x1c]\n\t"
        "push               ecx\n\t"
        "%{disp8%} lea        ecx, dword ptr [edi + 0x34]\n\t"
        "call               _jmp_addr_0x00745d80\n\t"
        "%{disp8%} fsubr      dword ptr [esp + 0x18]\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x18]\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x18]\n\t"
        "push               ecx\n\t"
        "%{disp8%} mov        ecx, dword ptr [eax + 0x60]\n\t"
        "neg                ebp\n\t"
        "push               ebp\n\t"
        "push               ebx\n\t"
        "push               esi\n\t"
        "call               _jmp_addr_0x00414520\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x10]\n"
        "LAB__addr_0x0040500e:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "pop                ebx\n\t"
        "pop                ecx\n\t"
        "ret                0x0010\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x04]\n\t"
        "push               eax\n\t"
        "call               LAB__addr_0x00405040\n\t"
        "add                esp, 0x04\n\t"
        "neg                eax\n\t"
        "sbb.s              eax, eax\n\t"
        "neg                eax\n\t"
        "ret\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n"
        "LAB__addr_0x00405040:\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x04]\n\t"
        "push               0x0\n\t"
        "push               0x0\n\t"
        "call               @FindType__9MapCoordsCF11OBJECT_TYPEP6Object@16"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

struct PlannedMultiMapFixed * __fastcall ConvertToPlanned__5AbodeFv(struct MultiMapFixed* this)
{
    void* dummy;
    struct PlannedMultiMapFixed * result;
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "push               edi\n\t"
        "push               esi\n\t"
        "call               ?Create@PlannedAbode@@SAPAV1@PAVAbode@@@Z\n\t"
        "mov.s              edi, eax\n\t"
        "add                esp, 0x04\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x0040506c\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x0\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0xc]\n\t"
        "LAB__addr_0x0040506c:\n\t"
        "mov.s              eax, edi\n\t"
        "pop                edi\n\t"
        "pop                esi"
        : "=a"(result), "=c"(dummy) : "c"(this) : "edx", "memory"
    );
    return result;
}
