#include "AbodeInfo.h"

const char* __fastcall GetDescription__10GAbodeInfoFv(struct GAbodeInfo* this)
{
    return this->description.string;
}

__attribute__((XOR32rr_REV))
int __cdecl GetInfoFromText__10GAbodeInfoFPc(const char* text)
{
    asm volatile (
        "sub                esp, 0x08\n\t"
        "push               ebx\n\t"
        "push               ebp\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], 0x00000000\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], OFFSET _AbodeInfos\n\t"
        "mov                ebp, 0x00da57b8\n"
        "LAB__addr_0x00405a8c:\n\t"
        "%{disp8%} mov        eax, dword ptr [ebp + 0x00]\n\t"
        "%{disp32%} mov       edx, dword ptr [eax * 0x4 + 0x00c22fdc]\n\t"
        "%{disp8%} mov        ebx, dword ptr [esp + 0x1c]\n\t"
        "or                 ecx, 0xffffffff\n\t"
        "xor.s              eax, eax\n\t"
        "mov.s              edi, edx\n\t"
        "repne scasb\n\t"
        "not                ecx\n\t"
        "dec                ecx\n\t"
        "mov.s              edi, ecx\n\t"
        "push               edi\n\t"
        "push               edx\n\t"
        "push               ebx\n\t"
        "call               __strnicmp\n\t"
        "add                esp, 0x0c\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x00405ae8\n\t"
        "cmp                byte ptr [edi + ebx * 0x1], 0x5f\n\t"
        "%{disp8%} jne        LAB__addr_0x00405ae8\n\t"
        "%{disp8%} lea        ebx, dword ptr [edi + ebx * 0x1 + 0x01]\n\t"
        "%{disp8%} mov        edi, dword ptr [esp + 0x10]\n\t"
        "xor.s              esi, esi\n"
        "LAB__addr_0x00405ac7:\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?GetDescription@GAbodeInfo@@QAEPBDXZ\n\t"
        "push               eax\n\t"
        "push               ebx\n\t"
        "call               __strcmpi\n\t"
        "add                esp, 0x08\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00405b15\n\t"
        "inc                esi\n\t"
        "add                edi, 0x000001c8\n\t"
        "cmp                esi, 0x10\n\t"
        ".byte              0x72, 0xdf\n"
        "LAB__addr_0x00405ae8:\n\t"
        "%{disp8%} mov        esi, dword ptr [esp + 0x14]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x10]\n\t"
        "inc                esi\n\t"
        "add                ebp, 0x1c\n\t"
        "add                ecx, 0x00001c80\n\t"
        "cmp                ebp, 0x00da58b4\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], esi\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], ecx\n\t"
        ".byte              0x72, 0x82\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "or                 eax, -0x1\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x08\n\t"
        "ret\n"
        "LAB__addr_0x00405b15:\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x14]\n\t"
        "pop                edi\n\t"
        "shl                eax, 4\n\t"
        "add.s              eax, esi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x08\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((XOR32rr_REV))
struct GAbodeInfo* __cdecl Find__10GAbodeInfoF10TRIBE_TYPE12ABODE_NUMBER(enum TRIBE_TYPE tribe_type, enum ABODE_NUMBER abode_number)
{
    asm volatile (
        "push               esi\n\t"
        "%{disp8%} mov        esi, dword ptr [esp + 0x08]\n\t"
        "push               edi\n\t"
        "%{disp8%} mov        edi, dword ptr [esp + 0x10]\n\t"
        "mov                eax, OFFSET _AbodeInfos\n\t"
        "mov                ecx, 0x00c3c7e8\n"
        "LAB__addr_0x00405b44:\n\t"
        "mov                edx, dword ptr [ecx]\n\t"
        "cmp.s              edx, esi\n\t"
        "%{disp8%} je         LAB__addr_0x00405b4f\n\t"
        "cmp                edx, -0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x00405b54\n"
        "LAB__addr_0x00405b4f:\n\t"
        "cmp                dword ptr [ecx + -0x34], edi\n\t"
        "%{disp8%} je         LAB__addr_0x00405b69\n"
        "LAB__addr_0x00405b54:\n\t"
        "add                ecx, 0x000001c8\n\t"
        "add                eax, 0x000001c8\n\t"
        "cmp                ecx, 0x00c4cdc0\n\t"
        ".byte              0x72, 0xdd\n\t"
        "xor.s              eax, eax\n"
        "LAB__addr_0x00405b69:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}
