#include "Abode.h"
#include "AbodeInfo.h"

const float rdata_float_0_7 asm("__real@3f333333") = 0.7f;
const float rdata_float_0_3 asm("__real@3e999999") = 0.3f;
const float rdata_float_1400_0 asm("__real@44af0000") = 1400.0f;
const float rdata_float_0_2 asm("__real@3e4ccccd") = 0.2f;
const float rdata_float_2000_0 asm("__real@44fa0000") = 2000.0f;
const float rdata_float_1_5 asm("__real@3fc00000") = 1.5f;

__attribute__((no_callee_saves, trailing_asm("call               dword ptr [__imp__timeKillEvent@4]")))
enum ABODE_TYPE __fastcall GetAbodeType__5AbodeFv(struct MultiMapFixed* this)
{
    enum ABODE_TYPE result = ((const struct GAbodeInfo*)this->base.super_object.info)->abodeType;
    return result;
}

__attribute__((XOR32rr_REV, no_callee_saves))
bool32_t __fastcall IsFunctional__5AbodeFv(struct GameThing* this)
{
    bool32_t result;
    asm volatile (
        "push esi\n\t"
        "mov.s esi, ecx\n\t"
        "call ?IsFunctional@MultiMapFixed@@UAE_NXZ\n\t"
        "cmp eax, 0x01\n\t"
        "%{disp8%} jne 0f\n\t"
        "mov eax, dword ptr [esi]\n\t"
        "mov.s ecx, esi\n\t"
        "call dword ptr [eax + 0x890]\n\t"
        "test eax, eax\n\t"
        "%{disp8%} je 0f\n\t"
        "mov eax, 0x00000001\n\t"
        "pop esi\n\t"
        "ret\n"
        "0:\n\t"
        "xor.s eax, eax\n\t"
        "pop esi"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV, prefer_xor8))
uint32_t __fastcall ChecksVerticesVObjects__5AbodeFv(struct Object* this)
{
    return 0;
}

__attribute__((XOR32rr_REV, no_ret))
void __fastcall ReactToPhysicsImpact__5AbodeFP13PhysicsObjectb(struct Object* this, const void* edx, struct PhysicsObject* param_1, bool param_2)
{
    asm volatile (
        "sub                esp, 0x34\n\t"
        "push               ebx\n\t"
        "%{disp8%} mov        ebx, dword ptr [esp + 0x3c]\n\t"
        "push               ebp\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "%{disp8%} mov        edi, dword ptr [ebx + 0x20]\n\t"
        "test               edi, edi\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp32%} je        LAB__addr_0x00406615\n\t"
        "%{disp8%} mov        eax, dword ptr [edi + 0x18]\n\t"
        "mov.s              ecx, edi\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], eax\n\t"
        "call               _jmp_addr_0x00647460\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], eax\n\t"
        "mov                ebp, 0x00000010\n\t"
        "%{disp8%} je         LAB__addr_0x0040628b\n\t"
        "test               byte ptr [ebx + 0x000001d8], 0x04\n\t"
        "%{disp8%} je         LAB__addr_0x0040628b\n\t"
        "%{disp8%} mov        ecx, dword ptr [edi + 0x24]\n\t"
        "push               0x0\n\t"
        "push               esi\n\t"
        "push               ebp\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x004ea900\n"
        "LAB__addr_0x0040628b:\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x10]\n\t"
        "mov                edx, dword ptr [ecx]\n\t"
        "call               dword ptr [edx + 0x7a8]\n\t"
        "test               al, al\n\t"
        "%{disp32%} je        LAB__addr_0x00406615\n\t"
        "%{disp32%} fld       dword ptr [edi + 0x00000104]\n\t"
        "%{disp32%} fld       dword ptr [edi + 0x00000108]\n\t"
        "%{disp32%} fld       dword ptr [edi + 0x0000010c]\n\t"
        "fld                st(0)\n\t"
        "fmul               st, st(1)\n\t"
        "fld                st(2)\n\t"
        "fmul               st, st(3)\n\t"
        "faddp              st(1), st\n\t"
        "fld                st(3)\n\t"
        "fmul               st, st(4)\n\t"
        "faddp              st(1), st\n\t"
        "fsqrt\n\t"
        "fstp               st(3)\n\t"
        "fstp               st(0)\n\t"
        "fstp               st(0)\n\t"
        "%{disp32%} fmul      dword ptr [edi + 0x0000015c]\n\t"
        "%{disp8%} fst        dword ptr [esp + 0x48]\n\t"
        "%{disp32%} fcomp     dword ptr [__real@44fa0000]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp32%} jne       LAB__addr_0x00406511\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x890]\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x004064ba\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x898]\n\t"
        "%{disp32%} mov       ebp, dword ptr [esi + 0x00000090]\n\t"
        "test               ebp, ebp\n\t"
        "%{disp32%} je        LAB__addr_0x0040638f\n\t"
        "%{disp32%} fcom      dword ptr [__real@3e4ccccd]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x00406361\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float1p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x40\n\t"
        "%{disp8%} jne        LAB__addr_0x00406363\n\t"
        "test               ebp, ebp\n\t"
        "%{disp8%} je         LAB__addr_0x0040633c\n\t"
        "mov.s              ecx, ebp\n\t"
        "call               ??1FragMesh@@QAE@XZ\n\t"
        "push               ebp\n\t"
        "call               ??3@YAXPAX@Z\n\t"
        "add                esp, 0x04\n"
        "LAB__addr_0x0040633c:\n\t"
        "push               0x00000778\n\t"
        "push               0x009c7fbc\n\t"
        "push               0x28\n\t"
        "call               ___nw__FUl\n\t"
        "add                esp, 0x0c\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x004063b6\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x40]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x007f6f00\n\t"
        "%{disp8%} jmp        LAB__addr_0x004063b8\n"
        "LAB__addr_0x00406361:\n\t"
        "fstp               st(0)\n"
        "LAB__addr_0x00406363:\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x10]\n\t"
        "cmp                dword ptr [ebp + 0x00], ecx\n\t"
        "%{disp8%} jne        LAB__addr_0x0040638a\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x48]\n\t"
        "%{disp32%} fcomp     dword ptr [__real@44af0000]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp8%} jne        LAB__addr_0x004063be\n\t"
        "cmp                dword ptr [ebx + 0x18], esi\n\t"
        "%{disp8%} jne        LAB__addr_0x004063be\n\t"
        "%{disp8%} mov        dword ptr [ebx + 0x1c], ecx\n\t"
        "%{disp8%} mov        dword ptr [edi + 0x1c], esi\n\t"
        "%{disp8%} jmp        LAB__addr_0x004063be\n"
        "LAB__addr_0x0040638a:\n\t"
        "%{disp8%} mov        dword ptr [ebp + 0x00], ecx\n\t"
        "%{disp8%} jmp        LAB__addr_0x004063be\n"
        "LAB__addr_0x0040638f:\n\t"
        "push               0x0000077d\n\t"
        "fstp               st(0)\n\t"
        "push               0x009c7fbc\n\t"
        "push               0x28\n\t"
        "call               ___nw__FUl\n\t"
        "add                esp, 0x0c\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x004063b6\n\t"
        "%{disp8%} mov        edx, dword ptr [esi + 0x40]\n\t"
        "push               edx\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x007f6f00\n\t"
        "%{disp8%} jmp        LAB__addr_0x004063b8\n"
        "LAB__addr_0x004063b6:\n\t"
        "xor.s              eax, eax\n"
        "LAB__addr_0x004063b8:\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000090], eax\n"
        "LAB__addr_0x004063be:\n\t"
        "%{disp32%} fld       dword ptr [edi + 0x00000104]\n\t"
        "%{disp32%} mov       eax, dword ptr [edi + 0x000000c8]\n\t"
        "%{disp32%} fmul      dword ptr [__real@3e999999]\n\t"
        "%{disp32%} mov       ecx, dword ptr [edi + 0x000000cc]\n\t"
        "%{disp32%} mov       edx, dword ptr [edi + 0x000000d0]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x24], eax\n\t"
        "%{disp8%} mov        al, byte ptr [esp + 0x4c]\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x18]\n\t"
        "test               al, al\n\t"
        "%{disp32%} fld       dword ptr [edi + 0x00000108]\n\t"
        "%{disp32%} fmul      dword ptr [__real@3e999999]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x28], ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x2c], edx\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x1c]\n\t"
        "%{disp32%} fld       dword ptr [edi + 0x0000010c]\n\t"
        "%{disp32%} fmul      dword ptr [__real@3e999999]\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x20]\n\t"
        "%{disp8%} je         LAB__addr_0x0040644e\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x00000090]\n\t"
        "push               0x00406620\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x28]\n\t"
        "push               eax\n\t"
        "call               _jmp_addr_0x0076d4c0\n\t"
        "call               _jmp_addr_0x00464440\n\t"
        "fld                st(0)\n\t"
        "%{disp8%} fmul       dword ptr [esp + 0x18]\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x18]\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x1c]\n\t"
        "fmul               st, st(1)\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x1c]\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x20]\n\t"
        "fmul               st, st(1)\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x20]\n\t"
        "fstp               st(0)\n"
        "LAB__addr_0x0040644e:\n\t"
        "%{disp32%} fld       dword ptr [edi + 0x00000178]\n\t"
        "push               esi\n\t"
        "%{disp32%} fadd      dword ptr [__real@3f333333]\n\t"
        "push               ecx\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x20]\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x2c]\n\t"
        "fstp               dword ptr [esp]\n\t"
        "push               ecx\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x00000090]\n\t"
        "push               edx\n\t"
        "call               _jmp_addr_0x007f7d40\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x00000090]\n\t"
        "call               _jmp_addr_0x007f7230\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float1p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x40\n\t"
        "%{disp8%} je         LAB__addr_0x004064ba\n\t"
        "%{disp32%} mov       edi, dword ptr [esi + 0x00000090]\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x004064a6\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ??1FragMesh@@QAE@XZ\n\t"
        "push               edi\n\t"
        "call               ??3@YAXPAX@Z\n\t"
        "add                esp, 0x04\n"
        "LAB__addr_0x004064a6:\n\t"
        "pop                edi\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000090], 0x00000000\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x34\n\t"
        "ret                0x0008\n"
        "LAB__addr_0x004064ba:\n\t"
        "%{disp8%} mov        eax, dword ptr [ebx + 0x1c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x004064cf\n\t"
        "%{disp8%} mov        eax, dword ptr [ebx + 0x20]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x004064cd\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x1c]\n\t"
        "%{disp8%} jmp        LAB__addr_0x004064cf\n"
        "LAB__addr_0x004064cd:\n\t"
        "xor.s              eax, eax\n"
        "LAB__addr_0x004064cf:\n\t"
        "push               0x0\n\t"
        "push               0x009c8060\n\t"
        "push               0x009c7f50\n\t"
        "push               0x0\n\t"
        "push               eax\n\t"
        "call               ___RTDynamicCast\n\t"
        "add                esp, 0x14\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x004064ee\n\t"
        "or                 byte ptr [esi + 0x7c], 0x20\n"
        "LAB__addr_0x004064ee:\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x14]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x10]\n\t"
        "push               eax\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?ApplyEffectsDueToPhysicalDestruction@Abode@@QAEXPAVObject@@PAVGPlayer@@@Z\n\t"
        "%{disp8%} mov        al, byte ptr [esi + 0x7c]\n\t"
        "pop                edi\n\t"
        "and                al, -0x21\n\t"
        "%{disp8%} mov        byte ptr [esi + 0x7c], al\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x34\n\t"
        "ret                0x0008\n"
        "LAB__addr_0x00406511:\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x48]\n\t"
        "%{disp32%} fcomp     dword ptr [__real@447a0000]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp8%} jne        LAB__addr_0x0040652c\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x30], 0x00000002\n\t"
        "%{disp8%} jmp        LAB__addr_0x00406549\n"
        "LAB__addr_0x0040652c:\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x48]\n\t"
        "%{disp32%} fcomp     dword ptr [__real@43960000]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp32%} jne       LAB__addr_0x00406615\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x30], 0x00000003\n"
        "LAB__addr_0x00406549:\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x18]\n\t"
        "push               edx\n\t"
        "%{disp8%} lea        ecx, dword ptr [esi + 0x14]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x3c], 0x00000016\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x40], ebp\n\t"
        "call               @GetLHPoint__9MapCoordsCFv@12\n\t"
        "mov                ecx, dword ptr [eax]\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x04]\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x08]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x24], ecx\n\t"
        "%{disp32%} mov       ecx, dword ptr [_game]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x28], edx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x2c], eax\n\t"
        "call               ?GetCamera@GGame@@QAEPAVGCamera@@XZ\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x00406615\n\t"
        "%{disp32%} mov       ecx, dword ptr [_game]\n\t"
        "call               ?GetCamera@GGame@@QAEPAVGCamera@@XZ\n\t"
        "%{disp32%} mov       ecx, dword ptr [data_bytes + 0x4dbdb8]\n\t"
        "%{disp32%} mov       edx, dword ptr [data_bytes + 0x4dbdbc]\n\t"
        "%{disp32%} mov       eax, dword ptr [data_bytes + 0x4dbdc0]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], ecx\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x18]\n\t"
        "%{disp8%} fsub       dword ptr [esp + 0x24]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x1c], edx\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x1c]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x20], eax\n\t"
        "%{disp8%} fsub       dword ptr [esp + 0x28]\n\t"
        "%{disp32%} mov       ecx, dword ptr [_global]\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x20]\n\t"
        "push               0x0\n\t"
        "%{disp8%} fsub       dword ptr [esp + 0x30]\n\t"
        "push               0x0\n\t"
        "push               0x0\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x40], 0x00000000\n\t"
        "fld                st(0)\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x4c], 0x0000004b\n\t"
        "fmul               st, st(1)\n\t"
        "%{disp32%} mov       edx, dword ptr [ecx + 0x000003b0]\n\t"
        "fld                st(2)\n\t"
        "push               edx\n\t"
        "fmul               st, st(3)\n\t"
        "push               0x0\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x44]\n\t"
        "faddp              st(1), st\n\t"
        "fld                st(3)\n\t"
        "push               eax\n\t"
        "fmul               st, st(4)\n\t"
        "push               ecx\n\t"
        "faddp              st(1), st\n\t"
        "fsqrt\n\t"
        "fstp               st(3)\n\t"
        "fstp               st(0)\n\t"
        "fstp               st(0)\n\t"
        "fstp               dword ptr [esp]\n\t"
        "push               esi\n\t"
        "call               _jmp_addr_0x0042a4b0\n"
        "LAB__addr_0x00406615:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x34\n\t"
        "ret                0x0008\n\t"
        "nop\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x04]\n\t"
        "push               0x00000740\n\t"
        "push               0x009c7fbc\n\t"
        "push               eax\n\t"
        "call               ?GameFloatRand@GRand@@SAMM@Z\n\t"
        "add                esp, 0x0c\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((no_callee_saves, ret_cleanup_override(0x0008)))
void __fastcall ApplyEffectsDueToPhysicalDestruction__5AbodeFP6ObjectP7GPlayer(struct Abode* this, const void* edx, struct Object* object, struct GPlayer* player)
{
    asm volatile (
        "sub                esp, 0x00000090\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x08]\n\t"
        "push               eax\n\t"
        "%{disp8%} lea        ecx, dword ptr [esi + 0x14]\n\t"
        "call               @GetLHPoint__9MapCoordsCFv@12\n\t"
        "mov                ecx, dword ptr [eax]\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x04]\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x08]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], ecx\n\t"
        "%{disp32%} mov       ecx, dword ptr [_game]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], edx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x1c], eax\n\t"
        "call               ?GetCamera@GGame@@QAEPAVGCamera@@XZ\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x004067ef\n\t"
        "%{disp32%} mov       ecx, dword ptr [_game]\n\t"
        "push               edi\n\t"
        "call               ?GetCamera@GGame@@QAEPAVGCamera@@XZ\n\t"
        "%{disp32%} mov       ecx, dword ptr [data_bytes + 0x4dbdb8]\n\t"
        "%{disp32%} mov       edx, dword ptr [data_bytes + 0x4dbdbc]\n\t"
        "%{disp32%} mov       eax, dword ptr [data_bytes + 0x4dbdc0]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], ecx\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x0c]\n\t"
        "%{disp8%} fsub       dword ptr [esp + 0x18]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], edx\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x10]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], eax\n\t"
        "%{disp8%} fsub       dword ptr [esp + 0x1c]\n\t"
        "%{disp32%} mov       ecx, dword ptr [_global]\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x14]\n\t"
        "push               0x0\n\t"
        "%{disp8%} fsub       dword ptr [esp + 0x24]\n\t"
        "push               0x0\n\t"
        "push               0x0\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x34], 0x00000001\n\t"
        "fld                st(0)\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x38], 0x00000000\n\t"
        "fmul               st, st(1)\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x3c], 0x00000016\n\t"
        "fld                st(2)\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x40], 0x00000009\n\t"
        "fmul               st, st(3)\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x44], 0x0000004b\n\t"
        "%{disp32%} mov       edx, dword ptr [ecx + 0x000003b0]\n\t"
        "faddp              st(1), st\n\t"
        "fld                st(3)\n\t"
        "push               edx\n\t"
        "fmul               st, st(4)\n\t"
        "push               0x0\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x3c]\n\t"
        "push               eax\n\t"
        "faddp              st(1), st\n\t"
        "push               ecx\n\t"
        "fsqrt\n\t"
        "fstp               st(3)\n\t"
        "fstp               st(0)\n\t"
        "fstp               st(0)\n\t"
        "fstp               dword ptr [esp]\n\t"
        "push               esi\n\t"
        "call               _jmp_addr_0x0042a4b0\n\t"
        "%{disp32%} mov       edi, dword ptr [esp + 0x000000a0]\n\t"
        "%{disp32%} mov       ecx, dword ptr [esp + 0x0000009c]\n\t"
        "push               edi\n\t"
        "push               ecx\n\t"
        "push               0x3\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x48]\n\t"
        "call               _jmp_addr_0x00524fe0\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x00000090]\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x004067d2\n\t"
        "%{disp8%} fld        dword ptr [eax + 0x18]\n\t"
        "push               ebx\n\t"
        "%{disp8%} fst        dword ptr [esp + 0x28]\n\t"
        "%{disp32%} fcomp     dword ptr [rdata_bytes + 0xd7188]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x00406786\n\t"
        "%{disp32%} mov       ecx, dword ptr [_game]\n\t"
        "call               _jmp_addr_0x00555880\n\t"
        "test               edi, edi\n\t"
        "mov.s              ebx, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00406786\n\t"
        "push               ebx\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?IsMemberOfThisPlayer@GPlayer@@QAEIPAVGInterfaceStatus@@@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00406786\n\t"
        "%{disp8%} mov        ecx, dword ptr [ebx + 0x30]\n\t"
        "push               esi\n\t"
        "call               _jmp_addr_0x0071d070\n"
        "LAB__addr_0x00406786:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x11c]\n\t"
        "%{disp8%} fsub       dword ptr [esp + 0x28]\n\t"
        "pop                ebx\n\t"
        "%{disp8%} fst        dword ptr [esp + 0x08]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float0p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x004067ae\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], 0x00000000\n"
        "LAB__addr_0x004067ae:\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x08]\n\t"
        "push               eax\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x48]\n\t"
        "call               _jmp_addr_0x00525720\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x7c]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               _jmp_addr_0x00637930\n\t"
        "push               eax\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x40]\n\t"
        "call               _jmp_addr_0x00525950\n"
        "LAB__addr_0x004067d2:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               0x0\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x40]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x5cc]\n\t"
        "fstp               st(0)\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x3c]\n\t"
        "call               _jmp_addr_0x00436960\n\t"
        "pop                edi\n"
        "LAB__addr_0x004067ef:\n\t"
        "pop                esi\n\t"
        "add                esp, 0x00000090"
        ::: "eax", "ecx", "edx", "memory"
    );
}

__attribute__((XOR32rr_REV))
bool __fastcall CanBecomeAPhysicsObject__5AbodeFv(struct Object* this)
{
    return 0;
}

uint32_t __fastcall GetScriptObjectType__5AbodeFv(struct GameThingWithPos* this)
{
    return 2;
}

uint32_t __fastcall InterfaceValidToTap__5AbodeFP16GInterfaceStatus(struct Object* this, const void* edx, struct GInterfaceStatus* status)
{
    return 1;
}

__attribute__((XOR32rr_REV, no_callee_saves, ret_cleanup_override(0x0004)))
uint32_t __fastcall InterfaceTap__5AbodeFP16GInterfaceStatus(struct Object* this, const void* edx, struct GInterfaceStatus* status)
{
    uint32_t result;
    asm volatile (
        "sub                esp, 0x00000174\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "mov.s              edi, ecx\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "%{disp32%} mov       dword ptr [_abode_town_00c4cc6c], eax\n\t"
        "call               _jmp_addr_0x00829690\n\t"
        "%{disp32%} mov       esi, dword ptr [edi + 0x000000a0]\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x00406864\n"
        "LAB__addr_0x00406853:\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?SetStateWhenTappedOnAbode@Villager@@QAE_NXZ\n\t"
        "%{disp32%} mov       esi, dword ptr [esi + 0x000000e4]\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} jne        LAB__addr_0x00406853\n"
        "LAB__addr_0x00406864:\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x8c4]\n\t"
        "test               al, 0x02\n\t"
        "%{disp32%} je        LAB__addr_0x00406959\n\t"
        "%{disp32%} mov       ecx, dword ptr [_game]\n\t"
        "call               _jmp_addr_0x00555880\n\t"
        "%{disp32%} mov       esi, dword ptr [esp + 0x00000180]\n\t"
        "cmp.s              esi, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x004068c0\n\t"
        "%{disp32%} mov       ecx, dword ptr [_game]\n\t"
        "xor.s              eax, eax\n\t"
        "%{disp32%} mov       al, byte ptr [ecx + 0x00205a59]\n\t"
        "lea                edx, dword ptr [eax + eax * 0x4]\n\t"
        "lea                edx, dword ptr [eax + edx * 0x8]\n\t"
        "lea                eax, dword ptr [eax + edx * 0x2]\n\t"
        "shl                eax, 5\n\t"
        "%{disp8%} lea        ecx, dword ptr [eax + ecx * 0x1 + 0x18]\n\t"
        "call               _jmp_addr_0x0064ab20\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x004068c0\n\t"
        "%{disp8%} lea        ecx, dword ptr [eax + 0x78]\n\t"
        "push               0x39\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x0046c050\n"
        "LAB__addr_0x004068c0:\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x000000d0]\n\t"
        "%{disp32%} mov       edx, dword ptr [esi + 0x000000c8]\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x000000cc]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], ecx\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x14]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], edx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], eax\n\t"
        "call               dword ptr [rdata_bytes + 0x75c]\n\t"
        "%{disp32%} mov       ecx, dword ptr [_global]\n\t"
        "%{disp32%} mov       edx, dword ptr [ecx + 0x000003ac]\n\t"
        "%{disp32%} mov       eax, dword ptr [_windmill_int_00c4cc7c]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], edx\n\t"
        "%{disp8%} lea        edx, dword ptr [eax + 0x6e]\n\t"
        "inc                eax\n\t"
        "cmp                eax, 0x09\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x38], edx\n\t"
        "%{disp32%} mov       dword ptr [_windmill_int_00c4cc7c], eax\n\t"
        "%{disp8%} jne        LAB__addr_0x00406919\n\t"
        "%{disp32%} mov       dword ptr [_windmill_int_00c4cc7c], 0x00000000\n"
        "LAB__addr_0x00406919:\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x0c]\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x08]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x48], edx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x44], eax\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x10]\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x14]\n\t"
        "push               edx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x38], edi\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x20], 0x00000001\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x50], eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x24], 0x00000000\n\t"
        "call               @PlaySoundEffect__6GAudioFP20LH_SamplePlayOptions@12\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x14]\n\t"
        "call               dword ptr [rdata_bytes + 0x758]\n"
        "LAB__addr_0x00406959:\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x00000174"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves))
float __fastcall GetDesireToBeRepaired__5AbodeFv(struct MultiMapFixed* this)
{
    float result;
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "%{disp8%} mov        edi, dword ptr [eax + 0x28]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x884]\n\t"
        "%{disp32%} fcomp     dword ptr [edi + 0x0000010c]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp8%} je         LAB__addr_0x004069b3\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x28]\n\t"
        "test               byte ptr [eax + 0x00000120], 0x02\n\t"
        "%{disp8%} je         LAB__addr_0x004069a9\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x000000a4]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x004069b3\n"
        "LAB__addr_0x004069a9:\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetDesireToBeRepaired@MultiMapFixed@@UAEMXZ\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x004069b3:\n\t"
        "%{disp32%} fld       dword ptr [_rdata_float0p0]\n\t"
        "pop                edi\n\t"
        "pop                esi"
        : "=t"(result) :: "eax", "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV, no_ret))
struct Villager* __fastcall FindVillager__5AbodeFPFP16GameThingWithPos18SCRIPT_OBJECT_TYPEUl_i18SCRIPT_OBJECT_TYPEUl(struct Abode* this, const void* edx, int (* param_1)(struct GameThingWithPos* param_1, enum SCRIPT_OBJECT_TYPE param_2, uint32_t param_3), enum SCRIPT_OBJECT_TYPE param_2, uint32_t param_3)
{
    asm("push               ebx");                                           // 0x004069c0    53
    asm("push               ebp");                                           // 0x004069c1    55
    asm("push               esi");                                           // 0x004069c2    56
    asm("{disp32} mov       esi, dword ptr [ecx + 0x000000a0]");             // 0x004069c3    8bb1a0000000
    asm("test               esi, esi");                                      // 0x004069c9    85f6
    asm("push               edi");                                           // 0x004069cb    57
    asm("{disp8} je         LAB__addr_0x004069f0");                          // 0x004069cc    7422
    asm("{disp8} mov        edi, dword ptr [esp + 0x1c]");                   // 0x004069ce    8b7c241c
    asm("{disp8} mov        ebx, dword ptr [esp + 0x18]");                   // 0x004069d2    8b5c2418
    asm("{disp8} mov        ebp, dword ptr [esp + 0x14]");                   // 0x004069d6    8b6c2414
    asm("LAB__addr_0x004069da:");
    asm("push               edi");                                           // 0x004069da    57
    asm("push               ebx");                                           // 0x004069db    53
    asm("push               esi");                                           // 0x004069dc    56
    asm("call               ebp");                                           // 0x004069dd    ffd5
    asm("add                esp, 0x0c");                                     // 0x004069df    83c40c
    asm("test               eax, eax");                                      // 0x004069e2    85c0
    asm("{disp8} jne        LAB__addr_0x004069f9");                          // 0x004069e4    7513
    asm("{disp32} mov       esi, dword ptr [esi + 0x000000e4]");             // 0x004069e6    8bb6e4000000
    asm("test               esi, esi");                                      // 0x004069ec    85f6
    asm("{disp8} jne        LAB__addr_0x004069da");                          // 0x004069ee    75ea
    asm("LAB__addr_0x004069f0:");
    asm("pop                edi");                                           // 0x004069f0    5f
    asm("pop                esi");                                           // 0x004069f1    5e
    asm("pop                ebp");                                           // 0x004069f2    5d
    asm("xor.s              eax, eax");                                      // 0x004069f3    33c0
    asm("pop                ebx");                                           // 0x004069f5    5b
    asm("ret                0x000c");                                        // 0x004069f6    c20c00
    asm("LAB__addr_0x004069f9:");
    asm("pop                edi");                                           // 0x004069f9    5f
    asm("mov.s              eax, esi");                                      // 0x004069fa    8bc6
    asm("pop                esi");                                           // 0x004069fc    5e
    asm("pop                ebp");                                           // 0x004069fd    5d
    asm("pop                ebx");                                           // 0x004069fe    5b
    asm("ret                0x000c");                                        // 0x004069ff    c20c00
    __builtin_unreachable();
}

__attribute__((XOR32rr_REV, no_callee_saves, ret_cleanup_override(0x0004)))
uint32_t __fastcall Save__5AbodeFR10GameOSFile(struct GameThing* this, const void* edx, struct GameOSFile* file)
{
    uint32_t result;
    asm volatile (
        "push               ecx\n\t"
        "push               ebx\n\t"
        "push               esi\n\t"
        "%{disp8%} mov        esi, dword ptr [esp + 0x10]\n\t"
        "mov.s              ebx, ecx\n\t"
        "push               esi\n\t"
        "call               ?Save@MultiMapFixed@@UAEIPAVGameOSFile@@@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x00406d09\n\t"
        "%{disp32%} mov       eax, dword ptr [data_bytes + 0x226990]\n\t"
        "push               ebp\n\t"
        "xor.s              ebp, ebp\n\t"
        "cmp.s              eax, ebp\n\t"
        "push               edi\n\t"
        "%{disp32%} je        LAB__addr_0x00406ad6\n\t"
        "push               ebp\n\t"
        "push               0x1\n\t"
        "%{disp8%} lea        edi, dword ptr [ebx + 0x7c]\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @Write__8LHOSFileFPvUlPUl@20\n\t"
        "cmp                eax, 0x03\n\t"
        "%{disp8%} jne        LAB__addr_0x00406a51\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x226990], ebp\n"
        "LAB__addr_0x00406a51:\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x00000214]\n\t"
        "xor.s              eax, eax\n\t"
        "mov                al, byte ptr [edi]\n\t"
        "inc                eax\n\t"
        "add.s              ecx, eax\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000214], ecx\n\t"
        "cmp                dword ptr [data_bytes + 0x226990], ebp\n\t"
        "%{disp8%} je         LAB__addr_0x00406ad6\n\t"
        "push               ebp\n\t"
        "push               0xc\n\t"
        "%{disp32%} lea       edi, dword ptr [ebx + 0x00000080]\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @Write__8LHOSFileFPvUlPUl@20\n\t"
        "cmp                eax, 0x03\n\t"
        "%{disp8%} jne        LAB__addr_0x00406a88\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x226990], ebp\n"
        "LAB__addr_0x00406a88:\n\t"
        "%{disp32%} mov       edx, dword ptr [esi + 0x00000214]\n\t"
        "xor.s              ecx, ecx\n\t"
        "mov                cl, byte ptr [edi]\n\t"
        "add                ecx, 0xc\n\t"
        "add.s              edx, ecx\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000214], edx\n\t"
        "cmp                dword ptr [data_bytes + 0x226990], ebp\n\t"
        "%{disp8%} je         LAB__addr_0x00406ad6\n\t"
        "push               ebp\n\t"
        "push               0x4\n\t"
        "%{disp32%} lea       edi, dword ptr [ebx + 0x00000094]\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @Write__8LHOSFileFPvUlPUl@20\n\t"
        "cmp                eax, 0x03\n\t"
        "%{disp8%} jne        LAB__addr_0x00406ac1\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x226990], ebp\n"
        "LAB__addr_0x00406ac1:\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x00000214]\n\t"
        "xor.s              edx, edx\n\t"
        "mov                dl, byte ptr [edi]\n\t"
        "add                edx, 0x04\n\t"
        "add.s              eax, edx\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000214], eax\n"
        "LAB__addr_0x00406ad6:\n\t"
        "%{disp32%} mov       eax, dword ptr [ebx + 0x00000098]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?WritePtr@GameOSFile@@QAEXPAVGameThing@@@Z\n\t"
        "cmp                dword ptr [data_bytes + 0x226990], ebp\n\t"
        "%{disp32%} je        LAB__addr_0x00406c4b\n\t"
        "%{disp32%} mov       ecx, dword ptr [ebx + 0x000000a4]\n\t"
        "%{disp32%} lea       eax, dword ptr [ebx + 0x000000a4]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], ecx\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               _WriteIt_u32___10GameOSFileFRUl);//??$WriteIt@I@GameOSFile@@QAEXAAI@Z\n\t"
        "xor.s              edi, edi\n"
        "LAB__addr_0x00406b0a:\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} jne        LAB__addr_0x00406b16\n\t"
        "%{disp32%} mov       edi, dword ptr [ebx + 0x000000a0]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00406b1c\n"
        "LAB__addr_0x00406b16:\n\t"
        "%{disp32%} mov       edi, dword ptr [edi + 0x000000e4]\n"
        "LAB__addr_0x00406b1c:\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x00406b4f\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x18]\n\t"
        "inc                ebp\n\t"
        "cmp.s              ebp, eax\n\t"
        "%{disp8%} jg         LAB__addr_0x00406b40\n\t"
        "%{disp32%} mov       eax, dword ptr [data_bytes + 0x226990]\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x00406c4b\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?WritePtr@GameOSFile@@QAEXPAVGameThing@@@Z\n\t"
        "%{disp8%} jmp        LAB__addr_0x00406b0a\n"
        "LAB__addr_0x00406b40:\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x226990], 0x00000000\n\t"
        "%{disp32%} jmp       LAB__addr_0x00406c4b\n"
        "LAB__addr_0x00406b4f:\n\t"
        "%{disp32%} mov       eax, dword ptr [data_bytes + 0x226990]\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x00406c4b\n\t"
        "push               0x0\n\t"
        "push               0x1\n\t"
        "%{disp32%} lea       edi, dword ptr [ebx + 0x000000b4]\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @Write__8LHOSFileFPvUlPUl@20\n\t"
        "cmp                eax, 0x03\n\t"
        "%{disp8%} jne        LAB__addr_0x00406b7d\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x226990], 0x00000000\n"
        "LAB__addr_0x00406b7d:\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x00000214]\n\t"
        "xor.s              edx, edx\n\t"
        "mov                dl, byte ptr [edi]\n\t"
        "inc                edx\n\t"
        "add.s              ecx, edx\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000214], ecx\n\t"
        "%{disp32%} mov       eax, dword ptr [data_bytes + 0x226990]\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x00406c4b\n\t"
        "push               0x0\n\t"
        "push               0x1\n\t"
        "%{disp32%} lea       edi, dword ptr [ebx + 0x000000b6]\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @Write__8LHOSFileFPvUlPUl@20\n\t"
        "cmp                eax, 0x03\n\t"
        "%{disp8%} jne        LAB__addr_0x00406bbe\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x226990], 0x00000000\n"
        "LAB__addr_0x00406bbe:\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x00000214]\n\t"
        "xor.s              eax, eax\n\t"
        "mov                al, byte ptr [edi]\n\t"
        "inc                eax\n\t"
        "add.s              ecx, eax\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000214], ecx\n\t"
        "%{disp32%} mov       eax, dword ptr [data_bytes + 0x226990]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00406c4b\n\t"
        "push               0x0\n\t"
        "push               0x1\n\t"
        "%{disp32%} lea       edi, dword ptr [ebx + 0x000000b7]\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @Write__8LHOSFileFPvUlPUl@20\n\t"
        "cmp                eax, 0x03\n\t"
        "%{disp8%} jne        LAB__addr_0x00406bfb\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x226990], 0x00000000\n"
        "LAB__addr_0x00406bfb:\n\t"
        "%{disp32%} mov       edx, dword ptr [esi + 0x00000214]\n\t"
        "xor.s              ecx, ecx\n\t"
        "mov                cl, byte ptr [edi]\n\t"
        "inc                ecx\n\t"
        "add.s              edx, ecx\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000214], edx\n\t"
        "%{disp32%} mov       eax, dword ptr [data_bytes + 0x226990]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00406c4b\n\t"
        "push               0x0\n\t"
        "push               0x1\n\t"
        "%{disp32%} lea       edi, dword ptr [ebx + 0x000000b8]\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @Write__8LHOSFileFPvUlPUl@20\n\t"
        "cmp                eax, 0x03\n\t"
        "%{disp8%} jne        LAB__addr_0x00406c38\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x226990], 0x00000000\n"
        "LAB__addr_0x00406c38:\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x00000214]\n\t"
        "xor.s              edx, edx\n\t"
        "mov                dl, byte ptr [edi]\n\t"
        "inc                edx\n\t"
        "add.s              eax, edx\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000214], eax\n"
        "LAB__addr_0x00406c4b:\n\t"
        "%{disp32%} mov       eax, dword ptr [data_bytes + 0x226990]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], 0x00000002\n\t"
        "%{disp8%} je         LAB__addr_0x00406c95\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x18]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               _WriteIt_u32___10GameOSFileFRUl);//??$WriteIt@I@GameOSFile@@QAEXAAI@Z\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x18]\n\t"
        "xor.s              ebp, ebp\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jbe        LAB__addr_0x00406c95\n\t"
        "%{disp32%} lea       edi, dword ptr [ebx + 0x000000bc]\n"
        "LAB__addr_0x00406c78:\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               _WriteIt_u32___10GameOSFileFRUl);//??$WriteIt@I@GameOSFile@@QAEXAAI@Z\n\t"
        "%{disp32%} mov       eax, dword ptr [data_bytes + 0x226990]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00406c95\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x18]\n\t"
        "inc                ebp\n\t"
        "add                edi, 0x04\n\t"
        "cmp.s              ebp, eax\n\t"
        ".byte              0x72, 0xe3\n"
        "LAB__addr_0x00406c95:\n\t"
        "%{disp32%} mov       edx, dword ptr [ebx + 0x00000090]\n\t"
        "%{disp32%} mov       ecx, dword ptr [data_bytes + 0x226990]\n\t"
        "xor.s              eax, eax\n\t"
        "test               edx, edx\n\t"
        "setne              al\n\t"
        "test               ecx, ecx\n\t"
        "pop                edi\n\t"
        "pop                ebp\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], eax\n\t"
        "%{disp8%} je         LAB__addr_0x00406cee\n\t"
        "push               0x0\n\t"
        "push               0x4\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x10]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @Write__8LHOSFileFPvUlPUl@20\n\t"
        "cmp                eax, 0x03\n\t"
        "%{disp8%} jne        LAB__addr_0x00406cd1\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x226990], 0x00000000\n"
        "LAB__addr_0x00406cd1:\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x08]\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x00000214]\n\t"
        "mov.s              edx, eax\n\t"
        "and                edx, 0x000000ff\n\t"
        "add                edx, 0x04\n\t"
        "add.s              ecx, edx\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000214], ecx\n"
        "LAB__addr_0x00406cee:\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00406cfe\n\t"
        "%{disp32%} mov       ecx, dword ptr [ebx + 0x00000090]\n\t"
        "push               esi\n\t"
        "call               _jmp_addr_0x0076d680\n"
        "LAB__addr_0x00406cfe:\n\t"
        "pop                esi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebx\n\t"
        "pop                ecx\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x00406d09:\n\t"
        "pop                esi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                ebx\n\t"
        "pop                ecx"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV, no_callee_saves, ret_cleanup_override(0x0004)))
uint32_t __fastcall Load__5AbodeFR10GameOSFile(struct GameThing* this, const void* edx, struct GameOSFile* file)
{
    uint32_t result;
    asm volatile (
        "sub                esp, 0x08\n\t"
        "push               ebp\n\t"
        "push               esi\n\t"
        "%{disp8%} mov        esi, dword ptr [esp + 0x14]\n\t"
        "mov.s              ebp, ecx\n\t"
        "push               esi\n\t"
        "call               @Load__13MultiMapFixedFR10GameOSFile@12\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x00407015\n\t"
        "%{disp32%} mov       eax, dword ptr [data_bytes + 0x226994]\n\t"
        "push               ebx\n\t"
        "xor.s              ebx, ebx\n\t"
        "cmp.s              eax, ebx\n\t"
        "push               edi\n\t"
        "%{disp8%} lea        edi, dword ptr [ebp + 0x7c]\n\t"
        "%{disp8%} je         LAB__addr_0x00406d72\n\t"
        "push               ebx\n\t"
        "push               0x1\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @Read__8LHOSFileFPvUlPUl@20\n\t"
        "cmp                eax, 0x03\n\t"
        "%{disp8%} jne        LAB__addr_0x00406d5f\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x226994], ebx\n"
        "LAB__addr_0x00406d5f:\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x00000214]\n\t"
        "xor.s              eax, eax\n\t"
        "mov                al, byte ptr [edi]\n\t"
        "inc                eax\n\t"
        "add.s              ecx, eax\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000214], ecx\n"
        "LAB__addr_0x00406d72:\n\t"
        "cmp                dword ptr [data_bytes + 0x226994], ebx\n\t"
        "%{disp32%} lea       edi, dword ptr [ebp + 0x00000080]\n\t"
        "%{disp8%} je         LAB__addr_0x00406dab\n\t"
        "push               ebx\n\t"
        "push               0xc\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @Read__8LHOSFileFPvUlPUl@20\n\t"
        "cmp                eax, 0x03\n\t"
        "%{disp8%} jne        LAB__addr_0x00406d96\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x226994], ebx\n"
        "LAB__addr_0x00406d96:\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x00000214]\n\t"
        "xor.s              ecx, ecx\n\t"
        "mov                cl, byte ptr [edi]\n\t"
        "add                ecx, 0xc\n\t"
        "add.s              eax, ecx\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000214], eax\n"
        "LAB__addr_0x00406dab:\n\t"
        "cmp                dword ptr [data_bytes + 0x226994], ebx\n\t"
        "%{disp32%} lea       edi, dword ptr [ebp + 0x00000094]\n\t"
        "%{disp8%} je         LAB__addr_0x00406de4\n\t"
        "push               ebx\n\t"
        "push               0x4\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @Read__8LHOSFileFPvUlPUl@20\n\t"
        "cmp                eax, 0x03\n\t"
        "%{disp8%} jne        LAB__addr_0x00406dcf\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x226994], ebx\n"
        "LAB__addr_0x00406dcf:\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x00000214]\n\t"
        "xor.s              edx, edx\n\t"
        "mov                dl, byte ptr [edi]\n\t"
        "add                edx, 0x04\n\t"
        "add.s              eax, edx\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000214], eax\n"
        "LAB__addr_0x00406de4:\n\t"
        "%{disp32%} lea       eax, dword ptr [ebp + 0x00000098]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @ReadPtr__10GameOSFileFPP9GameThing@12\n\t"
        "cmp                dword ptr [data_bytes + 0x226994], ebx\n\t"
        "%{disp8%} je         LAB__addr_0x00406e41\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x1c]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               _ReadIt_i32___10GameOSFileFRl\n\t"
        "cmp                dword ptr [esp + 0x1c], ebx\n\t"
        "%{disp8%} jle        LAB__addr_0x00406e41\n\t"
        "%{disp32%} lea       edi, dword ptr [ebp + 0x000000a0]\n"
        "LAB__addr_0x00406e12:\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x10]\n\t"
        "push               edx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @ReadPtr__10GameOSFileFPP9GameThing@12\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x10]\n\t"
        "%{disp32%} mov       dword ptr [eax + 0x000000e4], ebx\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x10]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, edi\n\t"
        "call               _AddToLast__21LHListHead_8Villager_FP8Villager\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x1c]\n\t"
        "dec                eax\n\t"
        "cmp.s              eax, ebx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x1c], eax\n\t"
        "%{disp8%} jg         LAB__addr_0x00406e12\n"
        "LAB__addr_0x00406e41:\n\t"
        "%{disp32%} mov       dword ptr [ebp + 0x000000a8], ebx\n\t"
        "%{disp32%} mov       dword ptr [ebp + 0x000000ac], ebx\n\t"
        "cmp                dword ptr [data_bytes + 0x226994], ebx\n\t"
        "%{disp32%} lea       edi, dword ptr [ebp + 0x000000b4]\n\t"
        "%{disp8%} je         LAB__addr_0x00406e84\n\t"
        "push               ebx\n\t"
        "push               0x1\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @Read__8LHOSFileFPvUlPUl@20\n\t"
        "cmp                eax, 0x03\n\t"
        "%{disp8%} jne        LAB__addr_0x00406e71\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x226994], ebx\n"
        "LAB__addr_0x00406e71:\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x00000214]\n\t"
        "xor.s              edx, edx\n\t"
        "mov                dl, byte ptr [edi]\n\t"
        "inc                edx\n\t"
        "add.s              eax, edx\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000214], eax\n"
        "LAB__addr_0x00406e84:\n\t"
        "cmp                dword ptr [data_bytes + 0x226994], ebx\n\t"
        "%{disp32%} lea       edi, dword ptr [ebp + 0x000000b6]\n\t"
        "%{disp8%} je         LAB__addr_0x00406ebb\n\t"
        "push               ebx\n\t"
        "push               0x1\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @Read__8LHOSFileFPvUlPUl@20\n\t"
        "cmp                eax, 0x03\n\t"
        "%{disp8%} jne        LAB__addr_0x00406ea8\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x226994], ebx\n"
        "LAB__addr_0x00406ea8:\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x00000214]\n\t"
        "xor.s              eax, eax\n\t"
        "mov                al, byte ptr [edi]\n\t"
        "inc                eax\n\t"
        "add.s              ecx, eax\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000214], ecx\n"
        "LAB__addr_0x00406ebb:\n\t"
        "cmp                dword ptr [data_bytes + 0x226994], ebx\n\t"
        "%{disp32%} lea       edi, dword ptr [ebp + 0x000000b7]\n\t"
        "%{disp8%} je         LAB__addr_0x00406ef2\n\t"
        "push               ebx\n\t"
        "push               0x1\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @Read__8LHOSFileFPvUlPUl@20\n\t"
        "cmp                eax, 0x03\n\t"
        "%{disp8%} jne        LAB__addr_0x00406edf\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x226994], ebx\n"
        "LAB__addr_0x00406edf:\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x00000214]\n\t"
        "xor.s              ecx, ecx\n\t"
        "mov                cl, byte ptr [edi]\n\t"
        "inc                ecx\n\t"
        "add.s              eax, ecx\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000214], eax\n"
        "LAB__addr_0x00406ef2:\n\t"
        "cmp                dword ptr [data_bytes + 0x226994], ebx\n\t"
        "%{disp32%} lea       edi, dword ptr [ebp + 0x000000b8]\n\t"
        "%{disp32%} je        LAB__addr_0x00406fa4\n\t"
        "push               ebx\n\t"
        "push               0x1\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @Read__8LHOSFileFPvUlPUl@20\n\t"
        "cmp                eax, 0x03\n\t"
        "%{disp8%} jne        LAB__addr_0x00406f1a\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x226994], ebx\n"
        "LAB__addr_0x00406f1a:\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x00000214]\n\t"
        "xor.s              edx, edx\n\t"
        "mov                dl, byte ptr [edi]\n\t"
        "inc                edx\n\t"
        "add.s              ecx, edx\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000214], ecx\n\t"
        "cmp                dword ptr [data_bytes + 0x226994], ebx\n\t"
        "%{disp8%} je         LAB__addr_0x00406fa4\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x1c]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               _ReadIt_u32___10GameOSFileFRUl\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x1c]\n\t"
        "xor.s              edi, edi\n\t"
        "cmp.s              eax, ebx\n\t"
        "%{disp8%} jbe        LAB__addr_0x00406f67\n\t"
        "%{disp32%} lea       ebx, dword ptr [ebp + 0x000000bc]\n"
        "LAB__addr_0x00406f51:\n\t"
        "push               ebx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               _ReadIt_u32___10GameOSFileFRUl\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x1c]\n\t"
        "inc                edi\n\t"
        "add                ebx, 0x04\n\t"
        "cmp.s              edi, eax\n\t"
        ".byte              0x72, 0xec\n\t"
        "xor.s              ebx, ebx\n"
        "LAB__addr_0x00406f67:\n\t"
        "cmp                dword ptr [data_bytes + 0x226994], ebx\n\t"
        "%{disp8%} je         LAB__addr_0x00406fa4\n\t"
        "push               ebx\n\t"
        "push               0x4\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x1c]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @Read__8LHOSFileFPvUlPUl@20\n\t"
        "cmp                eax, 0x03\n\t"
        "%{disp8%} jne        LAB__addr_0x00406f89\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x226994], ebx\n"
        "LAB__addr_0x00406f89:\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x14]\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x00000214]\n\t"
        "and                edx, 0x000000ff\n\t"
        "add                edx, 0x04\n\t"
        "add.s              eax, edx\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000214], eax\n"
        "LAB__addr_0x00406fa4:\n\t"
        "cmp                dword ptr [esp + 0x14], ebx\n\t"
        "%{disp8%} je         LAB__addr_0x00407006\n\t"
        "push               0x000008a2\n\t"
        "push               0x009c7fbc\n\t"
        "push               0x28\n\t"
        "call               ___nw__FUl\n\t"
        "mov.s              edi, eax\n\t"
        "add                esp, 0x0c\n\t"
        "cmp.s              edi, ebx\n\t"
        "%{disp8%} je         LAB__addr_0x00406ffe\n\t"
        "%{disp8%} mov        ecx, dword ptr [ebp + 0x28]\n\t"
        "mov                eax, dword ptr [ecx]\n\t"
        "call               dword ptr [eax + 0x2c]\n\t"
        "cmp.s              eax, ebx\n\t"
        "%{disp32%} mov       ecx, dword ptr [?g_current_pack@LH3DMesh@@2PAULH3DPack@@A]\n\t"
        "%{disp8%} jl         LAB__addr_0x00406fda\n\t"
        "cmp                eax, dword ptr [ecx]\n\t"
        "%{disp8%} jl         LAB__addr_0x00406fdc\n"
        "LAB__addr_0x00406fda:\n\t"
        "xor.s              eax, eax\n"
        "LAB__addr_0x00406fdc:\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + eax * 0x4 + 0x04]\n\t"
        "push               eax\n\t"
        "push               esi\n\t"
        "mov.s              ecx, edi\n\t"
        "call               @__ct__8FragMeshFR10GameOSFileP8LH3DMesh@16\n\t"
        "pop                edi\n\t"
        "pop                ebx\n\t"
        "%{disp32%} mov       dword ptr [ebp + 0x00000090], eax\n\t"
        "pop                esi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebp\n\t"
        "add                esp, 0x08\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x00406ffe:\n\t"
        "xor.s              eax, eax\n\t"
        "%{disp32%} mov       dword ptr [ebp + 0x00000090], eax\n"
        "LAB__addr_0x00407006:\n\t"
        "pop                edi\n\t"
        "pop                ebx\n\t"
        "pop                esi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebp\n\t"
        "add                esp, 0x08\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x00407015:\n\t"
        "pop                esi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                ebp\n\t"
        "add                esp, 0x08"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV, no_callee_saves, ret_cleanup_override(0x0004)))
void __fastcall FindNearestDrinkingWater__5AbodeFf(struct Abode* this, const void* edx, float max_dist)
{
    asm volatile (
        "%{disp8%} mov        eax, dword ptr [esp + 0x04]\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "push               eax\n\t"
        "%{disp32%} lea       ecx, dword ptr [esi + 0x00000080]\n\t"
        "push               ecx\n\t"
        "%{disp8%} lea        edx, dword ptr [esi + 0x14]\n\t"
        "push               edx\n\t"
        "call               ?FindNearestDrinkingWater@GUtils@@SAIAAUMapCoords@@0M@Z\n\t"
        "%{disp8%} mov        cl, byte ptr [esi + 0x7c]\n\t"
        "mov.s              dl, cl\n\t"
        "xor.s              dl, al\n\t"
        "and                dl, 0x01\n\t"
        "xor.s              dl, cl\n\t"
        "add                esp, 0x0c\n\t"
        "%{disp8%} mov        byte ptr [esi + 0x7c], dl\n\t"
        "pop                esi"
        ::: "eax", "ecx", "edx", "memory"
    );
}

__attribute__((no_callee_saves))
float __fastcall GetPercentAbodeFullWithAdults__5AbodeFv(struct MultiMapFixed* this)
{
    float result;
    asm volatile (
        "sub esp, 0x08\n\t"
        "push esi\n\t"
        "%{disp8%} mov esi, dword ptr [ecx + 0x28]\n\t"
        "%{disp32%} mov eax, dword ptr [esi + 0x00000174]\n\t"
        "test eax, eax\n\t"
        "%{disp8%} je 0f\n\t"
        "call ?GetNumAdultsInAbode@Abode@@QAEEXZ\n\t"
        "%{disp32%} mov eax, dword ptr [esi + 0x00000174]\n\t"
        "%{disp8%} mov dword ptr [esp + 0x04], eax\n\t"
        "%{disp8%} mov dword ptr [esp + 0x08], 0x00000000\n\t"
        "%{disp8%} fidiv dword ptr [esp + 0x04]\n\t"
        "pop esi\n\t"
        "add esp, 0x08\n\t"
        "ret\n"
        "0:\n\t"
        "%{disp32%} fld dword ptr [_rdata_float1p0]\n\t"
        "pop esi\n\t"
        "add esp, 0x08"
        : "=t"(result) :: "eax", "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV, no_callee_saves))
float __fastcall GetPercentAbodeFullWithChildren__5AbodeFv(struct MultiMapFixed* this)
{
    float result;
    asm volatile (
        "%{disp8%} mov        eax, dword ptr [ecx + 0x28]\n\t"
        "sub                esp, 0x08\n\t"
        "push               esi\n\t"
        "%{disp32%} mov       esi, dword ptr [eax + 0x00000178]\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x004070c2\n\t"
        "xor.s              eax, eax\n\t"
        "%{disp32%} mov       al, byte ptr [ecx + 0x000000b7]\n\t"
        "xor.s              edx, edx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], 0x00000000\n\t"
        "div                esi\n\t"
        "pop                esi\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x00], eax\n\t"
        "%{disp8%} fild       qword ptr [esp + 0x00]\n\t"
        "add                esp, 0x08\n\t"
        "ret\n"
        "LAB__addr_0x004070c2:\n\t"
        "%{disp32%} fld       dword ptr [_rdata_float1p0]\n\t"
        "pop                esi\n\t"
        "add                esp, 0x08"
        : "=t"(result) :: "eax", "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV, no_callee_saves))
uint8_t __fastcall GetNumAdultsInAbode__5AbodeFv(struct Abode* this)
{
    uint8_t result;
    asm volatile (
        "push               ecx\n\t"
        "xor.s              eax, eax\n\t"
        "%{disp32%} mov       al, byte ptr [ecx + 0x000000b4]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x00], eax\n\t"
        "%{disp8%} fild       dword ptr [esp + 0x00]\n\t"
        "pop                ecx"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, ret_cleanup_override(0x0004)))
void __fastcall DrawPercentFull__5AbodeFi(struct Abode* this, const void* edx, int param_1)
{
    asm volatile (
        "sub                esp, 0x0c\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x40]\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x38]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x04], eax\n\t"
        "%{disp8%} mov        edx, dword ptr [ecx + 0x3c]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], edx\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x40]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], eax\n\t"
        "mov                edx, dword ptr [ecx]\n\t"
        "push               edi\n\t"
        "call               dword ptr [edx + 0xf8]\n\t"
        "%{disp8%} fld        dword ptr [eax + 0x28]\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x28]\n\t"
        "fadd.s             st(0), st(0)\n\t"
        "mov.s              ecx, esi\n\t"
        "%{disp8%} fadd       dword ptr [esp + 0x0c]\n\t"
        "%{disp32%} fadd      dword ptr [__real@3fc00000]\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x0c]\n\t"
        "%{disp32%} mov       edi, dword ptr [eax + 0x00000174]\n\t"
        "call               ?GetNumAdultsInAbode@Abode@@QAEEXZ\n\t"
        "call               _jmp_addr_0x007a1400\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x18]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x0040714f\n\t"
        "mov                edi, 0x00000001\n\t"
        "or                 eax, -0x1\n"
        "LAB__addr_0x0040714f:\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x08]\n\t"
        "push               ecx\n\t"
        "push               eax\n\t"
        "push               edi\n\t"
        "call               _jmp_addr_0x00829780\n\t"
        "add                esp, 0x0c\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "add                esp, 0x0c"
        ::: "eax", "ecx", "edx", "memory"
    );
}

__attribute__((no_callee_saves, ret_cleanup_override(0x0008)))
uint32_t __fastcall GetDiscipleStateIfInteractedWith__5AbodeFP16GInterfaceStatusP8Villager(struct Object* this, const void* edx, struct GInterfaceStatus* status, struct Villager* villager)
{
    uint32_t result;
    asm volatile (
        "push               ebx\n\t"
        "push               ebp\n\t"
        "%{disp8%} mov        ebp, dword ptr [esp + 0x10]\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "%{disp8%} mov        edi, dword ptr [esp + 0x14]\n\t"
        "push               ebp\n\t"
        "mov.s              esi, ecx\n\t"
        "push               edi\n\t"
        "call               ?GetDiscipleStateIfInteractedWith@MultiMapFixed@@UAEIPAVGInterfaceStatus@@PAVVillager@@@Z\n\t"
        "mov.s              ebx, eax\n\t"
        "test               ebx, ebx\n\t"
        "%{disp8%} jne        LAB__addr_0x004071f0\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0xd4]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x004071f0\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "mov.s              edi, eax\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x1c]\n\t"
        "cmp.s              eax, edi\n\t"
        "%{disp8%} jne        LAB__addr_0x004071f0\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x89c]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float1p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x004071f0\n\t"
        "mov.s              ecx, ebp\n\t"
        "call               ?GetAbode@Villager@@QAEPAVAbode@@XZ\n\t"
        "cmp.s              eax, esi\n\t"
        "%{disp8%} je         LAB__addr_0x004071f0\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x004071f0\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x000005f4]\n\t"
        "test               ecx, ecx\n\t"
        "mov                eax, 0x0000000a\n\t"
        "%{disp8%} je         LAB__addr_0x004071f2\n"
        "LAB__addr_0x004071f0:\n\t"
        "mov.s              eax, ebx\n"
        "LAB__addr_0x004071f2:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "pop                ebx"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV, no_callee_saves))
bool32_t __fastcall IsInteractable__5AbodeFv(struct GameThingWithPos* this)
{
    bool32_t result;
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "call               dword ptr [eax + 0x880]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float0p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x40\n\t"
        "%{disp8%} je         LAB__addr_0x0040721c\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x0040721c:\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?IsInteractable@GameThingWithPos@@UAE_NXZ\n\t"
        "pop                esi"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, ret_cleanup_override(0x000c)))
struct MapCoords* __fastcall FUN_00407230__5AbodeFb(struct Abode* this, const void* edx, struct MapCoords* coords, bool param_2)
{
    struct MapCoords* result;
    asm volatile (
        "cmp                dword ptr [esp + 0x08], 0x01\n\t"
        "push               esi\n\t"
        "%{disp8%} jne        LAB__addr_0x0040725a\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x74]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0040725a\n\t"
        "%{disp8%} mov        esi, dword ptr [esp + 0x08]\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "push               0x0\n\t"
        "push               0x0\n\t"
        "push               0x1\n\t"
        "push               esi\n\t"
        "mov.s              ecx, eax\n\t"
        "call               dword ptr [edx + 0x114]\n\t"
        "mov.s              eax, esi\n\t"
        "pop                esi\n\t"
        "ret                0x000c\n"
        "LAB__addr_0x0040725a:\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x08]\n\t"
        "add                ecx, 0x14\n\t"
        "mov                esi, dword ptr [ecx]\n\t"
        "mov.s              edx, eax\n\t"
        "mov                dword ptr [edx], esi\n\t"
        "%{disp8%} mov        esi, dword ptr [ecx + 0x04]\n\t"
        "%{disp8%} mov        dword ptr [edx + 0x04], esi\n\t"
        "%{disp8%} mov        ecx, dword ptr [ecx + 0x08]\n\t"
        "%{disp8%} mov        dword ptr [edx + 0x08], ecx\n\t"
        "pop                esi"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

bool __fastcall CanBeHiddenIn__5AbodeFv(struct Abode* this)
{
    typedef bool (__fastcall *fn_t)(struct Abode*);
    fn_t fn = ((fn_t*)(*(void**)this))[0xd4 / 4];
    __attribute__((musttail)) return fn(this);
}

__attribute__((no_callee_saves, trailing_asm("call               dword ptr [__imp__bind@4]")))
float __fastcall GetPercentRepairedForNonFunctional__5AbodeFv(struct MultiMapFixed* this)
{
    return ((const struct GAbodeInfo*)this->base.super_object.info)->thresholdForStopBeingFunctional;
}

__attribute__((XOR32rr_REV, no_callee_saves))
float __fastcall GetInfluence__5AbodeFv(struct MultiMapFixed* this)
{
    float result;
    asm volatile (
        "sub                esp, 0x08\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "call               ?GetInfluence@MultiMapFixed@@UAEMXZ\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x08]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetNumAdultsInAbode@Abode@@QAEEXZ\n\t"
        "xor.s              eax, eax\n\t"
        "%{disp32%} mov       al, byte ptr [esi + 0x000000b7]\n\t"
        "pop                esi\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x00], eax\n\t"
        "%{disp8%} fiadd      dword ptr [esp + 0x00]\n\t"
        "%{disp32%} fadd      dword ptr [_rdata_float1p0]\n\t"
        "%{disp8%} fmul       dword ptr [esp + 0x04]\n\t"
        "add                esp, 0x08"
        : "=t"(result) :: "eax", "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV, no_callee_saves, trailing_asm("call               dword ptr [rdata_bytes + 0x3dc]"), ret_cleanup_override(0x0010)))
struct MapCoords* __fastcall GetPosOutside__5AbodeFfff(struct Abode* this, const void* edx, struct MapCoords* coords, float param_2, float param_3, float param_4)
{
    struct MapCoords* result;
    asm volatile (
        "sub                esp, 0x1c\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x14]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x104]\n\t"
        "xor.s              ecx, ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], ecx\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], edx\n\t"
        "%{disp8%} mov        ecx, dword ptr [eax + 0x04]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], ecx\n\t"
        "%{disp8%} fld        dword ptr [eax + 0x08]\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x10]\n\t"
        "%{disp32%} fld       dword ptr [__real@40c90fdb]\n\t"
        "push               0x0000094a\n\t"
        "%{disp8%} fdiv       dword ptr [esp + 0x2c]\n\t"
        "push               0x009c7fbc\n\t"
        "push               ecx\n\t"
        "fstp               dword ptr [esp]\n\t"
        "call               ?GameFloatRand@GRand@@SAMM@Z\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x34]\n\t"
        "fadd.s             st(0), st(0)\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x14]\n\t"
        "push               edx\n\t"
        "add                esi, 0x14\n\t"
        "%{disp32%} fdivr     dword ptr [__real@40c90fdb]\n\t"
        "push               esi\n\t"
        "fsubp              st(1), st\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x3c]\n\t"
        "call               ?Get3DAngleFromXZ@GUtils@@SAMABUMapCoords@@0@Z\n\t"
        "%{disp8%} fadd       dword ptr [esp + 0x3c]\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x44]\n\t"
        "push               0x0000094b\n\t"
        "push               0x009c7fbc\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x20]\n\t"
        "push               eax\n\t"
        "call               ?GameFloatRand@GRand@@SAMM@Z\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x24]\n\t"
        "%{disp8%} fadd       dword ptr [esp + 0x4c]\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x34]\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x48]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x48]\n\t"
        "push               ecx\n\t"
        "push               edx\n\t"
        "push               eax\n\t"
        "call               ?GetPosFromAngle@GUtils@@SAPAUMapCoords@@MM@Z\n\t"
        "add                esp, 0x2c\n\t"
        "push               eax\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x0c]\n\t"
        "call               @__apl__9MapCoordsFRC9MapCoords@12\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x24]\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x08]\n\t"
        "mov.s              ecx, eax\n\t"
        "mov                dword ptr [ecx], edx\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x0c]\n\t"
        "%{disp8%} mov        dword ptr [ecx + 0x04], edx\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x10]\n\t"
        "%{disp8%} mov        dword ptr [ecx + 0x08], edx\n\t"
        "pop                esi\n\t"
        "add                esp, 0x1c"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, ret_cleanup_override(0x0004)))
void __fastcall StopBeingFunctional__5AbodeFP7GPlayer(struct Abode* this, const void* edx, struct GPlayer* param_1)
{
    asm volatile (
        "%{disp8%} mov        edx, dword ptr [esp + 0x04]\n\t"
        "test               edx, edx\n\t"
        "%{disp8%} je         LAB__addr_0x004073ec\n\t"
        "cmp                byte ptr [ecx + 0x000000b9], -0x38\n\t"
        ".byte              0x72, 0x1b\n\t"
        "%{disp32%} mov       eax, dword ptr [edx + 0x00000a44]\n\t"
        "push               esi\n\t"
        "%{disp32%} mov       esi, dword ptr [eax + 0x00001080]\n\t"
        "inc                esi\n\t"
        "push               edx\n\t"
        "%{disp32%} mov       dword ptr [eax + 0x00001080], esi\n\t"
        "call               ?FUN_004073f0@Abode@@UAEXPAVGPlayer@@@Z\n\t"
        "pop                esi\n"
        "LAB__addr_0x004073ec:"
        ::: "eax", "ecx", "edx", "memory"
    );
}

__attribute__((no_callee_saves, ret_cleanup_override(0x0004)))
void __fastcall FUN_004073f0__5AbodeFP7GPlayer(struct Abode* this, const void* edx, struct GPlayer* param_1)
{
    asm volatile (
        "%{disp8%} mov        al, byte ptr [ecx + 0x7c]\n\t"
        "test               al, 0x40\n\t"
        "%{disp8%} jne        LAB__addr_0x00407416\n\t"
        "test               al, 0x20\n\t"
        "push               0x1\n\t"
        "%{disp8%} jne        LAB__addr_0x0040740b\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x08]\n\t"
        "push               0x9\n\t"
        "call               _jmp_addr_0x0064da80\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x0040740b:\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x08]\n\t"
        "push               0xa\n\t"
        "call               _jmp_addr_0x0064da80\n"
        "LAB__addr_0x00407416:"
        ::: "eax", "ecx", "edx", "memory"
    );
}

__attribute__((no_callee_saves, ret_cleanup_override(0x0008)))
void __fastcall DiscipleInHandNear__5AbodeFR8VillagerR16GInterfaceStatus(struct Object* this, const void* edx, struct Villager* param_1, struct GInterfaceStatus* status)
{
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x28]\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x00000174]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} jbe        LAB__addr_0x00407490\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x08]\n\t"
        "add                ecx, 0x14\n\t"
        "push               ecx\n\t"
        "%{disp8%} lea        ecx, dword ptr [esi + 0x14]\n\t"
        "call               _GetDistanceInMetres__6GUtilsFRC9MapCoordsRC9MapCoords_2\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x08]\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x64]\n\t"
        "%{disp8%} fcomp      dword ptr [esp + 0x08]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp8%} jne        LAB__addr_0x00407490\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "mov.s              esi, eax\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x00407490\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x000005f4]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x00407490\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x10]\n\t"
        "mov.s              edi, eax\n\t"
        "mov                eax, dword ptr [ecx]\n\t"
        "call               dword ptr [eax + 0x1c]\n\t"
        "cmp.s              edi, eax\n\t"
        "pop                edi\n\t"
        "%{disp8%} jne        LAB__addr_0x00407490\n\t"
        "%{disp32%} mov       dword ptr [_abode_town_00c4cc6c], esi\n\t"
        "call               _jmp_addr_0x00829690\n"
        "LAB__addr_0x00407490:\n\t"
        "pop                esi"
        ::: "eax", "ecx", "edx", "memory"
    );
}

__attribute__((XOR32rr_REV, no_callee_saves))
float __fastcall CalculateDesireToGainMale__5AbodeFv(struct Abode* this)
{
    float result;
    asm volatile (
        "sub                esp, 0x0c\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x28]\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x00000174]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x04], 0x00000000\n\t"
        "%{disp8%} je         LAB__addr_0x00407537\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00407537\n\t"
        "%{disp32%} mov       edx, dword ptr [eax + 0x00000664]\n\t"
        "%{disp32%} mov       eax, dword ptr [eax + 0x00000668]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], edx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], 0x00000000\n\t"
        "%{disp8%} fild       qword ptr [esp + 0x08]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], 0x00000000\n\t"
        "xor.s              ecx, ecx\n\t"
        "%{disp32%} fadd      dword ptr [_rdata_float0p001]\n\t"
        "%{disp32%} mov       cl, byte ptr [esi + 0x000000b5]\n\t"
        "%{disp8%} fild       qword ptr [esp + 0x08]\n\t"
        "xor.s              edx, edx\n\t"
        "%{disp32%} mov       dl, byte ptr [esi + 0x000000b4]\n\t"
        "%{disp32%} fadd      dword ptr [_rdata_float0p001]\n\t"
        "pop                esi\n\t"
        "fdivp              st(1), st\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x00], ecx\n\t"
        "sub.s              edx, ecx\n\t"
        "%{disp8%} fild       dword ptr [esp + 0x00]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x00], edx\n\t"
        "%{disp32%} fadd      dword ptr [_rdata_float0p001]\n\t"
        "%{disp8%} fild       dword ptr [esp + 0x00]\n\t"
        "%{disp32%} fadd      dword ptr [_rdata_float0p001]\n\t"
        "fdivp              st(1), st\n\t"
        "fsubp              st(1), st\n\t"
        "add                esp, 0x0c\n\t"
        "ret\n"
        "LAB__addr_0x00407537:\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x04]\n\t"
        "pop                esi\n\t"
        "add                esp, 0x0c"
        : "=t"(result) :: "eax", "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves))
float __fastcall CalculateDesireToGainVillager__5AbodeFv(struct Abode* this)
{
    float result;
    asm volatile (
        "sub                esp, 0x08\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x28]\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x00000174]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x04], 0x00000000\n\t"
        "%{disp8%} je         LAB__addr_0x004075a7\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x004075a7\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x00000618]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x04], ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], 0x00000000\n\t"
        "%{disp8%} fild       qword ptr [esp + 0x04]\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "%{disp32%} fadd      dword ptr [_rdata_float0p001]\n\t"
        "%{disp32%} fild      dword ptr [eax + 0x00000644]\n\t"
        "%{disp32%} fadd      dword ptr [_rdata_float0p001]\n\t"
        "fdivp              st(1), st\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x04]\n\t"
        "call               dword ptr [edx + 0x89c]\n\t"
        "%{disp8%} fsubr      dword ptr [esp + 0x04]\n\t"
        "pop                esi\n\t"
        "add                esp, 0x08\n\t"
        "ret\n"
        "LAB__addr_0x004075a7:\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x04]\n\t"
        "pop                esi\n\t"
        "add                esp, 0x08"
        : "=t"(result) :: "eax", "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV, no_callee_saves, ret_cleanup_override(0x0008)))
bool32_t __fastcall TakeVillagerFrom__5AbodeFR5Abodei(struct Abode* this, const void* edx, struct Abode* other, int param_2)
{
    bool32_t result;
    asm volatile (
        "%{disp8%} mov        eax, dword ptr [esp + 0x04]\n\t"
        "push               ebp\n\t"
        "push               esi\n\t"
        "%{disp32%} mov       esi, dword ptr [eax + 0x000000a0]\n\t"
        "test               esi, esi\n\t"
        "push               edi\n\t"
        "mov.s              ebp, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x004075f8\n\t"
        "%{disp8%} mov        edi, dword ptr [esp + 0x14]\n"
        "LAB__addr_0x004075c7:\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x004075d7\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x44c]\n\t"
        "%{disp8%} jmp        LAB__addr_0x004075e1\n"
        "LAB__addr_0x004075d7:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x450]\n"
        "LAB__addr_0x004075e1:\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x004075ee\n\t"
        "test               byte ptr [esi + 0x000000e0], 0x04\n\t"
        "%{disp8%} je         LAB__addr_0x00407600\n"
        "LAB__addr_0x004075ee:\n\t"
        "%{disp32%} mov       esi, dword ptr [esi + 0x000000e4]\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} jne        LAB__addr_0x004075c7\n"
        "LAB__addr_0x004075f8:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                ebp\n\t"
        "ret                0x0008\n"
        "LAB__addr_0x00407600:\n\t"
        "push               ebp\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?ForceMoveVillagerToAbode@Villager@@QAEXPAVAbode@@@Z\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebp"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV, no_callee_saves, ret_cleanup_override(0x0004)))
bool32_t __fastcall SwapMaleForFemaleFrom__5AbodeFR5Abode(struct Abode* this, const void* edx, struct Abode* other)
{
    bool32_t result;
    asm volatile (
        "%{disp8%} mov        eax, dword ptr [esp + 0x04]\n\t"
        "push               ebx\n\t"
        "push               ebp\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "%{disp32%} mov       edi, dword ptr [eax + 0x000000a0]\n\t"
        "test               edi, edi\n\t"
        "mov.s              ebp, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x00407656\n\t"
        "mov                bl, 0x04\n"
        "LAB__addr_0x00407636:\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x44c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0040764c\n\t"
        "test               byte ptr [edi + 0x000000e0], bl\n\t"
        "%{disp8%} je         LAB__addr_0x0040765f\n"
        "LAB__addr_0x0040764c:\n\t"
        "%{disp32%} mov       edi, dword ptr [edi + 0x000000e4]\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} jne        LAB__addr_0x00407636\n"
        "LAB__addr_0x00407656:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "xor.s              eax, eax\n\t"
        "pop                ebx\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x0040765f:\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x00407656\n\t"
        "%{disp32%} mov       esi, dword ptr [ebp + 0x000000a0]\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x00407656\n"
        "LAB__addr_0x0040766d:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x450]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00407683\n\t"
        "test               byte ptr [esi + 0x000000e0], bl\n\t"
        "%{disp8%} je         LAB__addr_0x00407696\n"
        "LAB__addr_0x00407683:\n\t"
        "%{disp32%} mov       esi, dword ptr [esi + 0x000000e4]\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} jne        LAB__addr_0x0040766d\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "xor.s              eax, eax\n\t"
        "pop                ebx\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x00407696:\n\t"
        "push               ebp\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?ForceMoveVillagerToAbode@Villager@@QAEXPAVAbode@@@Z\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x14]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?ForceMoveVillagerToAbode@Villager@@QAEXPAVAbode@@@Z\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebx"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV, no_callee_saves))
float __fastcall GetVillagerHealthTotal__5AbodeFv(struct Abode* this)
{
    float result;
    asm volatile (
        "push               ecx\n\t"
        "push               esi\n\t"
        "%{disp32%} mov       esi, dword ptr [ecx + 0x000000a0]\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x04], 0x00000000\n\t"
        "%{disp8%} je         LAB__addr_0x004076f0\n"
        "LAB__addr_0x004076d4:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x11c]\n\t"
        "%{disp8%} fadd       dword ptr [esp + 0x04]\n\t"
        "%{disp32%} mov       esi, dword ptr [esi + 0x000000e4]\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x04]\n\t"
        "%{disp8%} jne        LAB__addr_0x004076d4\n"
        "LAB__addr_0x004076f0:\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x04]\n\t"
        "pop                esi\n\t"
        "pop                ecx"
        : "=t"(result) :: "eax", "ecx", "edx", "memory"
    );
    return result;
}

