#include "Abode.h"
#include "AbodeInfo.h"

__attribute__((no_callee_saves))
void __fastcall DeleteAbodeSurroundingObjects__5AbodeFv(struct Abode* this)
{
    asm volatile (
        "sub                esp, 0x18\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "mov.s              edi, ecx\n\t"
        "%{disp8%} mov        eax, dword ptr [edi + 0x28]\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x000001c0]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x00403d90\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x08]\n\t"
        "push               ecx\n\t"
        "push               0x1\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?GetNewEp@Abode@@QAEIW4ABODE_EPP@@PAULHPoint@@@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00403d90\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x08]\n\t"
        "push               edx\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x18]\n\t"
        "call               @__ct__9MapCoordsFRC7LHPoint@12\n\t"
        "push               0x0\n\t"
        "push               0x23\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x1c]\n\t"
        "call               @FindType__9MapCoordsCF11OBJECT_TYPEP6Object@16\n\t"
        "mov.s              esi, eax\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x00403d90\n"
        "LAB__addr_0x00403d67:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x48c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00403d7e\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               0x0\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0xc]\n"
        "LAB__addr_0x00403d7e:\n\t"
        "push               esi\n\t"
        "push               0x23\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x1c]\n\t"
        "call               @FindType__9MapCoordsCF11OBJECT_TYPEP6Object@16\n\t"
        "mov.s              esi, eax\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} jne        LAB__addr_0x00403d67\n"
        "LAB__addr_0x00403d90:\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x08]\n\t"
        "push               eax\n\t"
        "push               0x0\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?GetNewEp@Abode@@QAEIW4ABODE_EPP@@PAULHPoint@@@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00403dec\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x08]\n\t"
        "push               ecx\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x18]\n\t"
        "call               @__ct__9MapCoordsFRC7LHPoint@12\n\t"
        "push               0x0\n\t"
        "push               0x1c\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x1c]\n\t"
        "call               @FindType__9MapCoordsCF11OBJECT_TYPEP6Object@16\n\t"
        "mov.s              esi, eax\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x00403dec\n"
        "LAB__addr_0x00403dc3:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x204]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00403dda\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x0\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0xc]\n"
        "LAB__addr_0x00403dda:\n\t"
        "push               esi\n\t"
        "push               0x1c\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x1c]\n\t"
        "call               @FindType__9MapCoordsCF11OBJECT_TYPEP6Object@16\n\t"
        "mov.s              esi, eax\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} jne        LAB__addr_0x00403dc3\n"
        "LAB__addr_0x00403dec:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "add                esp, 0x18"
        ::: "eax", "ecx", "edx", "memory"
    );
}

__attribute__((no_callee_saves))
void __fastcall CreateAbodeSurroundingObjects__5AbodeFv(struct Abode* this)
{
    asm volatile (
        "sub                esp, 0x18\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "mov.s              edi, ecx\n\t"
        "%{disp8%} mov        eax, dword ptr [edi + 0x28]\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x000001c0]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x00403e79\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x14]\n\t"
        "push               ecx\n\t"
        "push               0x1\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?GetNewEp@Abode@@QAEIW4ABODE_EPP@@PAULHPoint@@@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00403e79\n\t"
        "push               0x3f800000\n\t"
        "push               0x0\n\t"
        "push               0x0\n\t"
        "push               0x00d964a0\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x24]\n\t"
        "push               edx\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x1c]\n\t"
        "call               @__ct__9MapCoordsFRC7LHPoint@12\n\t"
        "push               eax\n\t"
        "call               _jmp_addr_0x00709a40\n\t"
        "mov.s              esi, eax\n\t"
        "add                esp, 0x14\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x00403e79\n\t"
        "%{disp8%} mov        eax, dword ptr [edi + 0x28]\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x000001c4]\n\t"
        "%{disp32%} mov       edx, dword ptr [eax + 0x000001c0]\n\t"
        "push               ecx\n\t"
        "push               edx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               _jmp_addr_0x00709a20\n\t"
        "push               0x0\n\t"
        "mov.s              ecx, esi\n\t"
        "%{disp8%} mov        dword ptr [esi + 0x1c], 0x00000000\n\t"
        "call               _jmp_addr_0x00709c40\n"
        "LAB__addr_0x00403e79:\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x14]\n\t"
        "push               eax\n\t"
        "push               0x0\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?GetNewEp@Abode@@QAEIW4ABODE_EPP@@PAULHPoint@@@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00403ed9\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x14]\n\t"
        "push               ecx\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x0c]\n\t"
        "call               @__ct__9MapCoordsFRC7LHPoint@12\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x08]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x0c]\n\t"
        "push               0x42200000\n\t"
        "sub                esp, 0x0c\n\t"
        "mov.s              edx, esp\n\t"
        "mov                dword ptr [edx], eax\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x20]\n\t"
        "%{disp8%} mov        dword ptr [edx + 0x04], ecx\n\t"
        "%{disp8%} mov        dword ptr [edx + 0x08], eax\n\t"
        "call               _jmp_addr_0x00734a30\n\t"
        "add                esp, 0x10\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x00403ed9\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x08]\n\t"
        "push               0x00d3af0c\n\t"
        "push               ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], eax\n\t"
        "call               _jmp_addr_0x007346e0\n\t"
        "add                esp, 0x08\n"
        "LAB__addr_0x00403ed9:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "add                esp, 0x18"
        ::: "eax", "ecx", "edx", "memory"
    );
}

void __fastcall InsertMapObject__5AbodeFv(struct Object* this)
{
    InsertMapObject__13MultiMapFixedFv(this);
}

__attribute__((XOR32rr_REV, no_callee_saves))
bool32_t __fastcall ShouldFootpathsGoRound__5AbodeFv(struct Object* this)
{
    bool32_t result;
    asm volatile (
        "%{disp8%} mov al, byte ptr [ecx + 0x58]\n\t"
        "and al, 0x02\n\t"
        "xor.s ecx, ecx\n\t"
        "cmp al, 0x02\n\t"
        "setne cl\n\t"
        "mov.s eax, ecx"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

void __fastcall DeleteDependancys__5AbodeFv(struct Abode* this)
{
    extern void __fastcall __opaque_RemoveAllVillagersFromAbode(struct Abode*) asm("__thunk_target_DeleteDependancys");
    __attribute__((musttail)) return __opaque_RemoveAllVillagersFromAbode(this);
}

__attribute__((no_callee_saves, trailing_asm("nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\nLAB__addr_0x00403f20:\n{disp32} mov eax, dword ptr [ecx + 0x00000090]\ntest eax, eax\n{disp8} jne LAB__addr_0x00403f31\n{disp32} fld dword ptr [_rdata_float1p0]\nret\nLAB__addr_0x00403f31:\n{disp8} fld dword ptr [eax + 0x18]\nret")))
uint16_t __fastcall GetNumberOfInstanceForGlobalList__5AbodeFv(struct GameThing* this)
{
    return 1;
}

__attribute__((no_callee_saves, trailing_asm("call               dword ptr [__imp__DirectXSetupGetVersion]")))
void __fastcall RemoveDamage__5AbodeFv(struct MultiMapFixed* this)
{
    asm("push               ecx");                                           // 0x00403f40    51
    asm("push               esi");                                           // 0x00403f41    56
    asm("push               edi");                                           // 0x00403f42    57
    asm("mov.s              edi, ecx");                                      // 0x00403f43    8bf9
    asm("call               LAB__addr_0x00403f20");                          // 0x00403f45    e8d6ffffff
    asm("{disp8} fstp       dword ptr [esp + 0x08]");                        // 0x00403f4a    d95c2408
    asm("{disp32} mov       esi, dword ptr [edi + 0x00000090]");             // 0x00403f4e    8bb790000000
    asm("test               esi, esi");                                      // 0x00403f54    85f6
    asm("{disp8} je         LAB__addr_0x00403f72");                          // 0x00403f56    741a
    asm("mov.s              ecx, esi");                                      // 0x00403f58    8bce
    asm("call               ??1FragMesh@@QAE@XZ");                           // 0x00403f5a    e881313f00
    asm("push               esi");                                           // 0x00403f5f    56
    asm("call                ??3@YAXPAX@Z");                                   // 0x00403f60    e833af3a00
    asm("add                esp, 0x04");                                     // 0x00403f65    83c404
    asm("{disp32} mov       dword ptr [edi + 0x00000090], 0x00000000");      // 0x00403f68    c7879000000000000000
    asm("LAB__addr_0x00403f72:");
    asm("{disp8} fld        dword ptr [esp + 0x08]");                        // 0x00403f72    d9442408
    asm("pop                edi");                                           // 0x00403f76    5f
    asm("pop                esi");                                           // 0x00403f77    5e
    asm("pop                ecx");                                           // 0x00403f78    59
}

__attribute__((XOR32rr_REV, no_callee_saves, ret_cleanup_override(0x0008)))
uint32_t __fastcall DestroyedByEffect__5AbodeFP7GPlayerf(struct Object* this, const void* edx, struct GPlayer* player, float param_2)
{
    uint32_t result;
    asm volatile (
        "push               ebx\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "push               edi\n\t"
        "push               esi\n\t"
        "call               _jmp_addr_0x005e6540\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "%{disp8%} mov        edi, dword ptr [esi + 0x74]\n\t"
        "add                esp, 0x04\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x448]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00404001\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} jne        LAB__addr_0x00403fc3\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x00403fb4\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebx\n\t"
        "ret                0x0008\n"
        "LAB__addr_0x00403fb4:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               esi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x0073b8e0\n"
        "LAB__addr_0x00403fc3:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x890]\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x00403fe1\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x3f800000\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x5b0]\n"
        "LAB__addr_0x00403fe1:\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x44]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x0040404a\n\t"
        "mov                edx, dword ptr [ecx]\n\t"
        "push               0x0\n\t"
        "call               dword ptr [edx + 0xc]\n\t"
        "pop                edi\n\t"
        "%{disp8%} mov        dword ptr [esi + 0x44], 0x00000000\n\t"
        "pop                esi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebx\n\t"
        "ret                0x0008\n"
        "LAB__addr_0x00404001:\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x00404036\n\t"
        "%{disp8%} mov        eax, dword ptr [edi + 0x24]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jbe        LAB__addr_0x00404036\n\t"
        "%{disp8%} mov        edi, dword ptr [edi + 0x20]\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x00404018\n\t"
        "%{disp8%} mov        edi, dword ptr [edi + 0x04]\n\t"
        "%{disp8%} jmp        LAB__addr_0x0040401a\n"
        "LAB__addr_0x00404018:\n\t"
        "xor.s              edi, edi\n"
        "LAB__addr_0x0040401a:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x1c]\n\t"
        "test               edi, edi\n\t"
        "mov.s              ebx, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00404041\n\t"
        "mov.s              ecx, edi\n\t"
        "call               _jmp_addr_0x006e9610\n\t"
        "push               ebx\n\t"
        "mov.s              ecx, edi\n\t"
        "call               _jmp_addr_0x006e8860\n"
        "LAB__addr_0x00404036:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x2c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0040404a\n"
        "LAB__addr_0x00404041:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               0x0\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0xc]\n"
        "LAB__addr_0x0040404a:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebx"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV, no_callee_saves, ret_cleanup_override(0x0004)))
void __fastcall AddVillagerToAbode__5AbodeFP8Villager(struct Abode* this, const void* edx, struct Villager* villager)
{
    asm volatile (
        "push               ebx\n\t"
        "push               ebp\n\t"
        "push               esi\n\t"
        "%{disp8%} mov        esi, dword ptr [esp + 0x10]\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "mov.s              edi, ecx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "mov.s              ebx, eax\n\t"
        "xor.s              ebp, ebp\n\t"
        "cmp.s              ebx, ebp\n\t"
        "%{disp8%} je         LAB__addr_0x004040de\n\t"
        "push               esi\n\t"
        "mov.s              ecx, ebx\n\t"
        "call               ?IsVillagerInHomelessList@Town@@QAEIPAVVillager@@@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x004040de\n\t"
        "%{disp32%} mov       eax, dword ptr [ebx + 0x00000768]\n\t"
        "cmp.s              eax, esi\n\t"
        "%{disp8%} jne        LAB__addr_0x004040ad\n\t"
        "%{disp32%} mov       eax, dword ptr [ebx + 0x0000076c]\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x000000e4]\n\t"
        "dec                eax\n\t"
        "%{disp32%} mov       dword ptr [ebx + 0x00000768], ecx\n\t"
        "%{disp32%} mov       dword ptr [ebx + 0x0000076c], eax\n\t"
        "%{disp32%} jmp       LAB__addr_0x00404154\n"
        "LAB__addr_0x004040ad:\n\t"
        "cmp.s              eax, ebp\n\t"
        "%{disp32%} je        LAB__addr_0x0040415a\n"
        "LAB__addr_0x004040b5:\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x000000e4]\n\t"
        "cmp.s              ecx, esi\n\t"
        "%{disp8%} je         LAB__addr_0x004040ca\n\t"
        "mov.s              eax, ecx\n\t"
        "cmp.s              eax, ebp\n\t"
        "%{disp8%} jne        LAB__addr_0x004040b5\n\t"
        "%{disp32%} jmp       LAB__addr_0x0040415a\n"
        "LAB__addr_0x004040ca:\n\t"
        "%{disp32%} mov       edx, dword ptr [esi + 0x000000e4]\n\t"
        "%{disp32%} mov       dword ptr [eax + 0x000000e4], edx\n\t"
        "dec                dword ptr [ebx + 0x0000076c]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00404154\n"
        "LAB__addr_0x004040de:\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetAbode@Villager@@QAEPAVAbode@@XZ\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x004040fa\n\t"
        "push               esi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetAbode@Villager@@QAEPAVAbode@@XZ\n\t"
        "mov.s              ecx, eax\n\t"
        "call               ?RemoveAliveVillagerFromAbode@Abode@@QAEXPAVVillager@@@Z\n\t"
        "%{disp8%} jmp        LAB__addr_0x0040415a\n"
        "LAB__addr_0x004040fa:\n\t"
        "%{disp32%} mov       eax, dword ptr [_game]\n\t"
        "%{disp32%} lea       edx, dword ptr [eax + 0x00205bfc]\n\t"
        "mov                eax, dword ptr [edx]\n\t"
        "cmp.s              eax, ebp\n\t"
        "%{disp8%} je         LAB__addr_0x0040415a\n"
        "LAB__addr_0x0040410b:\n\t"
        "cmp.s              eax, esi\n\t"
        "%{disp8%} je         LAB__addr_0x0040411b\n\t"
        "%{disp32%} mov       eax, dword ptr [eax + 0x000000e4]\n\t"
        "cmp.s              eax, ebp\n\t"
        "%{disp8%} jne        LAB__addr_0x0040410b\n\t"
        "%{disp8%} jmp        LAB__addr_0x0040415a\n"
        "LAB__addr_0x0040411b:\n\t"
        "cmp.s              eax, ebp\n\t"
        "%{disp8%} je         LAB__addr_0x0040415a\n\t"
        "mov                eax, dword ptr [edx]\n\t"
        "cmp.s              eax, esi\n\t"
        "%{disp8%} jne        LAB__addr_0x0040412f\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x000000e4]\n\t"
        "mov                dword ptr [edx], ecx\n\t"
        "%{disp8%} jmp        LAB__addr_0x00404151\n"
        "LAB__addr_0x0040412f:\n\t"
        "cmp.s              eax, ebp\n\t"
        "%{disp8%} je         LAB__addr_0x0040415a\n"
        "LAB__addr_0x00404133:\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x000000e4]\n\t"
        "cmp.s              ecx, esi\n\t"
        "%{disp8%} je         LAB__addr_0x00404145\n\t"
        "mov.s              eax, ecx\n\t"
        "cmp.s              eax, ebp\n\t"
        "%{disp8%} jne        LAB__addr_0x00404133\n\t"
        "%{disp8%} jmp        LAB__addr_0x0040415a\n"
        "LAB__addr_0x00404145:\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x000000e4]\n\t"
        "%{disp32%} mov       dword ptr [eax + 0x000000e4], ecx\n"
        "LAB__addr_0x00404151:\n\t"
        "dec                dword ptr [edx + 0x04]\n"
        "LAB__addr_0x00404154:\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x000000e4], ebp\n"
        "LAB__addr_0x0040415a:\n\t"
        "%{disp32%} mov       edx, dword ptr [edi + 0x000000a0]\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x000000e4], edx\n\t"
        "%{disp32%} mov       eax, dword ptr [edi + 0x000000a4]\n\t"
        "inc                eax\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "%{disp32%} mov       dword ptr [edi + 0x000000a0], esi\n\t"
        "%{disp32%} mov       dword ptr [edi + 0x000000a4], eax\n\t"
        "call               ?SetAbode@Villager@@QAEXPAVAbode@@@Z\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x004041bb\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "cmp.s              ebx, eax\n\t"
        "%{disp8%} je         LAB__addr_0x004041a6\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "push               esi\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               ?AddVillagerToTown@Town@@QAEIPAVVillager@@@Z\n"
        "LAB__addr_0x004041a6:\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "push               esi\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "mov.s              ecx, eax\n\t"
        "add                ecx, 0x00000610\n\t"
        "call               _jmp_addr_0x00749500\n"
        "LAB__addr_0x004041bb:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0xaf8]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x00404210\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x28]\n\t"
        "%{disp32%} mov       edx, dword ptr [ecx + 0x000001f8]\n\t"
        "%{disp32%} mov       ecx, dword ptr [edi + edx * 0x4 + 0x000000a8]\n\t"
        "cmp.s              ecx, ebp\n\t"
        "%{disp32%} lea       eax, dword ptr [edi + edx * 0x4 + 0x000000a8]\n\t"
        "%{disp8%} jne        LAB__addr_0x004041e6\n\t"
        "mov                dword ptr [eax], esi\n"
        "LAB__addr_0x004041e6:\n\t"
        "%{disp32%} inc       byte ptr [edi + 0x000000b4]\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x44c]\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} mov       al, byte ptr [edi + 0x000000b5]\n\t"
        "setne              cl\n\t"
        "add.s              al, cl\n\t"
        "%{disp32%} mov       byte ptr [edi + 0x000000b5], al\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "pop                ebx\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x00404210:\n\t"
        "%{disp32%} inc       byte ptr [edi + 0x000000b7]\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "pop                ebx"
        ::: "eax", "ecx", "edx", "memory"
    );
}

__attribute__((XOR32rr_REV, no_callee_saves, ret_cleanup_override(0x0004)))
void __fastcall RemoveDeletedVillagerFromAbode__5AbodeFP8Villager(struct Abode* this, const void* edx, struct Villager* villager)
{
    asm volatile (
        "push               ebx\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "%{disp8%} mov        edi, dword ptr [esp + 0x10]\n\t"
        "%{disp8%} mov        eax, dword ptr [edi + 0x28]\n\t"
        "%{disp32%} mov       eax, dword ptr [eax + 0x000001f8]\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + eax * 0x4 + 0x000000a8]\n\t"
        "xor.s              ebx, ebx\n\t"
        "cmp.s              ecx, edi\n\t"
        "%{disp8%} jne        LAB__addr_0x00404254\n\t"
        "xor.s              ecx, ecx\n\t"
        "cmp.s              eax, ebx\n\t"
        "sete               cl\n\t"
        "%{disp32%} mov       dword ptr [esi + ecx * 0x4 + 0x000000a8], ebx\n\t"
        "%{disp32%} mov       dword ptr [esi + eax * 0x4 + 0x000000a8], ebx\n"
        "LAB__addr_0x00404254:\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0xaf8]\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x0040429c\n\t"
        "%{disp32%} mov       al, byte ptr [esi + 0x000000b4]\n\t"
        "cmp.s              al, bl\n\t"
        "%{disp8%} jbe        LAB__addr_0x00404275\n\t"
        "dec                al\n\t"
        "%{disp32%} mov       byte ptr [esi + 0x000000b4], al\n"
        "LAB__addr_0x00404275:\n\t"
        "cmp                byte ptr [esi + 0x000000b5], bl\n\t"
        "%{disp8%} jbe        LAB__addr_0x004042ae\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x44c]\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} mov       al, byte ptr [esi + 0x000000b5]\n\t"
        "setne              cl\n\t"
        "sub.s              al, cl\n\t"
        "%{disp32%} mov       byte ptr [esi + 0x000000b5], al\n\t"
        "%{disp8%} jmp        LAB__addr_0x004042ae\n"
        "LAB__addr_0x0040429c:\n\t"
        "%{disp32%} mov       al, byte ptr [esi + 0x000000b7]\n\t"
        "cmp.s              al, bl\n\t"
        "%{disp8%} je         LAB__addr_0x004042ae\n\t"
        "dec                al\n\t"
        "%{disp32%} mov       byte ptr [esi + 0x000000b7], al\n"
        "LAB__addr_0x004042ae:\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x000000a0]\n\t"
        "cmp.s              eax, edi\n\t"
        "%{disp8%} jne        LAB__addr_0x004042c6\n\t"
        "%{disp32%} mov       edx, dword ptr [edi + 0x000000e4]\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x000000a0], edx\n\t"
        "%{disp8%} jmp        LAB__addr_0x004042e8\n"
        "LAB__addr_0x004042c6:\n\t"
        "cmp.s              eax, ebx\n\t"
        "%{disp8%} je         LAB__addr_0x004042f4\n"
        "LAB__addr_0x004042ca:\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x000000e4]\n\t"
        "cmp.s              ecx, edi\n\t"
        "%{disp8%} je         LAB__addr_0x004042dc\n\t"
        "mov.s              eax, ecx\n\t"
        "cmp.s              eax, ebx\n\t"
        "%{disp8%} jne        LAB__addr_0x004042ca\n\t"
        "%{disp8%} jmp        LAB__addr_0x004042f4\n"
        "LAB__addr_0x004042dc:\n\t"
        "%{disp32%} mov       ecx, dword ptr [edi + 0x000000e4]\n\t"
        "%{disp32%} mov       dword ptr [eax + 0x000000e4], ecx\n"
        "LAB__addr_0x004042e8:\n\t"
        "dec                dword ptr [esi + 0x000000a4]\n\t"
        "%{disp32%} mov       dword ptr [edi + 0x000000e4], ebx\n"
        "LAB__addr_0x004042f4:\n\t"
        "push               ebx\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?SetAbode@Villager@@QAEXPAVAbode@@@Z\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0040432b\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               ?RemoveVillager@Town@@QAEXPAVVillager@@@Z\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "mov.s              ecx, eax\n\t"
        "add                ecx, 0x00000610\n\t"
        "call               ?VillagerMoveOutOfAbode@TownStats@@QAEXPAVVillager@@@Z\n"
        "LAB__addr_0x0040432b:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebx"
        ::: "eax", "ecx", "edx", "memory"
    );
}

__attribute__((no_callee_saves, ret_cleanup_override(0x0004)))
void __fastcall RemoveAliveVillagerFromAbode__5AbodeFP8Villager(struct Abode* this, const void* edx, struct Villager* villager)
{
    asm volatile (
        "push               esi\n\t"
        "push               edi\n\t"
        "%{disp8%} mov        edi, dword ptr [esp + 0x0c]\n\t"
        "test               byte ptr [edi + 0x000000e0], 0x04\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x00404360\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "push               0x000000a3\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x8e8]\n"
        "LAB__addr_0x00404360:\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0xaf8]\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x004043aa\n\t"
        "%{disp32%} mov       al, byte ptr [esi + 0x000000b4]\n\t"
        "test               al, al\n\t"
        "%{disp8%} jbe        LAB__addr_0x00404381\n\t"
        "dec                al\n\t"
        "%{disp32%} mov       byte ptr [esi + 0x000000b4], al\n"
        "LAB__addr_0x00404381:\n\t"
        "%{disp32%} mov       al, byte ptr [esi + 0x000000b5]\n\t"
        "test               al, al\n\t"
        "%{disp8%} jbe        LAB__addr_0x004043bc\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x44c]\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} mov       al, byte ptr [esi + 0x000000b5]\n\t"
        "setne              cl\n\t"
        "sub.s              al, cl\n\t"
        "%{disp32%} mov       byte ptr [esi + 0x000000b5], al\n\t"
        "%{disp8%} jmp        LAB__addr_0x004043bc\n"
        "LAB__addr_0x004043aa:\n\t"
        "%{disp32%} mov       al, byte ptr [esi + 0x000000b7]\n\t"
        "test               al, al\n\t"
        "%{disp8%} je         LAB__addr_0x004043bc\n\t"
        "dec                al\n\t"
        "%{disp32%} mov       byte ptr [esi + 0x000000b7], al\n"
        "LAB__addr_0x004043bc:\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x000000a0]\n\t"
        "cmp.s              eax, edi\n\t"
        "%{disp8%} jne        LAB__addr_0x004043d4\n\t"
        "%{disp32%} mov       edx, dword ptr [edi + 0x000000e4]\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x000000a0], edx\n\t"
        "%{disp8%} jmp        LAB__addr_0x004043f6\n"
        "LAB__addr_0x004043d4:\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00404406\n"
        "LAB__addr_0x004043d8:\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x000000e4]\n\t"
        "cmp.s              ecx, edi\n\t"
        "%{disp8%} je         LAB__addr_0x004043ea\n\t"
        "mov.s              eax, ecx\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x004043d8\n\t"
        "%{disp8%} jmp        LAB__addr_0x00404406\n"
        "LAB__addr_0x004043ea:\n\t"
        "%{disp32%} mov       ecx, dword ptr [edi + 0x000000e4]\n\t"
        "%{disp32%} mov       dword ptr [eax + 0x000000e4], ecx\n"
        "LAB__addr_0x004043f6:\n\t"
        "dec                dword ptr [esi + 0x000000a4]\n\t"
        "%{disp32%} mov       dword ptr [edi + 0x000000e4], 0x00000000\n"
        "LAB__addr_0x00404406:\n\t"
        "push               0x0\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?SetAbode@Villager@@QAEXPAVAbode@@@Z\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0040442f\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "mov.s              ecx, eax\n\t"
        "add                ecx, 0x00000610\n\t"
        "call               ?VillagerMoveOutOfAbode@TownStats@@QAEXPAVVillager@@@Z\n"
        "LAB__addr_0x0040442f:\n\t"
        "pop                edi\n\t"
        "pop                esi"
        ::: "eax", "ecx", "edx", "memory"
    );
}

uint32_t __fastcall Process__5AbodeFv(struct Object* this)
{
    void* dummy;
    uint32_t result;
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "call               ?Process@MultiMapFixed@@UAEIXZ\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x89c]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float0p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x40\n\t"
        "%{disp32%} je        LAB__addr_0x00404503\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x8a0]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float0p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x40\n\t"
        "%{disp32%} je        LAB__addr_0x00404503\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x890]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00404503\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x448]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x00404503\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x004044b6\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x000005f4]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} jne        LAB__addr_0x00404503\n\t"
        "LAB__addr_0x004044b6:\n\t"
        "%{disp32%} fld       dword ptr [esi + 0x000000b0]\n\t"
        "%{disp32%} fadd      dword ptr [_rdata_float0p001]\n\t"
        "%{disp32%} fst       dword ptr [esi + 0x000000b0]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float1p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x00404503\n\t"
        "%{disp8%} mov        al, byte ptr [esi + 0x7c]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x28]\n\t"
        "or                 al, 0x40\n\t"
        "%{disp8%} mov        byte ptr [esi + 0x7c], al\n\t"
        "%{disp32%} mov       edx, dword ptr [ecx + 0x000001b0]\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x0\n\t"
        "push               edx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x5b8]\n\t"
        "fstp               st(0)\n\t"
        "and                byte ptr [esi + 0x7c], -0x41\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x000000b0], 0x00000000\n\t"
        "LAB__addr_0x00404503:\n\t"
        "%{disp32%} mov       al, byte ptr [esi + 0x000000b9]\n\t"
        "cmp                al, -0x38\n\t"
        "%{disp8%} jae        LAB__addr_0x00404515\n\t"
        "inc                al\n\t"
        "%{disp32%} mov       byte ptr [esi + 0x000000b9], al\n\t"
        "LAB__addr_0x00404515:\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi"
        : "=a"(result), "=c"(dummy) : "c"(this) : "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV, no_callee_saves))
void __fastcall MoveAbodeToPlannedAbodes__5AbodeFv(struct Abode* this)
{
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "mov.s              edi, eax\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x0040455a\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x8f8]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x00404552\n\t"
        "push               esi\n\t"
        "call               ?Create@PlannedAbode@@SAPAV1@PAVAbode@@@Z\n\t"
        "add                esp, 0x04\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00404552\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x00404552:\n\t"
        "push               esi\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?RemoveBuildingSite@Town@@QAEIPAVMultiMapFixed@@@Z\n"
        "LAB__addr_0x0040455a:\n\t"
        "pop                edi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi"
        ::: "eax", "ecx", "edx", "memory"
    );
}

__attribute__((noinline))
void __fastcall RemoveAllVillagersFromAbode__5AbodeFv(struct Abode* this)
{
    void* dummy;
    asm volatile (
        "%{disp32%} mov       ecx, dword ptr [ecx + 0x000000a0]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x0040457d\n\t"
        "push               esi\n\t"
        "LAB__addr_0x0040456b:\n\t"
        "%{disp32%} mov       esi, dword ptr [ecx + 0x000000e4]\n\t"
        "call               ?HomeDeleted@Villager@@QAEXXZ\n\t"
        "test               esi, esi\n\t"
        "mov.s              ecx, esi\n\t"
        "%{disp8%} jne        LAB__addr_0x0040456b\n\t"
        "pop                esi\n\t"
        "LAB__addr_0x0040457d:"
        : "=c"(dummy) : "c"(this) : "eax", "edx", "memory"
    );
}

__attribute__((XOR32rr_REV, no_callee_saves, ret_cleanup_override(0x0004)))
int __fastcall NumVillagersOfSex__5AbodeFv(struct Abode* this)
{
    int result;
    asm volatile (
        "push               esi\n\t"
        "%{disp32%} mov       esi, dword ptr [ecx + 0x000000a0]\n\t"
        "push               edi\n\t"
        "xor.s              edi, edi\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x004045bc\n\t"
        "push               ebx\n\t"
        "%{disp8%} mov        ebx, dword ptr [esp + 0x10]\n"
        "LAB__addr_0x00404593:\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?IsVillagerAvailable@Villager@@QAE_NXZ\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x004045aa\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x28]\n\t"
        "cmp                dword ptr [eax + 0x000001f8], ebx\n\t"
        "%{disp8%} jne        LAB__addr_0x004045aa\n\t"
        "inc                edi\n"
        "LAB__addr_0x004045aa:\n\t"
        "%{disp32%} mov       esi, dword ptr [esi + 0x000000e4]\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} jne        LAB__addr_0x00404593\n\t"
        "pop                ebx\n\t"
        "mov.s              eax, edi\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x004045bc:\n\t"
        "mov.s              eax, edi\n\t"
        "pop                edi\n\t"
        "pop                esi"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV))
int __fastcall CalculateFoodNeededForDinner__5AbodeFv(struct Abode* this)
{
    void* dummy;
    int result;
    asm volatile (
        "%{disp32%} mov       ecx, dword ptr [ecx + 0x000000a0]\n\t"
        "xor.s              eax, eax\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x004045f3\n\t"
        "push               esi\n\t"
        "LAB__addr_0x004045dd:\n\t"
        "%{disp8%} mov        edx, dword ptr [ecx + 0x28]\n\t"
        "%{disp32%} mov       esi, dword ptr [edx + 0x000002d8]\n\t"
        "%{disp32%} mov       ecx, dword ptr [ecx + 0x000000e4]\n\t"
        "add.s              eax, esi\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} jne        LAB__addr_0x004045dd\n\t"
        "pop                esi\n\t"
        "LAB__addr_0x004045f3:"
        : "=a"(result), "=c"(dummy) : "c"(this) : "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves))
bool32_t __fastcall IsEnoughFoodForDinner__5AbodeFv(struct Abode* this)
{
    bool32_t result;
    asm volatile (
        "push esi\n\t"
        "push edi\n\t"
        "mov.s esi, ecx\n\t"
        "mov eax, dword ptr [esi]\n\t"
        "push 0x0\n\t"
        "call dword ptr [eax + 0x98]\n\t"
        "mov.s ecx, esi\n\t"
        "mov.s edi, eax\n\t"
        "call ?CalculateFoodNeededForDinner@Abode@@QAEHXZ\n\t"
        "and eax, 0x0000ffff\n\t"
        "cmp.s edi, eax\n\t"
        ".byte 0x1b, 0xc0\n\t"
        "pop edi\n\t"
        "inc eax\n\t"
        "pop esi"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV, no_callee_saves, ret_cleanup_override(0x0004)))
struct Villager* __fastcall GetSpouse__5AbodeFP8Villager(struct Abode* this, const void* edx, struct Villager* villager)
{
    struct Villager* result;
    asm volatile (
        "%{disp8%} mov        edx, dword ptr [esp + 0x04]\n\t"
        "%{disp8%} mov        eax, dword ptr [edx + 0x28]\n\t"
        "%{disp32%} mov       eax, dword ptr [eax + 0x000001f8]\n\t"
        "cmp                dword ptr [ecx + eax * 0x4 + 0x000000a8], edx\n\t"
        "%{disp8%} jne        LAB__addr_0x00404657\n\t"
        "xor.s              edx, edx\n\t"
        "test               eax, eax\n\t"
        "sete               dl\n\t"
        "%{disp32%} mov       eax, dword ptr [ecx + edx * 0x4 + 0x000000a8]\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x00404657:\n\t"
        "xor.s              eax, eax"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV, expand_movzx, msvc6_regalloc))
int __fastcall GetRoomLeftForAdults__5AbodeFv(struct Abode* this)
{
    int max_adults = ((const struct GAbodeInfo*)this->base.super_object.info)->maxVillagersInAbode;
    int num_adults = this->adult_count;
    return max_adults - num_adults;
}

__attribute__((XOR32rr_REV, expand_movzx, msvc6_regalloc))
int __fastcall GetRoomLeftForChildren__5AbodeFv(struct Abode* this)
{
    int max_children = ((const struct GAbodeInfo*)this->base.super_object.info)->maxChildrenInAbode;
    int num_children = this->field_0xb7;
    return max_children - num_children;
}

void __fastcall FUN_004046a0__5AbodeFi(struct Abode* this, const void* edx, int param_1)
{
    return;
}

__attribute__((no_callee_saves, trailing_asm("call               dword ptr [__imp__SetWindowTextA@4]")))
int __fastcall FUN_004046b0__5AbodeFv(struct Abode* this)
{
    int result = ((const struct GMultiMapFixedInfo*)this->base.super_object.info)->maxVillagerNeededToBuild;
    return result;
}

__attribute__((XOR32rr_REV, no_callee_saves))
bool32_t __fastcall IsTooCrowded__5AbodeFv(struct Abode* this)
{
    bool32_t result;
    asm volatile (
        "%{disp8%} mov        eax, dword ptr [ecx + 0x28]\n\t"
        "sub                esp, 0x08\n\t"
        "push               esi\n\t"
        "%{disp32%} mov       esi, dword ptr [eax + 0x00000174]\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} jne        LAB__addr_0x004046db\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x08\n\t"
        "ret\n"
        "LAB__addr_0x004046db:\n\t"
        "xor.s              edx, edx\n\t"
        "%{disp32%} mov       dl, byte ptr [ecx + 0x000000b4]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], 0x00000000\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x04], edx\n\t"
        "%{disp8%} fild       dword ptr [esp + 0x04]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x04], esi\n\t"
        "%{disp8%} fidiv      dword ptr [esp + 0x04]\n\t"
        "%{disp32%} fcomp     dword ptr [eax + 0x000001a0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x00404712\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x08\n\t"
        "ret\n"
        "LAB__addr_0x00404712:\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi\n\t"
        "add                esp, 0x08"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves))
bool32_t __fastcall Built__5AbodeFv(struct MultiMapFixed* this)
{
    bool32_t result;
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "call               ?Built@MultiMapFixed@@UAE_NXZ\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0040478a\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0040478a\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x00000a44]\n\t"
        "push               esi\n\t"
        "call               _jmp_addr_0x0056a3f0\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x490]\n\t"
        "test               eax, eax\n\t"
        "push               0x1\n\t"
        "%{disp8%} je         LAB__addr_0x0040477a\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               0x4\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00404783\n"
        "LAB__addr_0x0040477a:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x3\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x1c]\n"
        "LAB__addr_0x00404783:\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x0064da80\n"
        "LAB__addr_0x0040478a:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0040479f\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x914]\n"
        "LAB__addr_0x0040479f:\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves))
bool32_t __fastcall Repaired__5AbodeFv(struct MultiMapFixed* this)
{
    bool32_t result;
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "call               ?Repaired@MultiMapFixed@@UAE_NXZ\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x004047cd\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x914]\n"
        "LAB__addr_0x004047cd:\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV, no_callee_saves))
void __fastcall MakeFunctional__5AbodeFv(struct Abode* this)
{
    asm volatile (
        "sub                esp, 0x18\n\t"
        "push               ebx\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "mov.s              ebx, eax\n\t"
        "test               ebx, ebx\n\t"
        "%{disp32%} je        LAB__addr_0x00404955\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x88c]\n\t"
        "%{disp8%} mov        cl, byte ptr [esi + 0x58]\n\t"
        "test               eax, eax\n\t"
        "sete               al\n\t"
        "and                al, 0x01\n\t"
        "shl                al, 2\n\t"
        "and                cl, -0x05\n\t"
        "or.s               al, cl\n\t"
        "%{disp8%} mov        byte ptr [esi + 0x58], al\n\t"
        "%{disp8%} mov        al, byte ptr [esi + 0x7c]\n\t"
        "test               al, 0x02\n\t"
        "%{disp8%} jne        LAB__addr_0x00404829\n\t"
        "or                 al, 2\n\t"
        "push               esi\n\t"
        "mov.s              ecx, ebx\n\t"
        "%{disp8%} mov        byte ptr [esi + 0x7c], al\n\t"
        "call               ?AddAbodeToTownStats@Town@@QAEXPAVAbode@@@Z\n"
        "LAB__addr_0x00404829:\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetRoomLeftForAdults@Abode@@QAEHXZ\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0040483b\n\t"
        "mov.s              ecx, ebx\n\t"
        "call               ?AllVillagersCheckNeedNewAbode@Town@@QAEXXZ\n"
        "LAB__addr_0x0040483b:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x88c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0040485f\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x890]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0040485f\n\t"
        "push               esi\n\t"
        "mov.s              ecx, ebx\n\t"
        "call               ?RemoveBuildingSite@Town@@QAEIPAVMultiMapFixed@@@Z\n"
        "LAB__addr_0x0040485f:\n\t"
        "push               edi\n\t"
        "mov.s              ecx, ebx\n\t"
        "call               ?GetStoragePit@Town@@QAEPAVStoragePit@@XZ\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x0040494d\n\t"
        "mov.s              ecx, ebx\n\t"
        "call               ?GetStoragePit@Town@@QAEPAVStoragePit@@XZ\n\t"
        "cmp.s              eax, esi\n\t"
        "%{disp32%} je        LAB__addr_0x0040494d\n\t"
        "%{disp32%} mov       ecx, dword ptr [_game]\n\t"
        "%{disp32%} mov       eax, dword ptr [ecx + 0x00205a40]\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} jbe       LAB__addr_0x0040494d\n\t"
        "push               0x000003fb\n\t"
        "push               0x009c7fbc\n\t"
        "push               0x24\n\t"
        "call               ?__nw@Base@@SAPAXK@Z\n\t"
        "add                esp, 0x0c\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x004048b9\n\t"
        "push               0x0\n\t"
        "push               0x0\n\t"
        "mov.s              ecx, eax\n\t"
        "call               @__ct__9GFootpathFP16GameThingWithPosP16GameThingWithPos@16\n\t"
        "mov.s              edi, eax\n\t"
        "%{disp8%} jmp        LAB__addr_0x004048bb\n"
        "LAB__addr_0x004048b9:\n\t"
        "xor.s              edi, edi\n"
        "LAB__addr_0x004048bb:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x0c]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x104]\n\t"
        "mov.s              ecx, ebx\n\t"
        "call               ?GetStoragePit@Town@@QAEPAVStoragePit@@XZ\n\t"
        "mov.s              ebx, eax\n\t"
        "mov                edx, dword ptr [ebx]\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x18]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, ebx\n\t"
        "call               dword ptr [edx + 0x104]\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x0c]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, edi\n\t"
        "call               @AddPos__9GFootpathFRC9MapCoords@12\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x18]\n\t"
        "push               edx\n\t"
        "mov.s              ecx, edi\n\t"
        "call               @AddPos__9GFootpathFRC9MapCoords@12\n\t"
        "%{disp8%} mov        edx, dword ptr [edi + 0x14]\n\t"
        "mov.s              eax, edx\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00404910\n"
        "LAB__addr_0x00404903:\n\t"
        "%{disp8%} mov        ecx, dword ptr [eax + 0x24]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x00404910\n\t"
        "mov.s              eax, ecx\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x00404903\n"
        "LAB__addr_0x00404910:\n\t"
        "push               0x0\n\t"
        "push               eax\n\t"
        "push               edx\n\t"
        "call               ?AttemptRerenderFootpathWithCreatureRP@GFootpath@@SAIPAVGFootpathNode@@0ABUMapCoords@@@Z\n\t"
        "add                esp, 0x0c\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x00404937\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "push               0x0\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0xc]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               LAB__addr_0x00404960\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x18\n\t"
        "ret\n"
        "LAB__addr_0x00404937:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x84]\n\t"
        "mov                eax, dword ptr [ebx]\n\t"
        "push               edi\n\t"
        "mov.s              ecx, ebx\n\t"
        "call               dword ptr [eax + 0x84]\n"
        "LAB__addr_0x0040494d:\n\t"
        "mov.s              ecx, esi\n\t"
        "call               LAB__addr_0x00404960\n\t"
        "pop                edi\n"
        "LAB__addr_0x00404955:\n\t"
        "pop                esi\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x18\n\t"
        "ret\n\t"
        "call               ?GetVillagerActivityDesire@GameThing@@QAEMPAVVillager@@@Z + 9\n"
        "LAB__addr_0x00404960:\n\t"
        "sub                esp, 0x08\n\t"
        "push               ebx\n\t"
        "push               ebp\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "mov.s              edi, ecx\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "xor.s              ebp, ebp\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], ebp\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], ebp\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x00404a8d\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "cmp                dword ptr [eax + 0x000005fc], ebp\n\t"
        "%{disp32%} jne       LAB__addr_0x00404a8d\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "mov.s              ebx, eax\n\t"
        "%{disp32%} mov       esi, dword ptr [ebx + 0x00000754]\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x00404a24\n"
        "LAB__addr_0x004049a6:\n\t"
        "cmp.s              esi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x004049fa\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x880]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float1p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x004049fa\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x8c4]\n\t"
        "cmp                eax, 0x24\n\t"
        "%{disp8%} jne        LAB__addr_0x004049d6\n\t"
        "%{disp8%} inc        dword ptr [esp + 0x10]\n\t"
        "%{disp8%} jmp        LAB__addr_0x004049fa\n"
        "LAB__addr_0x004049d6:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x1e0]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x004049e7\n\t"
        "inc                ebp\n\t"
        "%{disp8%} jmp        LAB__addr_0x004049fa\n"
        "LAB__addr_0x004049e7:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x8c4]\n\t"
        "cmp                eax, 0x02\n\t"
        "%{disp8%} jne        LAB__addr_0x004049fa\n\t"
        "%{disp8%} inc        dword ptr [esp + 0x14]\n"
        "LAB__addr_0x004049fa:\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} jne        LAB__addr_0x00404a06\n\t"
        "%{disp32%} mov       esi, dword ptr [ebx + 0x00000754]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00404a0c\n"
        "LAB__addr_0x00404a06:\n\t"
        "%{disp32%} mov       esi, dword ptr [esi + 0x0000009c]\n"
        "LAB__addr_0x00404a0c:\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} jne        LAB__addr_0x004049a6\n\t"
        "test               ebp, ebp\n\t"
        "%{disp8%} je         LAB__addr_0x00404a24\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x10]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00404a24\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x14]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x00404a8d\n"
        "LAB__addr_0x00404a24:\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x8c4]\n\t"
        "cmp                eax, 0x24\n\t"
        "%{disp8%} jne        LAB__addr_0x00404a39\n\t"
        "%{disp8%} inc        dword ptr [esp + 0x10]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00404a5d\n"
        "LAB__addr_0x00404a39:\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x1e0]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00404a4a\n\t"
        "inc                ebp\n\t"
        "%{disp8%} jmp        LAB__addr_0x00404a5d\n"
        "LAB__addr_0x00404a4a:\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x8c4]\n\t"
        "cmp                eax, 0x02\n\t"
        "%{disp8%} jne        LAB__addr_0x00404a5d\n\t"
        "%{disp8%} inc        dword ptr [esp + 0x14]\n"
        "LAB__addr_0x00404a5d:\n\t"
        "test               ebp, ebp\n\t"
        "%{disp8%} je         LAB__addr_0x00404a8d\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x10]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00404a8d\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x14]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00404a8d\n\t"
        "push               0x1\n\t"
        "%{disp32%} mov       dword ptr [ebx + 0x000005fc], 0x00000001\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "push               0xc\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x1c]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x0064da80\n"
        "LAB__addr_0x00404a8d:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x08"
        ::: "eax", "ecx", "edx", "memory"
    );
}

__attribute__((XOR32rr_REV, no_callee_saves))
int __fastcall GetMesh__5AbodeCFv(const struct Object* this)
{
    int result;
    asm volatile (
        "%{disp8%} mov        ecx, dword ptr [ecx + 0x28]\n\t"
        "mov                eax, dword ptr [ecx]\n\t"
        "%{disp8%} jmp        dword ptr [eax + 0x2c]\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "sub                esp, 0x14\n\t"
        "xor.s              eax, eax\n\t"
        "xor.s              ecx, ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x00], ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x04], ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], ecx\n\t"
        "%{disp8%} mov        word ptr [esp + 0x10], cx\n\t"
        "mov                ecx, 0x00c3c7e8\n"
        "LAB__addr_0x00404ad1:\n\t"
        "mov                edx, dword ptr [ecx]\n\t"
        "%{disp8%} inc        word ptr [esp + edx * 0x2 + 0x00]\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + edx * 0x2 + 0x00]\n\t"
        "add                ecx, 0x000001c8\n\t"
        "%{disp32%} lea       edx, dword ptr [ecx + -0x00000158]\n\t"
        "cmp                edx, OFFSET _AbodeInfos + 0x93 * 0x1c8\n\t"
        ".byte              0x72, 0xe1\n\t"
        "push               esi\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x04]\n\t"
        "mov                esi, 0x00000009\n"
        "LAB__addr_0x00404afa:\n\t"
        "xor.s              ecx, ecx\n\t"
        "mov                cx, word ptr [edx]\n\t"
        "cmp.s              ecx, eax\n\t"
        "%{disp8%} jbe        LAB__addr_0x00404b05\n\t"
        "mov.s              eax, ecx\n"
        "LAB__addr_0x00404b05:\n\t"
        "add                edx, 0x02\n\t"
        "dec                esi\n\t"
        "%{disp8%} jne        LAB__addr_0x00404afa\n\t"
        "pop                esi\n\t"
        "add                esp, 0x14"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

