#include "Game.h"

__attribute__((no_callee_saves, ret_cleanup_override(0x00)))
void __stdcall KeyHandler__5GGameFUs6LH_KEYUsUsPv(struct GGame* this, unsigned short param_1, enum LH_KEY param_2, unsigned short param_3, unsigned short param_4, void* param_5)
{
    asm volatile (
        "%{disp8%} mov        ax, word ptr [esp + 0x04]\n\t"
        "cmp                ax, 0x0100\n\t"
        "push               esi\n\t"
        "%{disp8%} je         LAB__addr_0x0054ff92\n\t"
        "cmp                ax, 0x0104\n\t"
        "%{disp8%} jne        LAB__addr_0x0054ffd5\n"
        "LAB__addr_0x0054ff92:\n\t"
        "%{disp8%} mov        esi, dword ptr [esp + 0x0c]\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x0054ffd5\n\t"
        "%{disp32%} mov       al, byte ptr [data_bytes + 0x33b9c5]\n\t"
        "test               al, al\n\t"
        "%{disp8%} je         LAB__addr_0x0054ffab\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x33b9c8], esi\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x0054ffab:\n\t"
        "%{disp32%} mov       ecx, dword ptr [_game]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x0054ffd5\n\t"
        "mov                eax, dword ptr [ecx]\n\t"
        "call               dword ptr [eax + 0x2c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0054ffd5\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x10]\n\t"
        "%{disp32%} mov       edx, dword ptr [_game]\n\t"
        "push               ecx\n\t"
        "push               esi\n\t"
        "%{disp32%} lea       ecx, dword ptr [edx + 0x002502a8]\n\t"
        "call               _jmp_addr_0x005e1bf0\n"
        "LAB__addr_0x0054ffd5:\n\t"
        "pop                esi"
        ::: "eax", "ecx", "edx", "memory"
    );
}

__attribute__((XOR32rr_REV, no_callee_saves, ret_cleanup_override(0x00)))
bool32_t __stdcall MouseHandler__5GGameFPv19LH_MOUSE_EVENT_TYPEUlUl(struct GGame* this, void* param_1, enum LH_MOUSE_EVENT_TYPE param_2, unsigned long param_3, unsigned long param_4)
{
    bool32_t result;
    asm volatile (
        "%{disp8%} mov        eax, dword ptr [esp + 0x08]\n\t"
        "cmp                eax, 0x04\n\t"
        "%{disp8%} je         LAB__addr_0x00550007\n\t"
        "test               eax, 0x000003bd\n\t"
        "%{disp32%} jne       LAB__addr_0x0055007b\n\t"
        "test               al, 0x02\n\t"
        "%{disp8%} je         LAB__addr_0x00550001\n\t"
        "%{disp32%} mov       eax, dword ptr [data_bytes + 0x4bf270]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0055007b\n"
        "LAB__addr_0x00550001:\n\t"
        "mov                eax, 0x00000001\n\t"
        "ret\n"
        "LAB__addr_0x00550007:\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x10]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jle        LAB__addr_0x00550001\n\t"
        "%{disp32%} mov       edx, dword ptr [data_bytes + 0x33b9cc]\n\t"
        "%{disp32%} mov       ecx, dword ptr [_game]\n\t"
        "add.s              edx, eax\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x33b9cc], edx\n\t"
        "call               ?MyInterface@GGame@@QAEPAVGInterface@@XZ\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0055007b\n\t"
        "%{disp32%} mov       ecx, dword ptr [_game]\n\t"
        "push               0x0\n\t"
        "call               ?MyInterface@GGame@@QAEPAVGInterface@@XZ\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x005db710\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0055007b\n\t"
        "cmp                dword ptr [data_bytes + 0x33b9cc], 0x1c\n\t"
        "%{disp8%} jle        LAB__addr_0x0055007b\n\t"
        "%{disp32%} mov       ecx, dword ptr [_game]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x0055007b\n\t"
        "mov                eax, dword ptr [ecx]\n\t"
        "call               dword ptr [eax + 0x2c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0055007b\n\t"
        "%{disp32%} mov       ecx, dword ptr [_game]\n\t"
        "add                ecx, 0x002502b8\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x33b9cc], 0x00000000\n\t"
        "call               ?ProcessPosition@CMouse@@QAEXXZ\n"
        "LAB__addr_0x0055007b:\n\t"
        "xor.s              eax, eax"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV))
void __fastcall UnfinishInitialisation__5GGameFv(struct GGame* this)
{
    void* dummy;
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp32%} mov       ecx, dword ptr [_global]\n\t"
        "push               edi\n\t"
        "call               ?ReleaseAtmosSoundBanks@GAudio@@QAEXXZ\n\t"
        "call               ?Close@Windmill@@QAEXXZ\n\t"
        "xor.s              edi, edi\n\t"
        "mov.s              ecx, esi\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x4bf208], edi\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x4bf354], edi\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x4bf36c], edi\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x4bf370], edi\n\t"
        "call               ?MyInterface@GGame@@QAEPAVGInterface@@XZ\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00550109\n\t"
        "push               ebx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?MyInterface@GGame@@QAEPAVGInterface@@XZ\n\t"
        "mov.s              ebx, eax\n\t"
        "%{disp32%} mov       ecx, dword ptr [ebx + 0x00000438]\n\t"
        "add                ebx, 0x00000430\n\t"
        "cmp.s              ecx, edi\n\t"
        "%{disp8%} je         LAB__addr_0x00550105\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + -0x04]\n\t"
        "push               ebp\n\t"
        "%{disp8%} lea        ebp, dword ptr [ecx + -0x04]\n\t"
        "lea                edx, dword ptr [eax + eax * 0x2]\n\t"
        "dec                eax\n\t"
        "lea                edx, dword ptr [edx + edx * 0x4]\n\t"
        "lea                ecx, dword ptr [ecx + edx * 0x4]\n\t"
        "%{disp8%} js         LAB__addr_0x005500fb\n\t"
        "%{disp8%} lea        esi, dword ptr [ecx + 0x0c]\n\t"
        "%{disp8%} lea        edi, dword ptr [eax + 0x01]\n\t"
        "LAB__addr_0x005500ec:\n\t"
        "sub                esi, 0x3c\n\t"
        "mov.s              ecx, esi\n\t"
        "call               _jmp_addr_0x00436960\n\t"
        "dec                edi\n\t"
        "%{disp8%} jne        LAB__addr_0x005500ec\n\t"
        "xor.s              edi, edi\n\t"
        "LAB__addr_0x005500fb:\n\t"
        "push               ebp\n\t"
        "call               ??3@YAXPAX@Z\n\t"
        "add                esp, 0x04\n\t"
        "pop                ebp\n\t"
        "LAB__addr_0x00550105:\n\t"
        "%{disp8%} mov        dword ptr [ebx + 0x08], edi\n\t"
        "pop                ebx\n\t"
        "LAB__addr_0x00550109:\n\t"
        "pop                edi\n\t"
        "pop                esi"
        : "=c"(dummy) : "c"(this) : "eax", "edx", "memory"
    );
}

__attribute__((XOR32rr_REV))
void __fastcall FinishInitialisation__5GGameFv(struct GGame* this)
{
    void* dummy;
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "call               ?MyInterface@GGame@@QAEPAVGInterface@@XZ\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00550130\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?MyInterface@GGame@@QAEPAVGInterface@@XZ\n\t"
        "push               0x40\n\t"
        "%{disp32%} lea       ecx, dword ptr [eax + 0x00000430]\n\t"
        "call               ?Init@GInterfaceMessageBuffer@@QAEXG@Z\n\t"
        "LAB__addr_0x00550130:\n\t"
        "xor.s              eax, eax\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x4bf36c], 0x0054ff80\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x4bf370], eax\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x4bf208], 0x0054ffe0\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x4bf354], eax\n\t"
        "call               ?Open@Windmill@@QAEXXZ\n\t"
        "%{disp32%} mov       ecx, dword ptr [_global]\n\t"
        "call               ?InitAtmos@GAudio@@QAEXXZ\n\t"
        "pop                esi"
        : "=c"(dummy) : "c"(this) : "eax", "edx", "memory"
    );
}

extern void __cdecl CreatePack_LH3DMesh(void) asm("?CreatePack@LH3DMesh@@SAXXZ");

void __fastcall CreateMeshPack__5GGameFv(struct GGame* this)
{
    CreatePack_LH3DMesh();
}

__attribute__((no_callee_saves, XOR32rr_REV, trailing_asm("call               ?GetVillagerActivityDesire@GameThing@@QAEMPAVVillager@@@Z + 9")))
void __cdecl LoadAllAnimations__Fv(void)
{
    asm volatile (
        "sub                esp, 0x000000a0\n\t"
        "push               ebp\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "call               ?CreatePack@LH3DAnim@@SAXXZ\n\t"
        "%{disp32%} mov       eax, dword ptr [data_bytes + 0x517508]\n\t"
        "%{disp32%} mov       eax, dword ptr [eax + 0x00000510]\n\t"
        "and                dword ptr [eax + 0x50], 0xfffffeff\n\t"
        "xor.s              ebp, ebp\n\t"
        "xor.s              edx, edx\n\t"
        "mov                eax, 0x00000004\n"
        "LAB__addr_0x005501a9:\n\t"
        "%{disp32%} mov       ecx, dword ptr [data_bytes + 0x517508]\n\t"
        "cmp                edx, dword ptr [ecx]\n\t"
        "%{disp8%} jge        LAB__addr_0x005501bd\n\t"
        "cmp                eax, 0x04\n\t"
        "%{disp8%} jl         LAB__addr_0x005501bd\n\t"
        "mov                ecx, dword ptr [eax + ecx * 0x1]\n\t"
        "%{disp8%} jmp        LAB__addr_0x005501c0\n"
        "LAB__addr_0x005501bd:\n\t"
        "%{disp8%} mov        ecx, dword ptr [ecx + 0x04]\n"
        "LAB__addr_0x005501c0:\n\t"
        "add                eax, 0x04\n\t"
        "inc                edx\n\t"
        "cmp                eax, 0x000006e8\n\t"
        "%{disp8%} mov        dword ptr [ecx + 0x44], ebp\n\t"
        "%{disp8%} jl         LAB__addr_0x005501a9\n\t"
        "push               0x009d976c\n\t"
        "push               0x00bec860\n\t"
        "call               _fopen\n\t"
        "mov.s              edi, eax\n\t"
        "add                esp, 0x08\n\t"
        "cmp.s              edi, ebp\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], edi\n\t"
        "%{disp32%} je        LAB__addr_0x00550381\n\t"
        "push               ebx\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x20]\n\t"
        "push               ecx\n\t"
        "push               0x009cda78\n\t"
        "push               edi\n\t"
        "call               _fscanf\n\t"
        "add                esp, 0x0c\n"
        "LAB__addr_0x00550202:\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x30]\n\t"
        "push               edx\n\t"
        "push               0x009c8c40\n\t"
        "push               edi\n\t"
        "call               _fscanf\n\t"
        "add                esp, 0x0c\n\t"
        "mov                esi, 0x00bec85c\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x30]\n"
        "LAB__addr_0x0055021e:\n\t"
        "mov                dl, byte ptr [eax]\n\t"
        "mov                bl, byte ptr [esi]\n\t"
        "mov.s              cl, dl\n\t"
        "cmp.s              dl, bl\n\t"
        "%{disp8%} jne        LAB__addr_0x00550246\n\t"
        "test               cl, cl\n\t"
        "%{disp8%} je         LAB__addr_0x00550242\n\t"
        "%{disp8%} mov        dl, byte ptr [eax + 0x01]\n\t"
        "%{disp8%} mov        bl, byte ptr [esi + 0x01]\n\t"
        "mov.s              cl, dl\n\t"
        "cmp.s              dl, bl\n\t"
        "%{disp8%} jne        LAB__addr_0x00550246\n\t"
        "add                eax, 0x02\n\t"
        "add                esi, 0x02\n\t"
        "test               cl, cl\n\t"
        "%{disp8%} jne        LAB__addr_0x0055021e\n"
        "LAB__addr_0x00550242:\n\t"
        "xor.s              eax, eax\n\t"
        "%{disp8%} jmp        LAB__addr_0x0055024b\n"
        "LAB__addr_0x00550246:\n\t"
        "sbb.s              eax, eax\n\t"
        "sbb                eax, -0x01\n"
        "LAB__addr_0x0055024b:\n\t"
        "cmp.s              eax, ebp\n\t"
        "%{disp32%} je        LAB__addr_0x00550377\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x20]\n\t"
        "xor.s              ebx, ebx\n\t"
        "cmp.s              eax, ebp\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], ebp\n\t"
        "%{disp8%} jne        LAB__addr_0x00550267\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], ebp\n\t"
        "%{disp8%} jmp        LAB__addr_0x0055027a\n"
        "LAB__addr_0x00550267:\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x18]\n\t"
        "push               eax\n\t"
        "push               0x009cda78\n\t"
        "push               edi\n\t"
        "call               _fscanf\n\t"
        "add                esp, 0x0c\n"
        "LAB__addr_0x0055027a:\n\t"
        "%{disp32%} mov       eax, dword ptr [data_bytes + 0x517508]\n\t"
        "mov                ebp, 0x00000004\n"
        "LAB__addr_0x00550284:\n\t"
        "test               ebx, ebx\n\t"
        "%{disp8%} jne        LAB__addr_0x005502f6\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x14]\n\t"
        "cmp                ecx, dword ptr [eax]\n\t"
        "%{disp8%} jge        LAB__addr_0x0055029a\n\t"
        "cmp                ebp, 0x04\n\t"
        "%{disp8%} jl         LAB__addr_0x0055029a\n\t"
        "mov                edi, dword ptr [eax + ebp * 0x1]\n\t"
        "%{disp8%} jmp        LAB__addr_0x0055029d\n"
        "LAB__addr_0x0055029a:\n\t"
        "%{disp8%} mov        edi, dword ptr [eax + 0x04]\n"
        "LAB__addr_0x0055029d:\n\t"
        "mov.s              esi, edi\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x30]\n"
        "LAB__addr_0x005502a3:\n\t"
        "mov                dl, byte ptr [eax]\n\t"
        "mov.s              cl, dl\n\t"
        "cmp                dl, byte ptr [esi]\n\t"
        "%{disp8%} jne        LAB__addr_0x005502c7\n\t"
        "test               cl, cl\n\t"
        "%{disp8%} je         LAB__addr_0x005502c3\n\t"
        "%{disp8%} mov        dl, byte ptr [eax + 0x01]\n\t"
        "mov.s              cl, dl\n\t"
        "cmp                dl, byte ptr [esi + 0x01]\n\t"
        "%{disp8%} jne        LAB__addr_0x005502c7\n\t"
        "add                eax, 0x02\n\t"
        "add                esi, 0x02\n\t"
        "test               cl, cl\n\t"
        "%{disp8%} jne        LAB__addr_0x005502a3\n"
        "LAB__addr_0x005502c3:\n\t"
        "xor.s              eax, eax\n\t"
        "%{disp8%} jmp        LAB__addr_0x005502cc\n"
        "LAB__addr_0x005502c7:\n\t"
        "sbb.s              eax, eax\n\t"
        "sbb                eax, -0x01\n"
        "LAB__addr_0x005502cc:\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x005502d9\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x18]\n\t"
        "mov.s              ebx, edi\n\t"
        "%{disp8%} mov        dword ptr [edi + 0x44], eax\n"
        "LAB__addr_0x005502d9:\n\t"
        "%{disp8%} mov        esi, dword ptr [esp + 0x14]\n\t"
        "%{disp32%} mov       eax, dword ptr [data_bytes + 0x517508]\n\t"
        "%{disp8%} mov        edi, dword ptr [esp + 0x10]\n\t"
        "inc                esi\n\t"
        "add                ebp, 0x04\n\t"
        "cmp                ebp, 0x000006e8\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], esi\n\t"
        "%{disp8%} jl         LAB__addr_0x00550284\n"
        "LAB__addr_0x005502f6:\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x1c], 0x00000001\n"
        "LAB__addr_0x005502fe:\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x1c]\n\t"
        "push               ecx\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x30]\n\t"
        "push               edx\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x2c]\n\t"
        "push               eax\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x34]\n\t"
        "push               ecx\n\t"
        "push               0x00bec850\n\t"
        "push               edi\n\t"
        "call               _fscanf\n\t"
        "add                esp, 0x18\n\t"
        "test               ebx, ebx\n\t"
        "%{disp8%} je         LAB__addr_0x00550368\n\t"
        "push               0x00001311\n\t"
        "push               0x00bec32c\n\t"
        "push               0x14\n\t"
        "call               ___nw__FUl\n\t"
        "add                esp, 0x0c\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00550363\n\t"
        "%{disp8%} mov        edi, dword ptr [esp + 0x28]\n\t"
        "%{disp8%} mov        ecx, dword ptr [ebx + 0x48]\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x2c]\n\t"
        "%{disp8%} mov        esi, dword ptr [esp + 0x24]\n\t"
        "%{disp8%} mov        dword ptr [eax + 0x04], edi\n\t"
        "%{disp8%} mov        edi, dword ptr [esp + 0x10]\n\t"
        "mov                dword ptr [eax], 0x00000000\n\t"
        "%{disp8%} mov        dword ptr [eax + 0x08], esi\n\t"
        "%{disp8%} mov        dword ptr [eax + 0x0c], edx\n\t"
        "%{disp8%} mov        dword ptr [eax + 0x10], ecx\n\t"
        "%{disp8%} jmp        LAB__addr_0x00550365\n"
        "LAB__addr_0x00550363:\n\t"
        "xor.s              eax, eax\n"
        "LAB__addr_0x00550365:\n\t"
        "%{disp8%} mov        dword ptr [ebx + 0x48], eax\n"
        "LAB__addr_0x00550368:\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x1c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x005502fe\n\t"
        "xor.s              ebp, ebp\n\t"
        "%{disp32%} jmp       LAB__addr_0x00550202\n"
        "LAB__addr_0x00550377:\n\t"
        "push               edi\n\t"
        "call               _fclose\n\t"
        "add                esp, 0x04\n\t"
        "pop                ebx\n"
        "LAB__addr_0x00550381:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "add                esp, 0x000000a0"
        ::: "eax", "ecx", "edx", "memory"
    );
}

__attribute__((XOR32rr_REV, no_callee_saves))
bool32_t __fastcall LoadFiles__5GGameFv(struct GGame* this)
{
    bool32_t result;
    asm volatile (
        "push               esi\n\t"
        "push               0x00bec8c8\n\t"
        "mov.s              esi, ecx\n\t"
        "call               ?RenderLoadingFrame@@YAXPAD@Z\n\t"
        "call               ?LoadAllAnimations@@YAXXZ\n\t"
        "push               0x00bec8b8\n\t"
        "call               ?RenderLoadingFrame@@YAXPAD@Z\n\t"
        "add                esp, 0x08\n\t"
        "call               ?CreateMeshPack@GGame@@QAEXXZ\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x00250064]\n\t"
        "push               0x00bec8a4\n\t"
        "call               ?Load@GestureSystemDataList@@QAEIPAD@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x005503ca\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x005503ca:\n\t"
        "push               0x00bec88c\n\t"
        "call               ?RenderLoadingFrame@@YAXPAD@Z\n\t"
        "add                esp, 0x04\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?MyInterface@GGame@@QAEPAVGInterface@@XZ\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x005ceba0\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x005503ee\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x005503ee:\n\t"
        "push               0x00bec878\n\t"
        "call               ?RenderLoadingFrame@@YAXPAD@Z\n\t"
        "add                esp, 0x04\n\t"
        "%{disp32%} lea       ecx, dword ptr [esi + 0x00205a30]\n\t"
        "call               _jmp_addr_0x0050f960\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV))
void __fastcall SetupPlayers__5GGameFv(struct GGame* this)
{
    asm volatile (
        "sub                esp, 0x000000f0\n\t"
        "%{disp32%} mov       eax, dword ptr [rdata_bytes + 0x36610]\n\t"
        "%{disp32%} mov       edx, dword ptr [rdata_bytes + 0x36608]\n\t"
        "push               ebx\n\t"
        "push               esi\n\t"
        "push               eax\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp32%} mov       ecx, dword ptr [rdata_bytes + 0x3660c]\n\t"
        "push               ecx\n\t"
        "push               edx\n\t"
        "%{disp32%} lea       eax, dword ptr [esi + 0x0025000c]\n\t"
        "xor.s              ebx, ebx\n\t"
        "push               eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], ebx\n\t"
        "call               _jmp_addr_0x0053b4a0\n\t"
        "add                esp, 0x04\n\t"
        "push               eax\n\t"
        "%{disp32%} lea       ecx, dword ptr [esi + 0x00205b70]\n\t"
        "call               _jmp_addr_0x00634640\n\t"
        "cmp                eax, 0x03\n\t"
        "%{disp32%} je        LAB__addr_0x0055076b\n\t"
        "%{disp32%} mov       byte ptr [esi + 0x00205a5b], 0x07\n\t"
        "cmp                dword ptr [data_bytes + 0x351cac], 0x00001a6c\n\t"
        "%{disp8%} ja         LAB__addr_0x00550472\n\t"
        "%{disp32%} mov       eax, dword ptr [data_bytes + 0x351ca8]\n\t"
        "%{disp8%} jmp        LAB__addr_0x0055047e\n"
        "LAB__addr_0x00550472:\n\t"
        "%{disp32%} mov       ecx, dword ptr [data_bytes + 0x351ca8]\n\t"
        "%{disp32%} lea       eax, dword ptr [ecx + 0x00013d10]\n"
        "LAB__addr_0x0055047e:\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x08]\n\t"
        "push               ebp\n\t"
        "push               edi\n\t"
        "push               0x7\n\t"
        "push               edx\n\t"
        "push               0x7\n\t"
        "push               0x3\n\t"
        "%{disp32%} lea       ecx, dword ptr [esi + 0x000048b8]\n\t"
        "call               @Init__7GPlayerF11PLAYER_TYPEUcPwUc@18\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x10]\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x00205b80]\n\t"
        "push               ecx\n\t"
        "%{disp32%} lea       ecx, dword ptr [eax + 0x00000090]\n\t"
        "%{disp32%} mov       byte ptr [esi + 0x00205a5c], bl\n\t"
        "call               _jmp_addr_0x00555cc0\n\t"
        "cmp.s              eax, ebx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], eax\n\t"
        "%{disp32%} je        LAB__addr_0x0055056f\n\t"
        "mov                edi, 0x00000001\n"
        "LAB__addr_0x005504c2:\n\t"
        "%{disp32%} inc       byte ptr [esi + 0x00205a5c]\n\t"
        "%{disp32%} mov       ecx, dword ptr [_game]\n\t"
        "call               ?IsMultiplayerGame@GGame@@QBE_NXZ\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x005504f2\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x10]\n\t"
        "%{disp32%} mov       edx, dword ptr [eax + 0x00000174]\n\t"
        "inc                edx\n\t"
        "%{disp32%} mov       dword ptr [eax + 0x000001f8], edx\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x10]\n\t"
        "%{disp32%} mov       dword ptr [eax + 0x000001f4], edi\n"
        "LAB__addr_0x005504f2:\n\t"
        "%{disp32%} mov       edx, dword ptr [esi + 0x00205b80]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x10]\n\t"
        "%{disp32%} mov       edx, dword ptr [edx + 0x00000088]\n\t"
        "%{disp32%} mov       eax, dword ptr [ecx + 0x00000178]\n\t"
        "cmp                eax, dword ptr [edx]\n\t"
        "%{disp8%} jne        LAB__addr_0x0055054d\n\t"
        "%{disp32%} mov       eax, dword ptr [ecx + 0x00000174]\n\t"
        "%{disp32%} mov       ecx, dword ptr [_game]\n\t"
        "%{disp32%} mov       byte ptr [ecx + 0x00205a5a], al\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x10]\n\t"
        "cmp                dword ptr [eax + 0x000001f8], ebx\n\t"
        "%{disp8%} jne        LAB__addr_0x00550539\n\t"
        "%{disp32%} mov       edx, dword ptr [_game]\n\t"
        "%{disp32%} mov       byte ptr [edx + 0x00205a59], 0x06\n\t"
        "%{disp8%} jmp        LAB__addr_0x0055054d\n"
        "LAB__addr_0x00550539:\n\t"
        "%{disp32%} mov       al, byte ptr [eax + 0x000001f8]\n\t"
        "%{disp32%} mov       ecx, dword ptr [_game]\n\t"
        "dec                al\n\t"
        "%{disp32%} mov       byte ptr [ecx + 0x00205a59], al\n"
        "LAB__addr_0x0055054d:\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x00205b80]\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x10]\n\t"
        "push               edx\n\t"
        "%{disp32%} lea       ecx, dword ptr [eax + 0x00000090]\n\t"
        "call               _jmp_addr_0x00555cc0\n\t"
        "cmp.s              eax, ebx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], eax\n\t"
        "%{disp32%} jne       LAB__addr_0x005504c2\n"
        "LAB__addr_0x0055056f:\n\t"
        "%{disp8%} mov        cl, byte ptr [esp + 0x17]\n\t"
        "%{disp8%} mov        al, byte ptr [esp + 0x17]\n\t"
        "%{disp8%} mov        byte ptr [esp + 0x1d], cl\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x1c]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], ebx\n\t"
        "%{disp8%} mov        byte ptr [esp + 0x1c], al\n\t"
        "%{disp8%} mov        byte ptr [esp + 0x24], bl\n\t"
        "call               _jmp_addr_0x00556910\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x00205b80]\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x10]\n\t"
        "push               edx\n\t"
        "%{disp32%} lea       ecx, dword ptr [eax + 0x00000090]\n\t"
        "call               _jmp_addr_0x00555cc0\n\t"
        "cmp.s              eax, ebx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], eax\n\t"
        "%{disp8%} je         LAB__addr_0x005505df\n"
        "LAB__addr_0x005505ae:\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x10]\n\t"
        "push               eax\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x34]\n\t"
        "push               ecx\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x24]\n\t"
        "call               _jmp_addr_0x00555f40\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x00205b80]\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x10]\n\t"
        "push               edx\n\t"
        "%{disp32%} lea       ecx, dword ptr [eax + 0x00000090]\n\t"
        "call               _jmp_addr_0x00555cc0\n\t"
        "cmp.s              eax, ebx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], eax\n\t"
        "%{disp8%} jne        LAB__addr_0x005505ae\n"
        "LAB__addr_0x005505df:\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x20]\n\t"
        "mov                eax, dword ptr [ecx]\n\t"
        "cmp.s              eax, ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x2c], eax\n\t"
        "%{disp8%} je         LAB__addr_0x00550665\n"
        "LAB__addr_0x005505ed:\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x0c]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], eax\n\t"
        "cmp                dword ptr [eax + 0x000001f8], ebx\n\t"
        "%{disp8%} jne        LAB__addr_0x00550614\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x00000174]\n\t"
        "push               0x6\n\t"
        "%{disp32%} mov       byte ptr [ecx + 0x00bea9a0], 0x06\n\t"
        "push               eax\n\t"
        "%{disp32%} lea       ecx, dword ptr [esi + 0x00003e58]\n\t"
        "%{disp8%} jmp        LAB__addr_0x0055064d\n"
        "LAB__addr_0x00550614:\n\t"
        "%{disp32%} mov       dl, byte ptr [eax + 0x000001f8]\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x00000174]\n\t"
        "dec                dl\n\t"
        "%{disp32%} mov       byte ptr [ecx + 0x00bea9a0], dl\n\t"
        "xor.s              edx, edx\n\t"
        "%{disp32%} mov       dl, byte ptr [eax + 0x000001f8]\n\t"
        "dec                dl\n\t"
        "push               edx\n\t"
        "push               eax\n\t"
        "%{disp32%} mov       eax, dword ptr [eax + 0x000001f8]\n\t"
        "lea                ecx, dword ptr [eax + eax * 0x4]\n\t"
        "lea                edx, dword ptr [eax + ecx * 0x8]\n\t"
        "lea                eax, dword ptr [eax + edx * 0x2]\n\t"
        "shl                eax, 5\n\t"
        "%{disp32%} lea       ecx, dword ptr [eax + esi * 0x1 + -0x00000a48]\n"
        "LAB__addr_0x0055064d:\n\t"
        "call               _jmp_addr_0x00649110\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x2c]\n\t"
        "call               _jmp_addr_0x00556c10\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x2c]\n\t"
        "cmp                eax, dword ptr [esp + 0x20]\n\t"
        "%{disp8%} jne        LAB__addr_0x005505ed\n"
        "LAB__addr_0x00550665:\n\t"
        "xor.s              edi, edi\n\t"
        "add                esi, 0x18\n"
        "LAB__addr_0x0055066a:\n\t"
        "%{disp8%} lea        ebp, dword ptr [edi + 0x01]\n\t"
        "push               ebp\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x3c]\n\t"
        "push               0x00bec8dc\n\t"
        "push               ecx\n\t"
        "call               _sprintf\n\t"
        "add                esp, 0x0c\n\t"
        "push               ebx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetNextInterfaceStatus@GPlayer@@QAEPAVGInterfaceStatus@@PAV2@@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x005506a4\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x38]\n\t"
        "push               edi\n\t"
        "push               edx\n\t"
        "call               _CHAR2WCHAR__FPc\n\t"
        "add                esp, 0x04\n\t"
        "push               eax\n\t"
        "push               edi\n\t"
        "push               ebx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @Init__7GPlayerF11PLAYER_TYPEUcPwUc@18\n"
        "LAB__addr_0x005506a4:\n\t"
        "mov.s              edi, ebp\n\t"
        "add                esi, 0x00000a60\n\t"
        "cmp                edi, 0x07\n\t"
        ".byte              0x72, 0xb9\n\t"
        "%{disp8%} mov        esi, dword ptr [esp + 0x20]\n\t"
        "cmp                dword ptr [esp + 0x28], ebx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], eax\n\t"
        "%{disp8%} je         LAB__addr_0x005506f4\n\t"
        "mov.s              ecx, eax\n\t"
        "cmp.s              eax, ecx\n\t"
        "%{disp8%} jne        LAB__addr_0x005506f4\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x04]\n\t"
        "push               eax\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x20]\n\t"
        "call               _jmp_addr_0x005568d0\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x20]\n\t"
        "%{disp32%} mov       edx, dword ptr [data_bytes + 0x33b9e0]\n\t"
        "%{disp8%} mov        dword ptr [ecx + 0x04], edx\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x20]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x28], ebx\n\t"
        "mov                dword ptr [eax], eax\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x20]\n\t"
        "%{disp8%} mov        dword ptr [eax + 0x08], eax\n\t"
        "%{disp8%} jmp        LAB__addr_0x0055071a\n"
        "LAB__addr_0x005506f4:\n\t"
        "cmp.s              eax, esi\n\t"
        "%{disp8%} je         LAB__addr_0x0055071a\n"
        "LAB__addr_0x005506f8:\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x18]\n\t"
        "mov.s              edi, eax\n\t"
        "call               _jmp_addr_0x00556c10\n\t"
        "push               edi\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x34]\n\t"
        "push               eax\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x24]\n\t"
        "call               _jmp_addr_0x005564d0\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x18]\n\t"
        "cmp.s              eax, esi\n\t"
        "%{disp8%} jne        LAB__addr_0x005506f8\n"
        "LAB__addr_0x0055071a:\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x20]\n\t"
        "push               ecx\n\t"
        "call               ??3@YAXPAX@Z\n\t"
        "add                esp, 0x04\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x18]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x20], ebx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x28], ebx\n\t"
        "xor.s              esi, esi\n\t"
        "call               ??0_Lockit@std@@QAE@XZ\n\t"
        "%{disp32%} mov       eax, dword ptr [data_bytes + 0x33b9dc]\n\t"
        "dec                eax\n\t"
        "pop                edi\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x33b9dc], eax\n\t"
        "pop                ebp\n\t"
        "%{disp8%} jne        LAB__addr_0x00550755\n\t"
        "%{disp32%} mov       esi, dword ptr [data_bytes + 0x33b9e0]\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x33b9e0], ebx\n"
        "LAB__addr_0x00550755:\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x10]\n\t"
        "call               ??1_Lockit@std@@QAE@XZ\n\t"
        "cmp.s              esi, ebx\n\t"
        "%{disp8%} je         LAB__addr_0x0055076b\n\t"
        "push               esi\n\t"
        "call               ??3@YAXPAX@Z\n\t"
        "add                esp, 0x04\n"
        "LAB__addr_0x0055076b:\n\t"
        "pop                esi\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x000000f0"
        ::: "eax", "ecx", "edx", "memory"
    );
}

__attribute__((no_callee_saves, XOR32rr_REV))
void __fastcall Dump__5GGameFv(struct Base* this)
{
    asm volatile (
        "push               esi\n\t"
        "push               edi\n\t"
        "mov.s              edi, ecx\n\t"
        "xor.s              esi, esi\n"
        "LAB__addr_0x00550786:\n\t"
        "push               esi\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?GetPlayer@GGame@@QAEPAVGPlayer@@K@Z\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               dword ptr [edx + 0x18]\n\t"
        "inc                esi\n\t"
        "cmp                esi, 0x08\n\t"
        ".byte              0x72, 0xeb\n\t"
        "%{disp32%} mov       eax, dword ptr [edi + 0x000059b8]\n\t"
        "%{disp32%} lea       ecx, dword ptr [edi + 0x000059b8]\n\t"
        "call               dword ptr [eax + 0x18]\n\t"
        "%{disp32%} mov       edx, dword ptr [edi + 0x00205ba4]\n\t"
        "%{disp32%} lea       ecx, dword ptr [edi + 0x00205ba4]\n\t"
        "call               dword ptr [edx + 0x18]\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "ret\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop\n\t"
        "nop"
        ::: "eax", "ecx", "edx", "memory"
    );
}

void __fastcall LoopThroughPlayers__5GGameFv(struct GGame* this)
{
    void* dummy;
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "push               0x0\n\t"
        "call               ?GetNextPlayer@GGame@@QAEPAVGPlayer@@PAV2@@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x005507ea\n\t"
        "LAB__addr_0x005507de:\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetNextPlayer@GGame@@QAEPAVGPlayer@@PAV2@@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x005507de\n\t"
        "LAB__addr_0x005507ea:\n\t"
        "pop                esi"
        : "=c"(dummy) : "c"(this) : "eax", "edx", "memory"
    );
}

void __fastcall Birthday__5GGameFv(struct GGame* this)
{
    void* dummy;
    asm volatile (
        "push               esi\n\t"
        "push               edi\n\t"
        "mov.s              edi, ecx\n\t"
        "push               0x0\n\t"
        "call               ?GetNextPlayerAndNeutral@GGame@@QAEPAVGPlayer@@PAV2@@Z\n\t"
        "mov.s              esi, eax\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x00550816\n\t"
        "LAB__addr_0x00550801:\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?Birthday@GPlayer@@QAEXXZ\n\t"
        "push               esi\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?GetNextPlayerAndNeutral@GGame@@QAEPAVGPlayer@@PAV2@@Z\n\t"
        "mov.s              esi, eax\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} jne        LAB__addr_0x00550801\n\t"
        "LAB__addr_0x00550816:\n\t"
        "pop                edi\n\t"
        "pop                esi"
        : "=c"(dummy) : "c"(this) : "eax", "edx", "memory"
    );
}

__attribute__((no_callee_saves, XOR32rr_REV))
int __fastcall MyPlayerID__5GGameFUl(struct GGame* this, const void* edx, unsigned long param_1)
{
    int result;
    asm volatile (
        "push               ebx\n\t"
        "%{disp8%} mov        ebx, dword ptr [esp + 0x08]\n\t"
        "push               ebp\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "xor.s              ebp, ebp\n\t"
        "%{disp8%} lea        edi, dword ptr [ecx + 0x18]\n"
        "LAB__addr_0x0055082d:\n\t"
        "push               0x0\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?GetNextInterfaceStatus@GPlayer@@QAEPAVGInterfaceStatus@@PAV2@@Z\n\t"
        "mov.s              esi, eax\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x00550870\n"
        "LAB__addr_0x0055083c:\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetInterface@GInterfaceStatus@@QAEPAVGInterface@@XZ\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x000001bc]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x00550862\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetInterface@GInterfaceStatus@@QAEPAVGInterface@@XZ\n\t"
        "%{disp32%} mov       eax, dword ptr [eax + 0x000001bc]\n\t"
        "cmp                dword ptr [eax + 0x00000178], ebx\n\t"
        "%{disp8%} je         LAB__addr_0x00550886\n"
        "LAB__addr_0x00550862:\n\t"
        "push               esi\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?GetNextInterfaceStatus@GPlayer@@QAEPAVGInterfaceStatus@@PAV2@@Z\n\t"
        "mov.s              esi, eax\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} jne        LAB__addr_0x0055083c\n"
        "LAB__addr_0x00550870:\n\t"
        "inc                ebp\n\t"
        "add                edi, 0x00000a60\n\t"
        "cmp                ebp, 0x08\n\t"
        ".byte              0x72, 0xb1\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "or                 eax, -0x1\n\t"
        "pop                ebx\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x00550886:\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetInterface@GInterfaceStatus@@QAEPAVGInterface@@XZ\n\t"
        "%{disp32%} mov       eax, dword ptr [eax + 0x000001bc]\n\t"
        "%{disp32%} mov       eax, dword ptr [eax + 0x00000174]\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "pop                ebx"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV))
struct GPlayer* __fastcall GetNextPlayer__5GGameFP7GPlayer(struct GGame* this, const void* edx, struct GPlayer* param_1)
{
    struct GPlayer* result;
    asm volatile (
        "%{disp8%} mov        edx, dword ptr [esp + 0x04]\n\t"
        "test               edx, edx\n\t"
        "%{disp8%} jne        LAB__addr_0x005508ba\n\t"
        "%{disp8%} lea        edx, dword ptr [ecx + 0x18]\n"
        "LAB__addr_0x005508ab:\n\t"
        "add                ecx, 0x000048b8\n\t"
        "cmp.s              edx, ecx\n\t"
        "sbb.s              eax, eax\n\t"
        "and.s              eax, edx\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x005508ba:\n\t"
        "%{disp32%} mov       eax, dword ptr [edx + 0x00001340]\n\t"
        "add                edx, 0x00000a60\n\t"
        "cmp                eax, 0x03\n\t"
        "%{disp8%} jne        LAB__addr_0x005508ab\n\t"
        "xor.s              eax, eax"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV))
struct GPlayer* __fastcall GetNextActivePlayer__5GGameFP7GPlayer(struct GGame* this, const void* edx, struct GPlayer* param_1)
{
    struct GPlayer* result;
    asm volatile (
        "%{disp8%} mov        edx, dword ptr [esp + 0x04]\n\t"
        "test               edx, edx\n\t"
        "%{disp8%} jne        LAB__addr_0x00550910\n\t"
        "%{disp8%} lea        edx, dword ptr [ecx + 0x18]\n"
        "LAB__addr_0x005508db:\n\t"
        "%{disp32%} mov       eax, dword ptr [edx + 0x000008e0]\n\t"
        "test               eax, eax\n\t"
        "push               esi\n\t"
        "%{disp8%} jne        LAB__addr_0x00550900\n\t"
        "%{disp32%} lea       eax, dword ptr [ecx + 0x000048b8]\n"
        "LAB__addr_0x005508ec:\n\t"
        "cmp.s              edx, eax\n\t"
        "%{disp8%} jae        LAB__addr_0x00550900\n\t"
        "%{disp32%} mov       esi, dword ptr [edx + 0x00001340]\n\t"
        "add                edx, 0x00000a60\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x005508ec\n"
        "LAB__addr_0x00550900:\n\t"
        "add                ecx, 0x000048b8\n\t"
        "cmp.s              edx, ecx\n\t"
        "sbb.s              eax, eax\n\t"
        "and.s              eax, edx\n\t"
        "pop                esi\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x00550910:\n\t"
        "%{disp32%} mov       eax, dword ptr [edx + 0x00001340]\n\t"
        "add                edx, 0x00000a60\n\t"
        "cmp                eax, 0x03\n\t"
        "%{disp8%} jne        LAB__addr_0x005508db\n\t"
        "xor.s              eax, eax"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves))
struct GPlayer* __fastcall GetNextActivePlayerAndNeutral__5GGameFP7GPlayer(struct GGame* this, const void* edx, struct GPlayer* player)
{
    struct GPlayer* result;
    asm volatile (
        "%{disp8%} mov        edx, dword ptr [esp + 0x04]\n\t"
        "test               edx, edx\n\t"
        "%{disp8%} jne        LAB__addr_0x0055093d\n\t"
        "%{disp8%} lea        edx, dword ptr [ecx + 0x18]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00550943\n"
        "LAB__addr_0x0055093d:\n\t"
        "add                edx, 0x00000a60\n"
        "LAB__addr_0x00550943:\n\t"
        "%{disp32%} mov       eax, dword ptr [edx + 0x000008e0]\n\t"
        "test               eax, eax\n\t"
        "push               esi\n\t"
        "%{disp8%} jne        LAB__addr_0x00550968\n\t"
        "%{disp32%} lea       eax, dword ptr [ecx + 0x000048b8]\n"
        "LAB__addr_0x00550954:\n\t"
        "cmp.s              edx, eax\n\t"
        "%{disp8%} jae        LAB__addr_0x00550968\n\t"
        "%{disp32%} mov       esi, dword ptr [edx + 0x00001340]\n\t"
        "add                edx, 0x00000a60\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x00550954\n"
        "LAB__addr_0x00550968:\n\t"
        "add                ecx, 0x00005318\n\t"
        "cmp.s              edx, ecx\n\t"
        "sbb.s              eax, eax\n\t"
        "and.s              eax, edx\n\t"
        "pop                esi"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves))
struct GPlayer* __fastcall GetNextPlayerAndNeutral__5GGameFP7GPlayer(struct GGame* this, const void* edx, struct GPlayer* player)
{
    struct GPlayer* result;
    asm volatile (
        "%{disp8%} mov edx, dword ptr [esp + 0x04]\n\t"
        "test edx, edx\n\t"
        "%{disp8%} jne 0f\n\t"
        "%{disp8%} lea edx, dword ptr [ecx + 0x18]\n\t"
        "add ecx, 0x00005318\n\t"
        "cmp.s edx, ecx\n\t"
        ".byte 0x1b, 0xc0\n\t"
        "and.s eax, edx\n\t"
        "ret 0x0004\n"
        "0:\n\t"
        "add edx, 0x00000a60\n\t"
        "add ecx, 0x00005318\n\t"
        "cmp.s edx, ecx\n\t"
        ".byte 0x1b, 0xc0\n\t"
        "and.s eax, edx"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV))
struct GPlayer* __fastcall GetPlayer__5GGameFUl(struct GGame* this, const void* edx, uint32_t param_1)
{
    struct GPlayer* result;
    asm volatile (
        "%{disp8%} mov eax, dword ptr [esp + 0x04]\n\t"
        "cmp eax, 0x08\n\t"
        ".byte 0x72, 0x5\n\t"
        "xor.s eax, eax\n\t"
        "ret 0x0004\n\t"
        "lea edx, dword ptr [eax + eax * 0x4]\n\t"
        "lea edx, dword ptr [eax + edx * 0x8]\n\t"
        "lea eax, dword ptr [eax + edx * 0x2]\n\t"
        "shl eax, 5\n\t"
        "%{disp8%} lea eax, dword ptr [eax + ecx * 0x1 + 0x18]"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV, trailing_asm("call ?GetVillagerActivityDesire@GameThing@@QAEMPAVVillager@@@Z + 9")))
struct GPlayer* __fastcall GetPlayerFromReal__5GGameFUl(struct GGame* this, const void* edx, unsigned long param_1)
{
    struct GPlayer* result;
    asm volatile (
        "%{disp8%} mov eax, dword ptr [esp + 0x04]\n\t"
        "cmp eax, 0x08\n\t"
        ".byte 0x72, 0x5\n\t"
        "xor.s eax, eax\n\t"
        "ret 0x0004\n\t"
        "xor.s edx, edx\n\t"
        "%{disp32%} mov dl, byte ptr [eax + 0x00bea9a0]\n\t"
        "mov.s eax, edx\n\t"
        "lea edx, dword ptr [eax + eax * 0x4]\n\t"
        "lea edx, dword ptr [eax + edx * 0x8]\n\t"
        "lea eax, dword ptr [eax + edx * 0x2]\n\t"
        "shl eax, 5\n\t"
        "%{disp8%} lea eax, dword ptr [eax + ecx * 0x1 + 0x18]"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV))
struct GInterface* __fastcall GetPlayerInterfaceFromReal__5GGameFUl(struct GGame* this, const void* edx, unsigned long param_1)
{
    struct GInterface* result;
    asm volatile (
        "%{disp8%} mov eax, dword ptr [esp + 0x04]\n\t"
        "cmp eax, 0x08\n\t"
        ".byte 0x72, 0x5\n\t"
        "xor.s eax, eax\n\t"
        "ret 0x0004\n\t"
        "push eax\n\t"
        "push eax\n\t"
        "call ?GetPlayerFromReal@GGame@@QAEPAVGPlayer@@K@Z\n\t"
        "mov.s ecx, eax\n\t"
        "call @GetRealInterface__7GPlayerFUl@12"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV, ret_cleanup_override(0x00)))
struct GPlayer* __fastcall GetNextPlayerWithNoCreature__5GGameFP7GPlayer(struct GGame* this, const void* edx, struct GPlayer* param_1)
{
    struct GPlayer* result;
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "push               0x0\n\t"
        "call               ?GetNextPlayer@GGame@@QAEPAVGPlayer@@PAV2@@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00550a54\n"
        "LAB__addr_0x00550a3e:\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x00000a4c]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x00550a56\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetNextPlayer@GGame@@QAEPAVGPlayer@@PAV2@@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x00550a3e\n"
        "LAB__addr_0x00550a54:\n\t"
        "xor.s              eax, eax\n"
        "LAB__addr_0x00550a56:\n\t"
        "pop                esi"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV))
struct GPlayer* __fastcall GetPlayer__5GGameF11PLAYER_NAME(struct GGame* this, const void* edx, enum PLAYER_NAME param_1)
{
    struct GPlayer* result;
    asm volatile (
        "%{disp8%} mov        eax, dword ptr [esp + 0x04]\n\t"
        "lea                edx, dword ptr [eax + eax * 0x4]\n\t"
        "lea                edx, dword ptr [eax + edx * 0x8]\n\t"
        "lea                eax, dword ptr [eax + edx * 0x2]\n\t"
        "shl                eax, 5\n\t"
        "%{disp8%} lea        eax, dword ptr [eax + ecx * 0x1 + 0x18]"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}
