#include "libs/lionhead/lh3dlib/development/LH3DMesh.h"

__attribute__((no_callee_saves, XOR32rr_REV, no_tail_merge, prefer_test_ah("5:eax"), defer_zero_eax))
uint32_t __fastcall GetSizeFootprintData__8LH3DMeshFv(struct LH3DMesh* param_1)
{
    uint32_t flags = *(uint32_t*)((char*)param_1 + 0x04);
    if (__builtin_expect(flags & 0x8000, 1)) {
        return *(uint32_t*)((char*)param_1 + 0x48);
    }
    return 0;
}

__attribute__((no_callee_saves, XOR32rr_REV))
uint32_t __fastcall GetSizeUV2Data__8LH3DMeshFv(struct LH3DMesh* param_1)
{
    uint32_t result;
    asm volatile (
        "%{disp8%} mov eax, dword ptr [ecx + 0x04]\n\t"
        "test eax, 0x00040000\n\t"
        "%{disp8%} jne 0f\n\t"
        "xor.s eax, eax\n\t"
        "ret\n"
        "0:\n\t"
        "test ah, -0x80\n\t"
        "%{disp8%} je 1f\n\t"
        "%{disp8%} mov eax, dword ptr [ecx + 0x48]\n\t"
        "%{disp8%} mov edx, dword ptr [eax + 0x08]\n\t"
        "add.s eax, edx\n\t"
        "ret\n"
        "1:\n\t"
        "%{disp8%} mov eax, dword ptr [ecx + 0x48]\n\t"
        "xor.s edx, edx\n\t"
        "add.s eax, edx"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV))
uint32_t __fastcall GetSizeNameData__8LH3DMeshFv(struct LH3DMesh* param_1)
{
    uint32_t result;
    asm volatile (
        "%{disp8%} mov        edx, dword ptr [ecx + 0x04]\n\t"
        "test               edx, 0x00080000\n\t"
        "%{disp8%} jne        LAB__addr_0x0040377e\n\t"
        "xor.s              eax, eax\n\t"
        "ret\n"
        "LAB__addr_0x0040377e:\n\t"
        "push               esi\n\t"
        "mov.s              esi, edx\n\t"
        "and                esi, 0x00008000\n\t"
        "push               edi\n\t"
        "%{disp8%} je         LAB__addr_0x00403792\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "%{disp8%} mov        edi, dword ptr [eax + 0x08]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403794\n"
        "LAB__addr_0x00403792:\n\t"
        "xor.s              edi, edi\n"
        "LAB__addr_0x00403794:\n\t"
        "test               edx, 0x00040000\n\t"
        "%{disp8%} je         LAB__addr_0x004037c7\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x004037b4\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x08]\n\t"
        "add.s              eax, edx\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "add.s              eax, edx\n\t"
        "add.s              eax, edi\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x004037b4:\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "xor.s              edx, edx\n\t"
        "add.s              eax, edx\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "add.s              eax, edx\n\t"
        "add.s              eax, edi\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x004037c7:\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "xor.s              edx, edx\n\t"
        "add.s              eax, edx\n\t"
        "add.s              eax, edi\n\t"
        "pop                edi\n\t"
        "pop                esi"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV))
uint32_t __fastcall GetSizeEMetricsData__8LH3DMeshFv(struct LH3DMesh* param_1)
{
    uint32_t result;
    asm volatile (
        "push               ecx\n\t"
        "push               esi\n\t"
        "%{disp8%} mov        esi, dword ptr [ecx + 0x04]\n\t"
        "test               esi, 0x00100000\n\t"
        "%{disp8%} jne        LAB__addr_0x004037f2\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi\n\t"
        "pop                ecx\n\t"
        "ret\n"
        "LAB__addr_0x004037f2:\n\t"
        "push               ebx\n\t"
        "push               ebp\n\t"
        "push               edi\n\t"
        "mov.s              edi, esi\n\t"
        "and                edi, 0x00008000\n\t"
        "%{disp8%} je         LAB__addr_0x0040380b\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x08]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], eax\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403813\n"
        "LAB__addr_0x0040380b:\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], 0x00000000\n"
        "LAB__addr_0x00403813:\n\t"
        "mov.s              ebx, esi\n\t"
        "and                ebx, 0x00040000\n\t"
        "%{disp8%} je         LAB__addr_0x0040383a\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x0040382e\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x08]\n\t"
        "mov                ebp, dword ptr [eax + edx * 0x1]\n\t"
        "add.s              eax, edx\n\t"
        "%{disp8%} jmp        LAB__addr_0x0040383c\n"
        "LAB__addr_0x0040382e:\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "xor.s              edx, edx\n\t"
        "mov                ebp, dword ptr [eax + edx * 0x1]\n\t"
        "add.s              eax, edx\n\t"
        "%{disp8%} jmp        LAB__addr_0x0040383c\n"
        "LAB__addr_0x0040383a:\n\t"
        "xor.s              ebp, ebp\n"
        "LAB__addr_0x0040383c:\n\t"
        "test               esi, 0x00080000\n\t"
        "%{disp32%} je        LAB__addr_0x004038ca\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x00403854\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "%{disp8%} mov        esi, dword ptr [eax + 0x08]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403856\n"
        "LAB__addr_0x00403854:\n\t"
        "xor.s              esi, esi\n"
        "LAB__addr_0x00403856:\n\t"
        "test               ebx, ebx\n\t"
        "%{disp8%} je         LAB__addr_0x004038ab\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x00403885\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x08]\n\t"
        "add.s              eax, edx\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "add.s              eax, edx\n\t"
        "mov                edx, dword ptr [eax + esi * 0x1]\n\t"
        "add.s              eax, esi\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x10]\n\t"
        "add.s              eax, edx\n\t"
        "pop                edi\n\t"
        "add.s              eax, ebp\n\t"
        "pop                ebp\n\t"
        "pop                ebx\n\t"
        "add.s              eax, ecx\n\t"
        "pop                esi\n\t"
        "pop                ecx\n\t"
        "ret\n"
        "LAB__addr_0x00403885:\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "xor.s              edx, edx\n\t"
        "add.s              eax, edx\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "add.s              eax, edx\n\t"
        "mov                edx, dword ptr [eax + esi * 0x1]\n\t"
        "add.s              eax, esi\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x10]\n\t"
        "add.s              eax, edx\n\t"
        "pop                edi\n\t"
        "add.s              eax, ebp\n\t"
        "pop                ebp\n\t"
        "pop                ebx\n\t"
        "add.s              eax, ecx\n\t"
        "pop                esi\n\t"
        "pop                ecx\n\t"
        "ret\n"
        "LAB__addr_0x004038ab:\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "xor.s              edx, edx\n\t"
        "add.s              eax, edx\n\t"
        "mov                edx, dword ptr [eax + esi * 0x1]\n\t"
        "add.s              eax, esi\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x10]\n\t"
        "add.s              eax, edx\n\t"
        "pop                edi\n\t"
        "add.s              eax, ebp\n\t"
        "pop                ebp\n\t"
        "pop                ebx\n\t"
        "add.s              eax, ecx\n\t"
        "pop                esi\n\t"
        "pop                ecx\n\t"
        "ret\n"
        "LAB__addr_0x004038ca:\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x10]\n\t"
        "xor.s              edx, edx\n\t"
        "add.s              eax, edx\n\t"
        "pop                edi\n\t"
        "add.s              eax, ebp\n\t"
        "pop                ebp\n\t"
        "pop                ebx\n\t"
        "add.s              eax, ecx\n\t"
        "pop                esi\n\t"
        "pop                ecx"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV))
uint32_t __fastcall GetSizeEBone__8LH3DMeshFv(struct LH3DMesh* param_1)
{
    uint32_t result;
    asm volatile (
        "sub                esp, 0x08\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp8%} mov        edx, dword ptr [esi + 0x04]\n\t"
        "test               edx, 0x00200000\n\t"
        "%{disp8%} jne        LAB__addr_0x004038f8\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi\n\t"
        "add                esp, 0x08\n\t"
        "ret\n"
        "LAB__addr_0x004038f8:\n\t"
        "push               ebx\n\t"
        "mov.s              ebx, edx\n\t"
        "and                ebx, 0x00008000\n\t"
        "push               ebp\n\t"
        "push               edi\n\t"
        "%{disp8%} je         LAB__addr_0x00403911\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x48]\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x08]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], eax\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403919\n"
        "LAB__addr_0x00403911:\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], 0x00000000\n"
        "LAB__addr_0x00403919:\n\t"
        "mov.s              ebp, edx\n\t"
        "and                ebp, 0x00040000\n\t"
        "%{disp8%} je         LAB__addr_0x00403946\n\t"
        "test               ebx, ebx\n\t"
        "%{disp8%} je         LAB__addr_0x00403937\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x48]\n\t"
        "%{disp8%} mov        ecx, dword ptr [eax + 0x08]\n\t"
        "add.s              eax, ecx\n\t"
        "mov                ecx, dword ptr [eax]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], ecx\n\t"
        "%{disp8%} jmp        LAB__addr_0x0040394e\n"
        "LAB__addr_0x00403937:\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x48]\n\t"
        "xor.s              ecx, ecx\n\t"
        "add.s              eax, ecx\n\t"
        "mov                ecx, dword ptr [eax]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], ecx\n\t"
        "%{disp8%} jmp        LAB__addr_0x0040394e\n"
        "LAB__addr_0x00403946:\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], 0x00000000\n"
        "LAB__addr_0x0040394e:\n\t"
        "test               edx, 0x00080000\n\t"
        "%{disp8%} je         LAB__addr_0x004039ac\n\t"
        "test               ebx, ebx\n\t"
        "%{disp8%} je         LAB__addr_0x00403962\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x48]\n\t"
        "%{disp8%} mov        edi, dword ptr [eax + 0x08]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403964\n"
        "LAB__addr_0x00403962:\n\t"
        "xor.s              edi, edi\n"
        "LAB__addr_0x00403964:\n\t"
        "test               ebp, ebp\n\t"
        "%{disp8%} je         LAB__addr_0x0040399e\n\t"
        "test               ebx, ebx\n\t"
        "%{disp8%} je         LAB__addr_0x00403989\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetSizeFootprintData@LH3DMesh@@QAEIXZ\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x08]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x48]\n\t"
        "add.s              ecx, eax\n\t"
        "mov                ecx, dword ptr [ecx]\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x48]\n\t"
        "add.s              eax, ecx\n\t"
        "mov                ebp, dword ptr [eax + edi * 0x1]\n\t"
        "add.s              eax, edi\n\t"
        "%{disp8%} jmp        LAB__addr_0x004039ae\n"
        "LAB__addr_0x00403989:\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x48]\n\t"
        "xor.s              eax, eax\n\t"
        "add.s              ecx, eax\n\t"
        "mov                ecx, dword ptr [ecx]\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x48]\n\t"
        "add.s              eax, ecx\n\t"
        "mov                ebp, dword ptr [eax + edi * 0x1]\n\t"
        "add.s              eax, edi\n\t"
        "%{disp8%} jmp        LAB__addr_0x004039ae\n"
        "LAB__addr_0x0040399e:\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x48]\n\t"
        "xor.s              ecx, ecx\n\t"
        "add.s              eax, ecx\n\t"
        "mov                ebp, dword ptr [eax + edi * 0x1]\n\t"
        "add.s              eax, edi\n\t"
        "%{disp8%} jmp        LAB__addr_0x004039ae\n"
        "LAB__addr_0x004039ac:\n\t"
        "xor.s              ebp, ebp\n"
        "LAB__addr_0x004039ae:\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x04]\n\t"
        "test               ecx, 0x00100000\n\t"
        "%{disp8%} je         LAB__addr_0x00403a0b\n\t"
        "test               ch, -0x80\n\t"
        "%{disp8%} je         LAB__addr_0x004039c6\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x48]\n\t"
        "%{disp8%} mov        ebx, dword ptr [eax + 0x08]\n\t"
        "%{disp8%} jmp        LAB__addr_0x004039c8\n"
        "LAB__addr_0x004039c6:\n\t"
        "xor.s              ebx, ebx\n"
        "LAB__addr_0x004039c8:\n\t"
        "test               ecx, 0x00040000\n\t"
        "%{disp8%} je         LAB__addr_0x004039db\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetSizeUV2Data@LH3DMesh@@QAEIXZ\n\t"
        "mov                edi, dword ptr [eax]\n\t"
        "%{disp8%} jmp        LAB__addr_0x004039dd\n"
        "LAB__addr_0x004039db:\n\t"
        "xor.s              edi, edi\n"
        "LAB__addr_0x004039dd:\n\t"
        "test               dword ptr [esi + 0x04], 0x00080000\n\t"
        "%{disp8%} je         LAB__addr_0x004039fc\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetSizeNameData@LH3DMesh@@QAEIXZ\n\t"
        "mov                eax, dword ptr [eax]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x48]\n\t"
        "add.s              ecx, eax\n\t"
        "add.s              ecx, edi\n\t"
        "add.s              ecx, ebx\n\t"
        "mov                ecx, dword ptr [ecx]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403a0d\n"
        "LAB__addr_0x004039fc:\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x48]\n\t"
        "xor.s              eax, eax\n\t"
        "add.s              ecx, eax\n\t"
        "add.s              ecx, edi\n\t"
        "add.s              ecx, ebx\n\t"
        "mov                ecx, dword ptr [ecx]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403a0d\n"
        "LAB__addr_0x00403a0b:\n\t"
        "xor.s              ecx, ecx\n"
        "LAB__addr_0x00403a0d:\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x48]\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x10]\n\t"
        "add.s              eax, ecx\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x14]\n\t"
        "pop                edi\n\t"
        "add.s              eax, ebp\n\t"
        "pop                ebp\n\t"
        "add.s              eax, edx\n\t"
        "pop                ebx\n\t"
        "add.s              eax, ecx\n\t"
        "pop                esi\n\t"
        "add                esp, 0x08"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV))
uint32_t __fastcall GetSizeTnLData__8LH3DMeshFv(struct LH3DMesh* param_1)
{
    uint32_t result;
    asm volatile (
        "sub                esp, 0x08\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "push               edi\n\t"
        "%{disp8%} mov        edi, dword ptr [esi + 0x04]\n\t"
        "test               edi, 0x00400000\n\t"
        "%{disp32%} je        LAB__addr_0x00403b7d\n\t"
        "mov.s              edx, edi\n\t"
        "and                edx, 0x00008000\n\t"
        "%{disp8%} je         LAB__addr_0x00403a5c\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x48]\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x08]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], eax\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403a64\n"
        "LAB__addr_0x00403a5c:\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], 0x00000000\n"
        "LAB__addr_0x00403a64:\n\t"
        "test               edi, 0x00040000\n\t"
        "%{disp8%} je         LAB__addr_0x00403a8f\n\t"
        "test               edx, edx\n\t"
        "%{disp8%} je         LAB__addr_0x00403a80\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x48]\n\t"
        "%{disp8%} mov        ecx, dword ptr [eax + 0x08]\n\t"
        "add.s              eax, ecx\n\t"
        "mov                ecx, dword ptr [eax]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], ecx\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403a97\n"
        "LAB__addr_0x00403a80:\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x48]\n\t"
        "xor.s              ecx, ecx\n\t"
        "add.s              eax, ecx\n\t"
        "mov                ecx, dword ptr [eax]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], ecx\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403a97\n"
        "LAB__addr_0x00403a8f:\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], 0x00000000\n"
        "LAB__addr_0x00403a97:\n\t"
        "test               edi, 0x00080000\n\t"
        "push               ebx\n\t"
        "push               ebp\n\t"
        "%{disp8%} je         LAB__addr_0x00403adf\n\t"
        "test               edx, edx\n\t"
        "%{disp8%} je         LAB__addr_0x00403ab1\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetSizeFootprintData@LH3DMesh@@QAEIXZ\n\t"
        "%{disp8%} mov        edi, dword ptr [eax + 0x08]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403ab3\n"
        "LAB__addr_0x00403ab1:\n\t"
        "xor.s              edi, edi\n"
        "LAB__addr_0x00403ab3:\n\t"
        "test               dword ptr [esi + 0x04], 0x00040000\n\t"
        "%{disp8%} je         LAB__addr_0x00403ad1\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetSizeUV2Data@LH3DMesh@@QAEIXZ\n\t"
        "mov                eax, dword ptr [eax]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x48]\n\t"
        "add.s              ecx, eax\n\t"
        "mov                ebp, dword ptr [ecx + edi * 0x1]\n\t"
        "add.s              ecx, edi\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403ae1\n"
        "LAB__addr_0x00403ad1:\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x48]\n\t"
        "xor.s              eax, eax\n\t"
        "add.s              ecx, eax\n\t"
        "mov                ebp, dword ptr [ecx + edi * 0x1]\n\t"
        "add.s              ecx, edi\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403ae1\n"
        "LAB__addr_0x00403adf:\n\t"
        "xor.s              ebp, ebp\n"
        "LAB__addr_0x00403ae1:\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x04]\n\t"
        "test               eax, 0x00100000\n\t"
        "%{disp8%} je         LAB__addr_0x00403b26\n\t"
        "test               ah, -0x80\n\t"
        "%{disp8%} je         LAB__addr_0x00403afc\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetSizeFootprintData@LH3DMesh@@QAEIXZ\n\t"
        "%{disp8%} mov        ebx, dword ptr [eax + 0x08]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403afe\n"
        "LAB__addr_0x00403afc:\n\t"
        "xor.s              ebx, ebx\n"
        "LAB__addr_0x00403afe:\n\t"
        "test               dword ptr [esi + 0x04], 0x00040000\n\t"
        "%{disp8%} je         LAB__addr_0x00403b12\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetSizeUV2Data@LH3DMesh@@QAEIXZ\n\t"
        "mov                edi, dword ptr [eax]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403b14\n"
        "LAB__addr_0x00403b12:\n\t"
        "xor.s              edi, edi\n"
        "LAB__addr_0x00403b14:\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetSizeNameData_dup1@LH3DMesh@@QAEIXZ\n\t"
        "add                eax, dword ptr [esi + 0x48]\n\t"
        "add.s              eax, edi\n\t"
        "add.s              eax, ebx\n\t"
        "mov                ebx, dword ptr [eax]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403b28\n"
        "LAB__addr_0x00403b26:\n\t"
        "xor.s              ebx, ebx\n"
        "LAB__addr_0x00403b28:\n\t"
        "test               dword ptr [esi + 0x04], 0x00200000\n\t"
        "%{disp8%} je         LAB__addr_0x00403b5c\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetSizeEMetricsData_dup1@LH3DMesh@@QAEIXZ\n\t"
        "mov.s              ecx, esi\n\t"
        "mov.s              edi, eax\n\t"
        "call               ?GetSizeNameData_dup1@LH3DMesh@@QAEIXZ\n\t"
        "mov.s              ecx, esi\n\t"
        "add.s              edi, eax\n\t"
        "call               ?GetSizeUV2Data_dup1@LH3DMesh@@QAEIXZ\n\t"
        "mov.s              ecx, esi\n\t"
        "add.s              edi, eax\n\t"
        "call               ?GetSizeFootprintData_dup1@LH3DMesh@@QAEIXZ\n\t"
        "add.s              edi, eax\n\t"
        "add                edi, dword ptr [esi + 0x48]\n\t"
        "mov                edi, dword ptr [edi]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403b5e\n"
        "LAB__addr_0x00403b5c:\n\t"
        "xor.s              edi, edi\n"
        "LAB__addr_0x00403b5e:\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x48]\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x10]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x14]\n\t"
        "add.s              eax, edi\n\t"
        "add.s              eax, ebx\n\t"
        "add.s              eax, ebp\n\t"
        "pop                ebp\n\t"
        "add.s              eax, edx\n\t"
        "pop                ebx\n\t"
        "add.s              eax, ecx\n\t"
        "mov                eax, dword ptr [eax]\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "add                esp, 0x08\n\t"
        "ret\n"
        "LAB__addr_0x00403b7d:\n\t"
        "pop                edi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi\n\t"
        "add                esp, 0x08"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV, no_tail_merge, prefer_test_ah("5:eax"), defer_zero_eax))
uint32_t __fastcall GetSizeFootprintData_dup1__8LH3DMeshFv(struct LH3DMesh* param_1)
{
    uint32_t flags = *(uint32_t*)((char*)param_1 + 0x04);
    if (__builtin_expect(flags & 0x8000, 1)) {
        return *(uint32_t*)(*(char**)((char*)param_1 + 0x48) + 0x08);
    }
    return 0;
}

__attribute__((no_callee_saves, XOR32rr_REV))
uint32_t __fastcall GetSizeUV2Data_dup1__8LH3DMeshFv(struct LH3DMesh* param_1)
{
    uint32_t result;
    asm volatile (
        "%{disp8%} mov        eax, dword ptr [ecx + 0x04]\n\t"
        "test               eax, 0x00040000\n\t"
        "%{disp8%} je         LAB__addr_0x00403bd4\n\t"
        "test               ah, -0x80\n\t"
        "%{disp8%} je         LAB__addr_0x00403bca\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x08]\n\t"
        "add.s              eax, edx\n\t"
        "mov                eax, dword ptr [eax]\n\t"
        "ret\n"
        "LAB__addr_0x00403bca:\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "xor.s              edx, edx\n\t"
        "add.s              eax, edx\n\t"
        "mov                eax, dword ptr [eax]\n\t"
        "ret\n"
        "LAB__addr_0x00403bd4:\n\t"
        "xor.s              eax, eax"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV))
uint32_t __fastcall GetSizeNameData_dup1__8LH3DMeshFv(struct LH3DMesh* param_1)
{
    uint32_t result;
    asm volatile (
        "%{disp8%} mov        edx, dword ptr [ecx + 0x04]\n\t"
        "test               edx, 0x00080000\n\t"
        "%{disp8%} je         LAB__addr_0x00403c46\n\t"
        "push               esi\n\t"
        "mov.s              esi, edx\n\t"
        "and                esi, 0x00008000\n\t"
        "push               edi\n\t"
        "%{disp8%} je         LAB__addr_0x00403bff\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "%{disp8%} mov        edi, dword ptr [eax + 0x08]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403c01\n"
        "LAB__addr_0x00403bff:\n\t"
        "xor.s              edi, edi\n"
        "LAB__addr_0x00403c01:\n\t"
        "test               edx, 0x00040000\n\t"
        "%{disp8%} je         LAB__addr_0x00403c38\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x00403c23\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x08]\n\t"
        "add.s              eax, edx\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "add.s              eax, edx\n\t"
        "add.s              eax, edi\n\t"
        "mov                eax, dword ptr [eax]\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x00403c23:\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "xor.s              edx, edx\n\t"
        "add.s              eax, edx\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "add.s              eax, edx\n\t"
        "add.s              eax, edi\n\t"
        "mov                eax, dword ptr [eax]\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x00403c38:\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "xor.s              edx, edx\n\t"
        "add.s              eax, edx\n\t"
        "add.s              eax, edi\n\t"
        "mov                eax, dword ptr [eax]\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x00403c46:\n\t"
        "xor.s              eax, eax"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV))
uint32_t __fastcall GetSizeEMetricsData_dup1__8LH3DMeshFv(struct LH3DMesh* param_1)
{
    uint32_t result;
    asm volatile (
        "push               ecx\n\t"
        "push               esi\n\t"
        "%{disp8%} mov        esi, dword ptr [ecx + 0x04]\n\t"
        "test               esi, 0x00100000\n\t"
        "%{disp32%} je        LAB__addr_0x00403d19\n\t"
        "push               ebx\n\t"
        "push               ebp\n\t"
        "push               edi\n\t"
        "mov.s              edi, esi\n\t"
        "and                edi, 0x00008000\n\t"
        "%{disp8%} je         LAB__addr_0x00403c7a\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x08]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], eax\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403c82\n"
        "LAB__addr_0x00403c7a:\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], 0x00000000\n"
        "LAB__addr_0x00403c82:\n\t"
        "mov.s              ebp, esi\n\t"
        "and                ebp, 0x00040000\n\t"
        "%{disp8%} je         LAB__addr_0x00403ca9\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x00403c9d\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x08]\n\t"
        "mov                ebx, dword ptr [eax + edx * 0x1]\n\t"
        "add.s              eax, edx\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403cab\n"
        "LAB__addr_0x00403c9d:\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "xor.s              edx, edx\n\t"
        "mov                ebx, dword ptr [eax + edx * 0x1]\n\t"
        "add.s              eax, edx\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403cab\n"
        "LAB__addr_0x00403ca9:\n\t"
        "xor.s              ebx, ebx\n"
        "LAB__addr_0x00403cab:\n\t"
        "test               esi, 0x00080000\n\t"
        "%{disp8%} je         LAB__addr_0x00403d02\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x00403cbf\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "%{disp8%} mov        esi, dword ptr [eax + 0x08]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403cc1\n"
        "LAB__addr_0x00403cbf:\n\t"
        "xor.s              esi, esi\n"
        "LAB__addr_0x00403cc1:\n\t"
        "test               ebp, ebp\n\t"
        "%{disp8%} je         LAB__addr_0x00403cf4\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x00403cdf\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x08]\n\t"
        "add.s              eax, edx\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "add.s              eax, edx\n\t"
        "mov                edx, dword ptr [eax + esi * 0x1]\n\t"
        "add.s              eax, esi\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403d04\n"
        "LAB__addr_0x00403cdf:\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "xor.s              edx, edx\n\t"
        "add.s              eax, edx\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "add.s              eax, edx\n\t"
        "mov                edx, dword ptr [eax + esi * 0x1]\n\t"
        "add.s              eax, esi\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403d04\n"
        "LAB__addr_0x00403cf4:\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "xor.s              edx, edx\n\t"
        "add.s              eax, edx\n\t"
        "mov                edx, dword ptr [eax + esi * 0x1]\n\t"
        "add.s              eax, esi\n\t"
        "%{disp8%} jmp        LAB__addr_0x00403d04\n"
        "LAB__addr_0x00403d02:\n\t"
        "xor.s              edx, edx\n"
        "LAB__addr_0x00403d04:\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x48]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x10]\n\t"
        "add.s              eax, edx\n\t"
        "pop                edi\n\t"
        "add.s              eax, ebx\n\t"
        "pop                ebp\n\t"
        "add.s              eax, ecx\n\t"
        "mov                eax, dword ptr [eax]\n\t"
        "pop                ebx\n\t"
        "pop                esi\n\t"
        "pop                ecx\n\t"
        "ret\n"
        "LAB__addr_0x00403d19:\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi\n\t"
        "pop                ecx"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}
