#include "Villager.h"

const float villager_forester_num_days_in_year_0x0099a98c = 365.25f;
const float villager_forester_seconds_in_day_0x0099a990 = 86400.0f;

float villager_forester_seconds_in_year_0x00db9e14;

void __cdecl globl_ct_0x0075f440(void)
{
    asm volatile (
        "%{disp32%} mov cl, byte ptr [_DAT_00fac934]\n\t"
        "mov al, 0x01\n\t"
        "test al, cl\n\t"
        "%{disp8%} jne LAB__addr_0x0075f454\n\t"
        "or.s cl, al\n\t"
        "%{disp32%} mov byte ptr [_DAT_00fac934], cl\n"
        "LAB__addr_0x0075f454:\n\t"
        "%{disp32%} jmp _crt_global_destruction_register_0x0075f460"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

void __cdecl crt_global_destruction_register_0x0075f460(void)
{
    asm volatile (
        "push               0x00407870\n\t"
        "call               _atexit\n\t"
        "pop                ecx"
        ::: "eax", "ecx", "edx", "memory"
    );
}

extern void __cdecl FUN_0075f480__8VillagerFv(void) __attribute__((noinline));

void __cdecl globl_ct_0x0075f470(void)
{
    __attribute__((musttail)) return FUN_0075f480__8VillagerFv();
}

void __cdecl FUN_0075f480__8VillagerFv(void)
{
    asm volatile (
        "%{disp32%} fld  dword ptr [_villager_forester_seconds_in_day_0x0099a990]\n\t"
        "%{disp32%} fmul dword ptr [_villager_forester_num_days_in_year_0x0099a98c]\n\t"
        "%{disp32%} fstp dword ptr [_villager_forester_seconds_in_year_0x00db9e14]"
        ::: "memory"
    );
}

__attribute__((XOR32rr_REV, noinline))
bool32_t __fastcall CheckSatisfyWoodDesire__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "sub                esp, 0x14\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x08]\n\t"
        "push               eax\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x08]\n\t"
        "push               ecx\n\t"
        "push               0x0\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?DecideHowToGetWood@Villager@@QAEIHPAPAVBigForest@@PAPAVForest@@@Z\n\t"
        "dec                eax\n\t"
        "%{disp8%} je         LAB__addr_0x0075f504\n\t"
        "dec                eax\n\t"
        "%{disp8%} je         LAB__addr_0x0075f4dc\n\t"
        "dec                eax\n\t"
        "%{disp8%} je         LAB__addr_0x0075f4c9\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi\n\t"
        "add                esp, 0x14\n\t"
        "ret\n"
        "LAB__addr_0x0075f4c9:\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x08]\n\t"
        "push               0x31\n\t"
        "push               edx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?VillagerGotoForest@Villager@@QAEIPAVForest@@W4VILLAGER_STATES@@@Z\n\t"
        "pop                esi\n\t"
        "add                esp, 0x14\n\t"
        "ret\n"
        "LAB__addr_0x0075f4dc:\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x04]\n\t"
        "push               0x35\n\t"
        "push               esi\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x14]\n\t"
        "push               eax\n\t"
        "call               _jmp_addr_0x00439360\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x08]\n\t"
        "push               eax\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @SetupMoveToOnFootpath__6LivingFR16GameThingWithPosRC9MapCoordsUc@17\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x14\n\t"
        "ret\n"
        "LAB__addr_0x0075f504:\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GotoStoragePitForDropOff@Villager@@QAEIXZ\n\t"
        "pop                esi\n\t"
        "add                esp, 0x14\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((XOR32rr_REV))
uint32_t __fastcall DecideHowToGetWood__8VillagerFiPP9BigForestPP6Forest(struct Villager* this, const void* edx, int param_1, struct BigForest** param_2, struct Forest** param_3)
{
    asm volatile (
        "sub                esp, 0x1c\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], 0x00000000\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x1c], 0x00000000\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x20], 0x00000000\n\t"
        "call               ?GetStoragePit@Villager@@QAEPAVStoragePit@@XZ\n\t"
        "mov.s              edi, eax\n\t"
        "test               edi, edi\n\t"
        "%{disp32%} mov       eax, dword ptr [data_bytes + 0x3dc8e4]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], eax\n\t"
        "%{disp8%} je         LAB__addr_0x0075f582\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0xd4]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0075f582\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x08]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x104]\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], edx\n\t"
        "%{disp8%} mov        ecx, dword ptr [eax + 0x04]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x1c], ecx\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x08]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x20], edx\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "push               0x1\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x98]\n\t"
        "%{disp8%} jmp        LAB__addr_0x0075f5a7\n"
        "LAB__addr_0x0075f582:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x1\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x1c]\n\t"
        "push               ecx\n\t"
        "%{disp8%} lea        edx, dword ptr [esi + 0x14]\n\t"
        "push               edx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               ?GetTemporaryResourceStorePotOrPos@Town@@QAEPAXABUMapCoords@@AAU2@W4RESOURCE_TYPE@@@Z\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "push               0x1\n\t"
        "mov.s              ecx, eax\n\t"
        "call               dword ptr [edx + 0x98]\n"
        "LAB__addr_0x0075f5a7:\n\t"
        "mov.s              ecx, esi\n\t"
        "mov.s              edi, eax\n\t"
        "call               ?GetWoodCapacity@Villager@@QAEHXZ\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x28]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0075f5e2\n\t"
        "mov.s              ecx, esi\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], 0x3f000000\n\t"
        "call               ?GetWoodCapacity@Villager@@QAEHXZ\n\t"
        "movsx              eax, ax\n\t"
        "cmp.s              edi, eax\n\t"
        "%{disp8%} jbe        LAB__addr_0x0075f5d8\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x28], 0x3f800000\n\t"
        "%{disp8%} jmp        LAB__addr_0x0075f633\n"
        "LAB__addr_0x0075f5d8:\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x28], 0x00000000\n\t"
        "%{disp8%} jmp        LAB__addr_0x0075f633\n"
        "LAB__addr_0x0075f5e2:\n\t"
        "%{disp8%} mov        edi, dword ptr [esi + 0x28]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetWoodCapacity@Villager@@QAEHXZ\n\t"
        "%{disp32%} mov       edx, dword ptr [edi + 0x00000268]\n\t"
        "movsx              ecx, ax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x28], ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], edx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], 0x00000000\n\t"
        "%{disp8%} fild       dword ptr [esp + 0x28]\n\t"
        "%{disp32%} fadd      dword ptr [rdata_bytes + 0xf1100]\n\t"
        "%{disp8%} fild       qword ptr [esp + 0x08]\n\t"
        "%{disp32%} fadd      dword ptr [rdata_bytes + 0xf1100]\n\t"
        "fdivp              st(1), st\n\t"
        "%{disp32%} fsubr     dword ptr [_rdata_float1p0]\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x28]\n\t"
        "%{disp32%} fld       dword ptr [_rdata_float1p0]\n\t"
        "%{disp8%} fsub       dword ptr [esp + 0x28]\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x08]\n"
        "LAB__addr_0x0075f633:\n\t"
        "push               ebx\n\t"
        "%{disp8%} mov        ebx, dword ptr [esp + 0x18]\n\t"
        "push               ebx\n\t"
        "%{disp8%} lea        edi, dword ptr [esi + 0x14]\n\t"
        "push               edi\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x24]\n\t"
        "call               _GetDistanceInMetres__6GUtilsFRC9MapCoordsRC9MapCoords_2\n\t"
        "push               ecx\n\t"
        "fstp               dword ptr [esp]\n\t"
        "call               _GetDistanceModifier__6GUtilsFff@8\n\t"
        "%{disp8%} fmul       dword ptr [esp + 0x34]\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "add                esp, 0x08\n\t"
        "mov.s              ecx, esi\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x2c]\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0075f68f\n\t"
        "push               edi\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x0073ec10\n\t"
        "mov.s              esi, eax\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x0075f68f\n"
        "LAB__addr_0x0075f673:\n\t"
        "push               ebx\n\t"
        "push               edi\n\t"
        "%{disp8%} lea        ecx, dword ptr [esi + 0x14]\n\t"
        "call               _GetDistanceInMetres__6GUtilsFRC9MapCoordsRC9MapCoords_2\n\t"
        "push               ecx\n\t"
        "fstp               dword ptr [esp]\n\t"
        "call               _GetDistanceModifier__6GUtilsFff@8\n\t"
        "%{disp8%} fmul       dword ptr [esp + 0x14]\n\t"
        "add                esp, 0x08\n\t"
        "%{disp8%} jmp        LAB__addr_0x0075f6a7\n"
        "LAB__addr_0x0075f68f:\n\t"
        "push               0x0\n\t"
        "push               ebx\n\t"
        "push               edi\n\t"
        "call               _jmp_addr_0x0053a1a0\n\t"
        "mov.s              esi, eax\n\t"
        "add                esp, 0x0c\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} jne        LAB__addr_0x0075f673\n\t"
        "%{disp32%} fld       dword ptr [_rdata_float0p0]\n"
        "LAB__addr_0x0075f6a7:\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x2c]\n\t"
        "pop                ebx\n\t"
        "fcomp              st(1)\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp8%} jne        LAB__addr_0x0075f6c4\n\t"
        "pop                edi\n\t"
        "fstp               st(0)\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x1c\n\t"
        "ret                0x000c\n"
        "LAB__addr_0x0075f6c4:\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float0p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x40\n\t"
        "%{disp8%} jne        LAB__addr_0x0075f702\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x0075f702\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x38]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0075f6ef\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x2c]\n\t"
        "pop                edi\n\t"
        "mov                dword ptr [ecx], eax\n\t"
        "mov                eax, 0x00000002\n\t"
        "pop                esi\n\t"
        "add                esp, 0x1c\n\t"
        "ret                0x000c\n"
        "LAB__addr_0x0075f6ef:\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x30]\n\t"
        "pop                edi\n\t"
        "mov                dword ptr [edx], esi\n\t"
        "mov                eax, 0x00000003\n\t"
        "pop                esi\n\t"
        "add                esp, 0x1c\n\t"
        "ret                0x000c\n"
        "LAB__addr_0x0075f702:\n\t"
        "pop                edi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi\n\t"
        "add                esp, 0x1c\n\t"
        "ret                0x000c"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall ForesterGotoForest__8VillagerFv(struct Villager* this)
{
    __attribute__((musttail)) return CheckSatisfyWoodDesire__8VillagerFv(this);
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall VillagerGotoForest__8VillagerFP6Forest15VILLAGER_STATES(struct Villager* this, const void* edx, struct Forest* param_1, enum VILLAGER_STATES param_2)
{
    asm volatile (
        "sub                esp, 0x18\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "%{disp8%} mov        edi, dword ptr [esp + 0x24]\n\t"
        "mov.s              esi, ecx\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?GetForestCentreTree@Forest@@QAEPAVTree@@XZ\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], 0x00000000\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], 0x00000000\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], 0x00000000\n\t"
        "%{disp8%} je         LAB__addr_0x0075f770\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "push               esi\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x18]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, eax\n\t"
        "call               dword ptr [edx + 0x648]\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], edx\n\t"
        "%{disp8%} mov        ecx, dword ptr [eax + 0x04]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], ecx\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x08]\n\t"
        "%{disp8%} jmp        LAB__addr_0x0075f783\n"
        "LAB__addr_0x0075f770:\n\t"
        "add                edi, 0x14\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "%{disp8%} mov        ecx, dword ptr [edi + 0x04]\n\t"
        "%{disp8%} mov        edx, dword ptr [edi + 0x08]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], ecx\n"
        "LAB__addr_0x0075f783:\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x28]\n\t"
        "push               eax\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x0c]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, esi\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], edx\n\t"
        "call               @SetupMoveToWithHug__6LivingFRC9MapCoordsUc@13\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0075f7b8\n\t"
        "push               0x2f\n\t"
        "push               0x0\n\t"
        "%{disp32%} lea       ecx, dword ptr [esi + 0x0000008c]\n\t"
        "call               @SetState__12LivingActionFUlUc@16\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x18\n\t"
        "ret                0x0008\n"
        "LAB__addr_0x0075f7b8:\n\t"
        "pop                edi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi\n\t"
        "add                esp, 0x18\n\t"
        "ret                0x0008"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall ForesterMoveToForest__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "sub                esp, 0x44\n\t"
        "push               edi\n\t"
        "mov.s              edi, ecx\n\t"
        "call               ?MoveToPos@Living@@QAEHXZ\n\t"
        "cmp                eax, 0x07\n\t"
        "%{disp32%} jne       LAB__addr_0x0075f918\n\t"
        "cmp                byte ptr [edi + 0x5e], 0x02\n\t"
        "%{disp32%} jne       LAB__addr_0x0075f918\n\t"
        "push               ebx\n\t"
        "push               ebp\n\t"
        "xor.s              eax, eax\n\t"
        "push               esi\n\t"
        "%{disp8%} mov        word ptr [esp + 0x1c], -0x0200\n\t"
        "%{disp8%} mov        word ptr [esp + 0x1e], ax\n\t"
        "%{disp8%} mov        word ptr [esp + 0x20], 0x0200\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], 0x461c3c00\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], eax\n\t"
        "%{disp8%} lea        ebp, dword ptr [edi + 0x14]\n\t"
        "%{disp8%} lea        ebx, dword ptr [esp + 0x1c]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], 0x00000003\n"
        "LAB__addr_0x0075f821:\n\t"
        "%{disp8%} mov        ax, word ptr [edi + 0x5c]\n\t"
        "xor.s              ecx, ecx\n\t"
        "mov                cx, word ptr [ebx]\n\t"
        "add.s              cx, ax\n\t"
        "push               0x41200000\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x34]\n\t"
        "push               ecx\n\t"
        "push               edx\n\t"
        "call               _jmp_addr_0x0074d6a0\n\t"
        "add                esp, 0x0c\n\t"
        "push               eax\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x28]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, ebp\n\t"
        "call               @__pl__9MapCoordsCFRC9MapCoords@16\n\t"
        "push               0x0\n\t"
        "push               0x009d96e0\n\t"
        "push               0x009c7f50\n\t"
        "push               0x0\n\t"
        "push               0x0\n\t"
        "push               0x6\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x3c]\n\t"
        "call               @FindType__9MapCoordsCF11OBJECT_TYPEP6Object@16\n\t"
        "push               eax\n\t"
        "call               ___RTDynamicCast\n\t"
        "mov.s              esi, eax\n\t"
        "add                esp, 0x14\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x0075f8e3\n"
        "LAB__addr_0x0075f877:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x86c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0075f8ba\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x24]\n\t"
        "push               eax\n\t"
        "push               edi\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x44]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x648]\n\t"
        "push               eax\n\t"
        "call               ?GetDistanceInMetres@GUtils@@SAMABUMapCoords@@0@Z\n\t"
        "%{disp8%} fcom       dword ptr [esp + 0x18]\n\t"
        "add                esp, 0x08\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x0075f8b8\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x10]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], esi\n\t"
        "%{disp8%} jmp        LAB__addr_0x0075f8ba\n"
        "LAB__addr_0x0075f8b8:\n\t"
        "fstp               st(0)\n"
        "LAB__addr_0x0075f8ba:\n\t"
        "push               0x0\n\t"
        "push               0x009d96e0\n\t"
        "push               0x009c7f50\n\t"
        "push               0x0\n\t"
        "push               esi\n\t"
        "push               0x6\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x3c]\n\t"
        "call               @FindType__9MapCoordsCF11OBJECT_TYPEP6Object@16\n\t"
        "push               eax\n\t"
        "call               ___RTDynamicCast\n\t"
        "mov.s              esi, eax\n\t"
        "add                esp, 0x14\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} jne        LAB__addr_0x0075f877\n"
        "LAB__addr_0x0075f8e3:\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x14]\n\t"
        "add                ebx, 0x02\n\t"
        "dec                eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], eax\n\t"
        "%{disp32%} jne       LAB__addr_0x0075f821\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x18]\n\t"
        "test               ecx, ecx\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "pop                ebx\n\t"
        "%{disp8%} je         LAB__addr_0x0075f918\n\t"
        "mov                edx, dword ptr [ecx]\n\t"
        "push               0x31\n\t"
        "push               edi\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x44]\n\t"
        "push               eax\n\t"
        "call               dword ptr [edx + 0x648]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, edi\n\t"
        "call               @SetupMoveToWithHug__6LivingFRC9MapCoordsUc@13\n"
        "LAB__addr_0x0075f918:\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                edi\n\t"
        "add                esp, 0x44\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall ForesterArrivesAtForest__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "sub                esp, 0x10\n\t"
        "push               esi\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x04]\n\t"
        "mov.s              esi, ecx\n\t"
        "push               eax\n\t"
        "call               ?FindTreeNearVillager@Villager@@QAEIPAPAVTree@@@Z\n\t"
        "sub                eax, 0x00\n\t"
        "%{disp8%} je         LAB__addr_0x0075f9a8\n\t"
        "dec                eax\n\t"
        "%{disp8%} je         LAB__addr_0x0075f97d\n\t"
        "sub                eax, 0x09\n\t"
        "%{disp8%} jne        LAB__addr_0x0075f9c8\n\t"
        "%{disp8%} mov        cx, word ptr [esi + 0x5c]\n\t"
        "sub                cx, 0x0124\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000118], 0x00000000\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @SetGameAngle__13MobileWallHugFUs@10\n\t"
        "push               0x1\n\t"
        "push               0x32\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?PlayAnimThenSetState@Living@@QAEXEK@Z\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x10\n\t"
        "ret\n"
        "LAB__addr_0x0075f97d:\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x04]\n\t"
        "mov                edx, dword ptr [ecx]\n\t"
        "push               esi\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x0c]\n\t"
        "push               eax\n\t"
        "call               dword ptr [edx + 0x648]\n\t"
        "push               0x31\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x0c]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @SetupMoveToWithHug__6LivingFRC9MapCoordsUc@13\n\t"
        "neg                eax\n\t"
        "sbb.s              eax, eax\n\t"
        "neg                eax\n\t"
        "pop                esi\n\t"
        "add                esp, 0x10\n\t"
        "ret\n"
        "LAB__addr_0x0075f9a8:\n\t"
        "push               0x1\n\t"
        "%{disp8%} lea        edx, dword ptr [esi + 0x14]\n\t"
        "push               0x42480000\n\t"
        "push               edx\n\t"
        "call               _jmp_addr_0x0053a1a0\n\t"
        "add                esp, 0x0c\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0075f9c8\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "push               0x0\n\t"
        "mov.s              ecx, eax\n\t"
        "call               dword ptr [edx + 0xc]\n"
        "LAB__addr_0x0075f9c8:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x34\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x8e8]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?ForesterFinishedForestering@Villager@@QAEIXZ\n\t"
        "pop                esi\n\t"
        "add                esp, 0x10\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall ArrivesAtBigForest__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "sub                esp, 0x0c\n\t"
        "push               ebx\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "mov.s              esi, ecx\n\t"
        "call               ?GetWoodCapacity@Villager@@QAEHXZ\n\t"
        "movsx              ebx, ax\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0075fa68\n\t"
        "test               ebx, ebx\n\t"
        "%{disp8%} je         LAB__addr_0x0075fa68\n\t"
        "%{disp8%} lea        ecx, dword ptr [esi + 0x14]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x0073ec10\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0075fa68\n\t"
        "%{disp8%} mov        edi, dword ptr [eax + 0x38]\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x0075fa68\n\t"
        "push               esi\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x10]\n\t"
        "push               edx\n\t"
        "mov.s              ecx, edi\n\t"
        "call               _jmp_addr_0x00439360\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x0\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x10]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x85c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0075fa83\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "push               0x0\n\t"
        "push               0x0\n\t"
        "push               ebx\n\t"
        "push               0x1\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0xa0]\n\t"
        "mov.s              ebx, eax\n\t"
        "test               ebx, ebx\n\t"
        "%{disp8%} je         LAB__addr_0x0075fa68\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x820]\n\t"
        "push               eax\n\t"
        "push               ebx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?PickupWood@Villager@@QAEXFE@Z\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GotWoodDecideWhatToDo@Villager@@QAEIXZ\n"
        "LAB__addr_0x0075fa68:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               0x000000a3\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x8e8]\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x0c\n\t"
        "ret\n"
        "LAB__addr_0x0075fa83:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0xb04]\n\t"
        "mov.s              ecx, esi\n\t"
        "push               eax\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x10]\n\t"
        "push               eax\n\t"
        "call               @SetupMoveToWithHug__6LivingFRC9MapCoordsUc@13\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x0c\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall ArrivesAtBigForestForBuilding__8VillagerFv(struct Villager* this)
{
    return 1;
}

bool32_t __fastcall ForesterChopsTree__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "push               ecx\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x00000118]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0075fb03\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x04]\n\t"
        "push               eax\n\t"
        "call               ?FindTreeNearVillager@Villager@@QAEIPAPAVTree@@@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0075fb03\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x04]\n\t"
        "push               esi\n\t"
        "push               ecx\n\t"
        "call               _jmp_addr_0x005116a0\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x0c]\n\t"
        "add                esp, 0x08\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000118], eax\n\t"
        "mov                edx, dword ptr [ecx]\n\t"
        "push               0x0\n\t"
        "call               dword ptr [edx + 0xc]\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "pop                ecx\n\t"
        "ret\n"
        "LAB__addr_0x0075fb03:\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x00000118]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x0075fb1d\n\t"
        "test               byte ptr [ecx + 0x24], 0x40\n\t"
        "%{disp8%} je         LAB__addr_0x0075fb1d\n\t"
        "mov                eax, dword ptr [ecx]\n\t"
        "call               dword ptr [eax + 0x2c]\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x0075fb33\n"
        "LAB__addr_0x0075fb1d:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               0x34\n\t"
        "mov.s              ecx, esi\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000118], 0x00000000\n\t"
        "call               dword ptr [edx + 0x8e8]\n"
        "LAB__addr_0x0075fb33:\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "pop                ecx\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall ForesterChopsTreeForBuilding__8VillagerFv(struct Villager* this)
{
    void* dummy;
    asm volatile (
        "mov eax, dword ptr [ecx]\n\t"
        "push 0x000000a3\n\t"
        "call dword ptr [eax + 0x8e8]"
        : "=c"(dummy) : "c"(this) : "eax", "edx", "memory"
    );
    return 1;
}

bool32_t __fastcall ForesterFinishedForestering__8VillagerFv(struct Villager* this)
{
    bool32_t result;
    asm volatile (
        "cmp                word ptr [ecx + 0x000000f6], 0x00\n\t"
        "%{disp8%} jle        LAB__addr_0x0075fb6f\n\t"
        "%{disp32%} jmp       ?GotWoodDecideWhatToDo@Villager@@QAEIXZ\n\t"
        "LAB__addr_0x0075fb6f:\n\t"
        "mov                eax, dword ptr [ecx]\n\t"
        "push               0x000000a3\n\t"
        "call               dword ptr [eax + 0x8e8]\n\t"
        "mov                eax, 0x00000001"
        : "=a"(result) : "c"(this) : "edx", "memory"
    );
    return result;
}

bool32_t __fastcall TakeWoodFromTreeForBuilding__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "%{disp32%} jmp       ?TakeWoodFromTree@Villager@@QAEIXZ"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

extern bool32_t __fastcall TakeWoodFromPot__8VillagerFv(struct Villager* this) __attribute__((noinline));

bool32_t __fastcall TakeWoodFromPotForBuilding__8VillagerFv(struct Villager* this)
{
    __attribute__((musttail)) return TakeWoodFromPot__8VillagerFv(this);
}

bool32_t __fastcall TakeWoodFromPot__8VillagerFv(struct Villager* this)
{
    return 1;
}

bool32_t __fastcall TakeWoodFromTree__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "push               ecx\n\t"
        "push               esi\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x04]\n\t"
        "mov.s              esi, ecx\n\t"
        "push               eax\n\t"
        "call               ?FindTreeNearVillager@Villager@@QAEIPAPAVTree@@@Z\n\t"
        "test               eax, eax\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "%{disp8%} je         LAB__addr_0x0075fc0c\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0075fbf6\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "%{disp8%} lea        eax, dword ptr [esi + 0x14]\n\t"
        "push               eax\n\t"
        "push               0x3f000000\n\t"
        "push               0x1\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x004c80f0\n"
        "LAB__addr_0x0075fbf6:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x31\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x8e8]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?ForesterArrivesAtForest@Villager@@QAEIXZ\n\t"
        "pop                esi\n\t"
        "pop                ecx\n\t"
        "ret\n"
        "LAB__addr_0x0075fc0c:\n\t"
        "push               0x000000a3\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x8e8]\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "pop                ecx\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall GotWoodDecideWhatToDo__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "cmp                word ptr [esi + 0x000000f6], 0x00\n\t"
        "%{disp32%} jbe       LAB__addr_0x0075fcdc\n\t"
        "xor.s              eax, eax\n\t"
        "%{disp32%} mov       ax, word ptr [esi + 0x000000e0]\n\t"
        "shr                eax, 9\n\t"
        "test               al, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x0075fc6c\n\t"
        "xor.s              eax, eax\n\t"
        "%{disp32%} mov       al, byte ptr [esi + 0x000000f2]\n\t"
        "%{disp32%} lea       ecx, dword ptr [eax * 0x8 + 0x00000000]\n\t"
        "sub.s              ecx, eax\n\t"
        "cmp                dword ptr [ecx * 0x4 + 0x0099a204], 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x0075fcdc\n"
        "LAB__addr_0x0075fc6c:\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x000000fc]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0075fcbe\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0075fcbe\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x000000fc]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, eax\n\t"
        "call               ?IsBuildingSiteValid@Town@@QAEIPAVBuildingSite@@@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0075fcbe\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x000000fc]\n\t"
        "call               _jmp_addr_0x0043bc60\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0075fcab\n\t"
        "cmp                byte ptr [esi + 0x000000f2], 0x04\n\t"
        "%{disp8%} jne        LAB__addr_0x0075fcbe\n"
        "LAB__addr_0x0075fcab:\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x000000fc]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GotoBuildingSite@Villager@@QAEIPAVBuildingSite@@@Z\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x0075fceb\n"
        "LAB__addr_0x0075fcbe:\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?CheckNeededForBuilding@Villager@@QAEIXZ\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0075fceb\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x1f\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x8e8]\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x0075fcdc:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               0x000000a3\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x8e8]\n"
        "LAB__addr_0x0075fceb:\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall FindTreeNearVillager__8VillagerFPP4Tree(struct Villager* this, const void* edx, struct Tree* * param_1)
{
    asm volatile (
        "sub                esp, 0x28\n\t"
        "push               ebx\n\t"
        "push               ebp\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "mov.s              edi, ecx\n\t"
        "%{disp8%} lea        ebp, dword ptr [edi + 0x14]\n\t"
        "mov.s              eax, ebp\n\t"
        "mov                ecx, dword ptr [eax]\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x04]\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x08]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x28], eax\n\t"
        "mov                eax, 0x00000001\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], 0x47c34f80\n\t"
        "xor.s              ebx, ebx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x20], ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x24], edx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x1c], eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], 0x00000009\n"
        "LAB__addr_0x0075fd41:\n\t"
        "push               0x0\n\t"
        "push               0x009d96e0\n\t"
        "push               0x009c7f50\n\t"
        "push               0x0\n\t"
        "push               0x0\n\t"
        "push               0x6\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x38]\n\t"
        "call               @FindType__9MapCoordsCF11OBJECT_TYPEP6Object@16\n\t"
        "push               eax\n\t"
        "call               ___RTDynamicCast\n\t"
        "mov.s              esi, eax\n\t"
        "add                esp, 0x14\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x0075fda4\n\t"
        "test               byte ptr [esi + 0x25], 0x40\n\t"
        "%{disp8%} jne        LAB__addr_0x0075fda4\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x30]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x648]\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x2c]\n\t"
        "push               ecx\n\t"
        "push               ebp\n\t"
        "call               ?GetDistanceInMetres@GUtils@@SAMABUMapCoords@@0@Z\n\t"
        "%{disp8%} fcom       dword ptr [esp + 0x18]\n\t"
        "add                esp, 0x08\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x0075fda2\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x10]\n\t"
        "mov.s              ebx, esi\n\t"
        "%{disp8%} jmp        LAB__addr_0x0075fda4\n"
        "LAB__addr_0x0075fda2:\n\t"
        "fstp               st(0)\n"
        "LAB__addr_0x0075fda4:\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x18]\n\t"
        "push               edx\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x20]\n\t"
        "push               eax\n\t"
        "call               ?Spiral@GUtils@@SAPBUJustMapXZ@@AAJ0@Z\n\t"
        "add                esp, 0x08\n\t"
        "push               eax\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x24]\n\t"
        "call               @__apl__9MapCoordsFRC9JustMapXZ@12\n\t"
        "dec                dword ptr [esp + 0x14]\n\t"
        "%{disp32%} jne       LAB__addr_0x0075fd41\n\t"
        "test               ebx, ebx\n\t"
        "%{disp8%} je         LAB__addr_0x0075fe05\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x3c]\n\t"
        "mov                dword ptr [ecx], ebx\n\t"
        "mov                edx, dword ptr [ebx]\n\t"
        "push               edi\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x30]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, ebx\n\t"
        "call               dword ptr [edx + 0x648]\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x2c]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x6b4]\n\t"
        "neg                eax\n\t"
        "pop                edi\n\t"
        "sbb.s              eax, eax\n\t"
        "pop                esi\n\t"
        "and                eax, 0x09\n\t"
        "pop                ebp\n\t"
        "inc                eax\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x28\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x0075fe05:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "xor.s              eax, eax\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x28\n\t"
        "ret                0x0004"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall ExitForesting__8VillagerFUc(struct Villager* this, const void* edx, unsigned char param_1)
{
    this->target_thing = NULL;
    return 1;
}
