#include "Villager.h"

const float villager_worshipper_num_days_in_year_0x0099aa5c = 365.25f;
const float villager_worshipper_seconds_in_day_0x0099aa60 = 86400.0f;

uint32_t villager_worshipper_uint_0x00dcb16c;
float villager_worshipper_seconds_in_year_0x00dcb170;

void __cdecl globl_ct_0x0076b9e0(void)
{
    asm volatile (
        "%{disp32%} mov cl, byte ptr [_DAT_00fac934]\n\t"
        "mov al, 0x01\n\t"
        "test al, cl\n\t"
        "%{disp8%} jne LAB__addr_0x0076b9f4\n\t"
        "or.s cl, al\n\t"
        "%{disp32%} mov byte ptr [_DAT_00fac934], cl\n"
        "LAB__addr_0x0076b9f4:\n\t"
        "%{disp32%} jmp _crt_global_destruction_register_0x0076ba00"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

void __cdecl crt_global_destruction_register_0x0076ba00(void)
{
    asm volatile (
        "push               0x00407870\n\t"
        "call               _atexit\n\t"
        "pop                ecx"
        ::: "eax", "ecx", "edx", "memory"
    );
}

extern void __cdecl FUN_0076ba20__8VillagerFv(void) __attribute__((noinline));

void __cdecl globl_ct_0x0076ba10(void)
{
    __attribute__((musttail)) return FUN_0076ba20__8VillagerFv();
}

void __cdecl FUN_0076ba20__8VillagerFv(void)
{
    asm volatile (
        "%{disp32%} fld  dword ptr [_villager_worshipper_seconds_in_day_0x0099aa60]\n\t"
        "%{disp32%} fmul dword ptr [_villager_worshipper_num_days_in_year_0x0099aa5c]\n\t"
        "%{disp32%} fstp dword ptr [_villager_worshipper_seconds_in_year_0x00dcb170]"
        ::: "memory"
    );
}

extern void __cdecl FUN_0076ba50__8VillagerFv(void) __attribute__((noinline));

void __cdecl globl_ct_0x0076ba40(void)
{
    __attribute__((musttail)) return FUN_0076ba50__8VillagerFv();
}

void __cdecl FUN_0076ba50__8VillagerFv(void)
{
    villager_worshipper_uint_0x00dcb16c = 0xffffffff;
}

__attribute__((XOR32rr_REV))
float __fastcall CheckNeededForWorship__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "push               ecx\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "test               byte ptr [esi + 0x000000e0], 0x02\n\t"
        "%{disp8%} je         LAB__addr_0x0076ba8e\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?StartWorshippingAtWorshipSite@Villager@@QAEIXZ\n\t"
        "mov.s              edi, eax\n\t"
        "cmp                edi, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x0076ba88\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?RemoveVillagerFromWorshipSite@Villager@@QAEIXZ\n"
        "LAB__addr_0x0076ba88:\n\t"
        "mov.s              eax, edi\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ecx\n\t"
        "ret\n"
        "LAB__addr_0x0076ba8e:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "mov.s              ecx, eax\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x0076bad7\n\t"
        "%{disp32%} fld       dword ptr [ecx + 0x000005c0]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float0p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x40\n\t"
        "%{disp8%} jne        LAB__addr_0x0076bad7\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x04]\n\t"
        "push               eax\n\t"
        "push               0x1\n\t"
        "push               0x1\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], 0x00000001\n\t"
        "call               ?GetWorshipersNeeded@Town@@QAEHHHPAH@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jle        LAB__addr_0x0076bad7\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x04]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?CheckWorshipActivity@Villager@@QAEMH@Z\n\t"
        "pop                esi\n\t"
        "pop                ecx\n\t"
        "ret\n"
        "LAB__addr_0x0076bad7:\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi\n\t"
        "pop                ecx\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((XOR32rr_REV))
float __fastcall CheckWorshipActivity__8VillagerFi(struct Villager* this, const void* edx, int param_1)
{
    asm volatile (
        "push               ecx\n\t"
        "push               ebx\n\t"
        "push               ebp\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "xor.s              ebp, ebp\n\t"
        "push               edi\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], ebp\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "mov.s              edi, eax\n\t"
        "call               dword ptr [edx + 0x30c]\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x0076bc0d\n\t"
        "cmp.s              edi, ebp\n\t"
        "%{disp32%} je        LAB__addr_0x0076bc0d\n\t"
        "%{disp32%} mov       ecx, dword ptr [edi + 0x000009a4]\n\t"
        "cmp.s              ecx, ebp\n\t"
        "%{disp32%} je        LAB__addr_0x0076bc0d\n\t"
        "mov                eax, dword ptr [ecx]\n\t"
        "call               dword ptr [eax + 0x2c]\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp32%} jne       LAB__addr_0x0076bc0d\n\t"
        "%{disp32%} mov       ecx, dword ptr [edi + 0x000009a4]\n\t"
        "mov                edx, dword ptr [ecx]\n\t"
        "call               dword ptr [edx + 0x890]\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp32%} jne       LAB__addr_0x0076bc0d\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x30c]\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "mov.s              ebx, eax\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "mov.s              edi, eax\n\t"
        "mov                eax, dword ptr [ebx]\n\t"
        "mov.s              ecx, ebx\n\t"
        "call               dword ptr [eax + 0x1c]\n\t"
        "cmp.s              eax, edi\n\t"
        "%{disp32%} jne       LAB__addr_0x0076bc0d\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x10]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?CanIGetToTheWorshipSite@Villager@@QAEIAAPAVMagicTeleport@@@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0076bb81\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x18]\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} jne       LAB__addr_0x0076bc0d\n"
        "LAB__addr_0x0076bb81:\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?CheckNeededForWorshipSiteBuilding@Villager@@QAEIXZ\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x0076bb99\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GotoWorshipSiteForWorship@Villager@@QAEIXZ\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x0076bc0d\n"
        "LAB__addr_0x0076bb99:\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x10]\n\t"
        "test               eax, eax\n\t"
        "mov                ebp, 0x00000001\n\t"
        "%{disp8%} je         LAB__addr_0x0076bc0d\n\t"
        "push               0x14\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @SetReactionDoneWhen__6LivingF8REACTION@12\n\t"
        "%{disp32%} mov       edi, dword ptr [esi + 0x00000094]\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x0076bbf5\n\t"
        "%{disp8%} mov        edx, dword ptr [edi + 0x18]\n\t"
        "mov.s              eax, edx\n\t"
        "xor.s              ecx, ecx\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076bbf5\n"
        "LAB__addr_0x0076bbc4:\n\t"
        "cmp                dword ptr [eax], esi\n\t"
        "%{disp8%} je         LAB__addr_0x0076bbd3\n\t"
        "mov.s              ecx, eax\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x04]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0076bbc4\n\t"
        "%{disp8%} jmp        LAB__addr_0x0076bbf5\n"
        "LAB__addr_0x0076bbd3:\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} jne        LAB__addr_0x0076bbdf\n\t"
        "%{disp8%} mov        edx, dword ptr [edx + 0x04]\n\t"
        "%{disp8%} mov        dword ptr [edi + 0x18], edx\n\t"
        "%{disp8%} jmp        LAB__addr_0x0076bbe5\n"
        "LAB__addr_0x0076bbdf:\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x04]\n\t"
        "%{disp8%} mov        dword ptr [ecx + 0x04], edx\n"
        "LAB__addr_0x0076bbe5:\n\t"
        "push               eax\n\t"
        "call               ??3@YAXPAX@Z\n\t"
        "%{disp8%} mov        eax, dword ptr [edi + 0x1c]\n\t"
        "add                esp, 0x04\n\t"
        "dec                eax\n\t"
        "%{disp8%} mov        dword ptr [edi + 0x1c], eax\n"
        "LAB__addr_0x0076bbf5:\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x10]\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x00000094]\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               ecx\n\t"
        "push               eax\n\t"
        "push               0x14\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x994]\n"
        "LAB__addr_0x0076bc0d:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "mov.s              eax, ebp\n\t"
        "pop                ebp\n\t"
        "pop                ebx\n\t"
        "pop                ecx\n\t"
        "ret                0x0004"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall CanIGetToTheWorshipSite__8VillagerFRP13MagicTeleport(struct Villager* this, const void* edx, struct MagicTeleport* * param_1)
{
    asm volatile (
        "push               ecx\n\t"
        "push               ebx\n\t"
        "push               ebp\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "mov                ebx, 0x00000001\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "mov.s              edi, eax\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x0076bcaa\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x30c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076bcaa\n\t"
        "%{disp8%} mov        ecx, dword ptr [edi + 0x28]\n\t"
        "%{disp8%} lea        ebx, dword ptr [eax + 0x14]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], ecx\n\t"
        "%{disp8%} lea        ebp, dword ptr [esi + 0x14]\n\t"
        "push               ebx\n\t"
        "mov.s              ecx, ebp\n\t"
        "call               _GetDistanceInMetres__6GUtilsFRC9MapCoordsRC9MapCoords_2\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x10]\n\t"
        "%{disp32%} fcomp     dword ptr [edx + 0x00000148]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp8%} jne        LAB__addr_0x0076bc93\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x1c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076bc93\n\t"
        "%{disp8%} mov        edi, dword ptr [edi + 0x28]\n\t"
        "%{disp32%} mov       ecx, dword ptr [edi + 0x00000148]\n\t"
        "push               ecx\n\t"
        "push               ebx\n\t"
        "push               ebp\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x0064d6b0\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076bca0\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x18]\n\t"
        "mov                dword ptr [edx], eax\n"
        "LAB__addr_0x0076bc93:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebx\n\t"
        "pop                ecx\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x0076bca0:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "xor.s              eax, eax\n\t"
        "pop                ebx\n\t"
        "pop                ecx\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x0076bcaa:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "mov.s              eax, ebx\n\t"
        "pop                ebx\n\t"
        "pop                ecx\n\t"
        "ret                0x0004"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall GotoWorshipSiteForWorship__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "sub                esp, 0x0c\n\t"
        "push               ebx\n\t"
        "push               ebp\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "call               dword ptr [eax + 0x30c]\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "mov.s              edi, eax\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "xor.s              ebx, ebx\n\t"
        "test               edi, edi\n\t"
        "mov.s              ebp, eax\n\t"
        "%{disp32%} je        LAB__addr_0x0076bd67\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x890]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076bd67\n\t"
        "%{disp32%} mov       eax, dword ptr [edi + 0x000000a0]\n\t"
        "%{disp32%} inc       dword ptr [eax + 0x00000114]\n\t"
        "or                 byte ptr [esi + 0xe0], 0x10\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "push               esi\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x6c4]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float0p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp8%} jne        LAB__addr_0x0076bd4a\n\t"
        "xor.s              eax, eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], eax\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x10]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, edi\n\t"
        "call               _jmp_addr_0x0077ceb0\n\t"
        "push               0x3b\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x14]\n\t"
        "push               ecx\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @SetupMoveToOnFootpath__6LivingFR16GameThingWithPosRC9MapCoordsUc@17\n\t"
        "%{disp8%} jmp        LAB__addr_0x0076bd56\n"
        "LAB__addr_0x0076bd4a:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               0x3b\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x8e8]\n"
        "LAB__addr_0x0076bd56:\n\t"
        "test               ebp, ebp\n\t"
        "%{disp8%} je         LAB__addr_0x0076bd62\n\t"
        "push               esi\n\t"
        "mov.s              ecx, ebp\n\t"
        "call               _jmp_addr_0x0073e300\n"
        "LAB__addr_0x0076bd62:\n\t"
        "mov                ebx, 0x00000001\n"
        "LAB__addr_0x0076bd67:\n\t"
        "cmp                byte ptr [esi + 0x000000f2], 0x0b\n\t"
        "%{disp8%} jne        LAB__addr_0x0076bd8d\n\t"
        "push               0x0\n\t"
        "push               0x0\n\t"
        "push               0x0\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?SetVillagerDisciple@Villager@@QAEIPAVGameThing@@W4VILLAGER_DISCIPLE@@H@Z\n\t"
        "test               ebp, ebp\n\t"
        "%{disp8%} je         LAB__addr_0x0076bd8d\n\t"
        "cmp                ebx, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x0076bd8d\n\t"
        "mov.s              ecx, ebp\n\t"
        "call               _jmp_addr_0x0073c650\n"
        "LAB__addr_0x0076bd8d:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "mov.s              eax, ebx\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x0c\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall SetGotoWorshipSpeed__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "push               ecx\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x28]\n\t"
        "%{disp32%} fild      dword ptr [eax + 0x00000118]\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x04]\n\t"
        "call               dword ptr [edx + 0x30c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076bdea\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x30c]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x0077c100\n\t"
        "%{disp32%} fadd      dword ptr [_rdata_float1p0]\n\t"
        "push               0x1\n\t"
        "%{disp8%} fmul       dword ptr [esp + 0x08]\n\t"
        "call               _jmp_addr_0x007a1400\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?SetSpeed@Villager@@QAEXJH@Z\n\t"
        "pop                esi\n\t"
        "pop                ecx\n\t"
        "ret\n"
        "LAB__addr_0x0076bdea:\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x04]\n\t"
        "push               0x1\n\t"
        "call               _jmp_addr_0x007a1400\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?SetSpeed@Villager@@QAEXJH@Z\n\t"
        "pop                esi\n\t"
        "pop                ecx\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall ArrivesAtWorshipSiteForWorship__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "sub                esp, 0x0c\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "call               dword ptr [eax + 0x30c]\n\t"
        "mov.s              edi, eax\n\t"
        "xor.s              eax, eax\n\t"
        "cmp.s              edi, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0076be27\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x8c8]\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "add                esp, 0x0c\n\t"
        "ret\n"
        "LAB__addr_0x0076be27:\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], eax\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x08]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, edi\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], 0x00000000\n\t"
        "call               _jmp_addr_0x0077ceb0\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x08]\n\t"
        "push               ecx\n\t"
        "%{disp8%} lea        edx, dword ptr [esi + 0x14]\n\t"
        "push               edx\n\t"
        "call               _jmp_addr_0x0074cd50\n\t"
        "%{disp32%} fcomp     dword ptr [rdata_bytes + 0x2414]\n\t"
        "add                esp, 0x08\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x0076be9a\n\t"
        "%{disp32%} mov       ecx, dword ptr [edi + 0x000000a0]\n\t"
        "%{disp32%} mov       edx, dword ptr [ecx + 0x00000090]\n\t"
        "%{disp8%} mov        eax, dword ptr [edi + 0x28]\n\t"
        "cmp                edx, dword ptr [eax + 0x0000014c]\n\t"
        "mov.s              ecx, esi\n\t"
        "%{disp8%} jae        LAB__addr_0x0076be8a\n\t"
        "call               ?StartWorshippingAtWorshipSite@Villager@@QAEIXZ\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x0c\n\t"
        "ret\n"
        "LAB__addr_0x0076be8a:\n\t"
        "call               ?StartHidingAtWorshipSite@Villager@@QAEIXZ\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x0c\n\t"
        "ret\n"
        "LAB__addr_0x0076be9a:\n\t"
        "push               0x3b\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x0c]\n\t"
        "push               eax\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @SetupMoveToOnFootpath__6LivingFR16GameThingWithPosRC9MapCoordsUc@17\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x0c\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall CheckVillagerGoBackToTownFromWorship__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "mov.s              edi, eax\n\t"
        "test               edi, edi\n\t"
        "%{disp32%} je        LAB__addr_0x0076bf85\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x30c]\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x0076bf6e\n\t"
        "%{disp32%} mov       ecx, dword ptr [edi + 0x000009a4]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x0076bf6e\n\t"
        "mov                eax, dword ptr [ecx]\n\t"
        "call               dword ptr [eax + 0x2c]\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x0076bf6e\n\t"
        "%{disp32%} mov       ecx, dword ptr [edi + 0x000009a4]\n\t"
        "mov                edx, dword ptr [ecx]\n\t"
        "call               dword ptr [edx + 0x890]\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x0076bf6e\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               ebx\n\t"
        "push               ebp\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x30c]\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "mov.s              ebx, eax\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "mov.s              ebp, eax\n\t"
        "mov                eax, dword ptr [ebx]\n\t"
        "mov.s              ecx, ebx\n\t"
        "call               dword ptr [eax + 0x1c]\n\t"
        "cmp.s              eax, ebp\n\t"
        "pop                ebp\n\t"
        "pop                ebx\n\t"
        "%{disp8%} jne        LAB__addr_0x0076bf6e\n\t"
        "push               0x0\n\t"
        "push               0x0\n\t"
        "push               0x0\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?GetWorshipersNeeded@Town@@QAEHHHPAH@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jge        LAB__addr_0x0076bf85\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               esi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x30c]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x0077e0a0\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076bf85\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x000000f8\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x8e8]\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x0076bf85\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x0076bf6e:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               0x000000a3\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x8e8]\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x0076bf85:\n\t"
        "pop                edi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall CheckNeededForSupplyWorship__8VillagerFv(struct Villager* this)
{
    void* dummy;
    asm volatile (
        "mov eax, dword ptr [ecx]\n\t"
        "call dword ptr [eax + 0x30c]"
        : "=c"(dummy) : "c"(this) : "eax", "edx", "memory"
    );
    return 0;
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall GotoStoragePitForWorshipSupplies__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "sub                esp, 0x0c\n\t"
        "push               ebx\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "mov.s              esi, ecx\n\t"
        "call               ?GetStoragePit@Villager@@QAEPAVStoragePit@@XZ\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x0076c068\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetStoragePit@Villager@@QAEPAVStoragePit@@XZ\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               dword ptr [edx + 0xd4]\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x0076c068\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x30c]\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x0076c068\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "movsx              ebx, word ptr [esi + 0x000000f4]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x0073c950\n\t"
        "mov.s              ecx, esi\n\t"
        "mov.s              edi, eax\n\t"
        "call               ?GetStoragePit@Villager@@QAEPAVStoragePit@@XZ\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "push               0x0\n\t"
        "mov.s              ecx, eax\n\t"
        "call               dword ptr [edx + 0x98]\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x0076c068\n\t"
        "cmp.s              ebx, edi\n\t"
        "%{disp8%} ja         LAB__addr_0x0076c05a\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x28]\n\t"
        "cmp                ebx, dword ptr [ecx + 0x00000264]\n\t"
        "%{disp8%} je         LAB__addr_0x0076c05a\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076c068\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetStoragePit@Villager@@QAEPAVStoragePit@@XZ\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "push               0x2b\n\t"
        "push               0x0\n\t"
        "push               esi\n\t"
        "push               0x0\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x1c]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, eax\n\t"
        "call               dword ptr [edx + 0x8d4]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetStoragePit@Villager@@QAEPAVStoragePit@@XZ\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @SetupMoveToOnFootpath__6LivingFR16GameThingWithPosRC9MapCoordsUc@17\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x0c\n\t"
        "ret\n"
        "LAB__addr_0x0076c05a:\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GotoWorshipSiteWithSupplies@Villager@@QAEIXZ\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x0c\n\t"
        "ret\n"
        "LAB__addr_0x0076c068:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x0c\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall ArrivesAtStoragePitForWorshipSupplies__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "call               dword ptr [eax + 0x30c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076c0e7\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x0073c950\n\t"
        "mov.s              edi, eax\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x0076c0e7\n\t"
        "movsx              eax, word ptr [esi + 0x000000f4]\n\t"
        "cmp.s              eax, edi\n\t"
        "mov.s              ecx, esi\n\t"
        "%{disp8%} jl         LAB__addr_0x0076c0b9\n\t"
        "call               ?GotoWorshipSiteWithSupplies@Villager@@QAEIXZ\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x0076c0b9:\n\t"
        "call               ?GetFoodCapacity@Villager@@QAEHXZ\n\t"
        "movsx              ecx, ax\n\t"
        "cmp.s              ecx, edi\n\t"
        "%{disp8%} jge        LAB__addr_0x0076c0cf\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetFoodCapacity@Villager@@QAEHXZ\n\t"
        "movsx              edi, ax\n"
        "LAB__addr_0x0076c0cf:\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} jle        LAB__addr_0x0076c0e7\n\t"
        "push               0x000000a3\n\t"
        "push               0x0\n\t"
        "push               edi\n\t"
        "push               0x0\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?ArrivesAtStoragePitForResource@Villager@@QAEIW4RESOURCE_TYPE@@KW4VILLAGER_STATES@@1@Z\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x0076c0e7:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x8c8]\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall GotoWorshipSiteWithSupplies__8VillagerFv(struct Villager* this)
{
    return 0;
}

bool32_t __fastcall MoveToWorshipSiteWithSupplies__8VillagerFv(struct Villager* this)
{
    return 1;
}

bool32_t __fastcall ExitMoveToWorshipSiteWithSupplies__8VillagerFUc(struct Villager* this, const void* edx, unsigned char param_1)
{
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x08]\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "and                ecx, 0x000000ff\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x96c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c163\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x30c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076c163\n\t"
        "movsx              eax, word ptr [esi + 0x000000f4]\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x30c]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x0077c4d0\n"
        "LAB__addr_0x0076c163:\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "ret                0x0004"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall ExitMoveToWorshipSite__8VillagerFUc(struct Villager* this, const void* edx, unsigned char param_1)
{
    asm volatile (
        "push               esi\n\t"
        "%{disp8%} mov        esi, dword ptr [esp + 0x08]\n\t"
        "push               edi\n\t"
        "mov.s              edi, ecx\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "and                esi, 0x000000ff\n\t"
        "push               esi\n\t"
        "call               dword ptr [eax + 0x96c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c1e4\n\t"
        "lea                eax, dword ptr [esi + esi * 0x8]\n\t"
        "shl                eax, 4\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x00d091b8]\n\t"
        "cmp                ecx, 0x00766390\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c1c1\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x0076c1e4\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x00d091bc]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c1c1\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x00d091c0]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c1c1\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x00d091c4]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x0076c1e4\n"
        "LAB__addr_0x0076c1c1:\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076c1db\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "push               edi\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               ?RemoveVillagerOnWayToWorshipSite@Town@@QAEXPAVVillager@@@Z\n"
        "LAB__addr_0x0076c1db:\n\t"
        ".byte              0x66, 0x81, 0xa7, 0xe0, 0x0, 0x0, 0x0, 0xef, 0xff\n"
        "LAB__addr_0x0076c1e4:\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "ret                0x0004"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall ExitAtWorshipSite__8VillagerFUc(struct Villager* this, const void* edx, unsigned char param_1)
{
    asm volatile (
        "push               ebx\n\t"
        "%{disp8%} mov        ebx, dword ptr [esp + 0x08]\n\t"
        "push               ebp\n\t"
        "push               esi\n\t"
        "mov.s              ebp, ebx\n\t"
        "push               edi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "and                ebp, 0x000000ff\n\t"
        "push               ebp\n\t"
        "call               dword ptr [eax + 0x96c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c272\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x30c]\n\t"
        "mov.s              edi, eax\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x0076c227\n\t"
        "push               esi\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?RemoveVillagerRequestingToGoHome@WorshipSite@@QAEXPAVVillager@@@Z\n"
        "LAB__addr_0x0076c227:\n\t"
        "push               ebp\n\t"
        "call               ?IsReactiveState@Villager@@QAEIK@Z\n\t"
        "add                esp, 0x04\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c24c\n\t"
        "cmp                bl, -0x0f\n\t"
        "%{disp8%} je         LAB__addr_0x0076c24c\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?RemoveVillagerFromWorshipSite@Villager@@QAEIXZ\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebx\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x0076c24c:\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x0076c258\n\t"
        "push               esi\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?RemoveVillagerFromWorshipCount@WorshipSite@@QAEXPAVVillager@@@Z\n"
        "LAB__addr_0x0076c258:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x978]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076c272\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               0x1\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0xb08]\n"
        "LAB__addr_0x0076c272:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebx\n\t"
        "ret                0x0004"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall ExitGetFoodAtWorship__8VillagerFUc(struct Villager* this, const void* edx, unsigned char param_1)
{
    asm volatile (
        "push               esi\n\t"
        "%{disp8%} mov        esi, dword ptr [esp + 0x08]\n\t"
        "push               edi\n\t"
        "mov.s              edi, ecx\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "and                esi, 0x000000ff\n\t"
        "push               esi\n\t"
        "call               dword ptr [eax + 0x96c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c2b8\n\t"
        "lea                eax, dword ptr [esi + esi * 0x2]\n\t"
        "shl                eax, 3\n\t"
        "sub.s              eax, esi\n\t"
        "lea                ecx, dword ptr [eax + eax * 0x2]\n\t"
        "%{disp32%} mov       eax, dword ptr [ecx * 0x4 + 0x00db9f50]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c2b8\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?RemoveVillagerFromWorshipSite@Villager@@QAEIXZ\n"
        "LAB__addr_0x0076c2b8:\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "ret                0x0004"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall ArrivesAtWorshipSiteWithSupplies__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "push               ecx\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "call               dword ptr [eax + 0x30c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076c329\n\t"
        "movsx              eax, word ptr [esi + 0x000000f4]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x04], eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076c329\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "push               0x0\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x0c]\n\t"
        "push               ecx\n\t"
        "push               0x0\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x30c]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?AtStructureAddResource@Villager@@QAEIPAVMultiMapFixed@@W4RESOURCE_TYPE@@AAK_N@Z\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              edi, eax\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x08]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x30c]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x0077c4d0\n\t"
        "cmp                edi, 0x24\n\t"
        "pop                edi\n\t"
        "%{disp8%} je         LAB__addr_0x0076c338\n"
        "LAB__addr_0x0076c329:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x000000a3\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x8e8]\n"
        "LAB__addr_0x0076c338:\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "pop                ecx\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((XOR32rr_REV))
struct WorshipSite* __fastcall GetWorshipSite__8VillagerFv(struct GameThingWithPos* this)
{
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076c35f\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               dword ptr [edx + 0x30c]\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x0076c35f:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x114]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076c388\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetTribe@Villager@@QAEPAVGTribeInfo@@XZ\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x114]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x00463190\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x0076c388:\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall RestartWorshippingAtWorshipSite__8VillagerFv(struct Villager* this)
{
    void* dummy;
    bool32_t result;
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "call               ?StartWorshippingAtWorshipSite@Villager@@QAEIXZ\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x0076c3ac\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x000000a3\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x8e8]\n\t"
        "LAB__addr_0x0076c3ac:\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi"
        : "=a"(result), "=c"(dummy) : "c"(this) : "edx", "memory"
    );
    return result;
}

bool32_t __fastcall RestartWorshippingCreature__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "%{disp32%} mov       eax, dword ptr [ecx + 0x000000d8]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076c3e0\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x14]\n\t"
        "push               0x9\n\t"
        "push               0x5a\n\t"
        "add                eax, 0x14\n\t"
        "push               eax\n\t"
        "call               ?PerformDance@Living@@QAEIABUMapCoords@@EK@Z\n\t"
        "mov                eax, 0x00000001\n\t"
        "ret\n"
        "LAB__addr_0x0076c3e0:\n\t"
        "call               ?GoHome@Villager@@QAEIXZ\n\t"
        "mov                eax, 0x00000001\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall AddVillagerToWorshipSite__8VillagerFv(struct Villager* this)
{
    void* dummy;
    bool32_t result;
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "test               byte ptr [esi + 0x000000e0], 0x02\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c419\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x0073e3e0\n\t"
        "or                 byte ptr [esi + 0xe0], 2\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000118], 0x00000000\n\t"
        "LAB__addr_0x0076c419:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               esi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x30c]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x0077d040\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi"
        : "=a"(result), "=c"(dummy) : "c"(this) : "edx", "memory"
    );
    return result;
}

bool32_t __fastcall RemoveVillagerFromWorshipSite__8VillagerFv(struct Villager* this)
{
    void* dummy;
    bool32_t result;
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076c4a3\n\t"
        "test               byte ptr [esi + 0x000000e0], 0x02\n\t"
        "%{disp8%} je         LAB__addr_0x0076c463\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x0073e3f0\n\t"
        "LAB__addr_0x0076c463:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x30c]\n\t"
        "mov.s              edi, eax\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x0076c488\n\t"
        "push               esi\n\t"
        "mov.s              ecx, edi\n\t"
        "call               _jmp_addr_0x0077d110\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076c488\n\t"
        "push               esi\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?RemoveVillagerFromWorshipCount@WorshipSite@@QAEXPAVVillager@@@Z\n\t"
        "LAB__addr_0x0076c488:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x978]\n\t"
        "test               eax, eax\n\t"
        "pop                edi\n\t"
        "%{disp8%} je         LAB__addr_0x0076c4a3\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x1\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0xb08]\n\t"
        "LAB__addr_0x0076c4a3:\n\t"
        ".byte              0x66, 0x81, 0xa6, 0xe0, 0x0, 0x0, 0x0, 0xfd, 0xff\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000118], 0x00000000\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi"
        : "=a"(result), "=c"(dummy) : "c"(this) : "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall StartWorshippingAtWorshipSite__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "sub                esp, 0x0c\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "call               dword ptr [eax + 0x30c]\n\t"
        "mov.s              edi, eax\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x0076c547\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x2c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076c547\n\t"
        "%{disp32%} mov       ecx, dword ptr [edi + 0x000000a0]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x0076c547\n\t"
        "push               esi\n\t"
        "call               ?FindDanceGroup@GroupBehaviour@@QAEIPAVLiving@@@Z\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c547\n\t"
        "%{disp32%} mov       ecx, dword ptr [edi + 0x000000a0]\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x08]\n\t"
        "add                ecx, 0x14\n\t"
        "push               eax\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, esi\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], 0x00000000\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], 0x00000000\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], 0x00000000\n\t"
        "call               ?CalculateDancePosition@Living@@QAE_NABUMapCoords@@PAU2@@Z\n\t"
        "push               0x3c\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x0c]\n\t"
        "push               edx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?SetupMoveToPos@Villager@@QAE_NABUMapCoords@@W4VILLAGER_STATES@@@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076c547\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?AddVillagerToWorshipSite@Villager@@QAEIXZ\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x0c\n\t"
        "ret\n"
        "LAB__addr_0x0076c547:\n\t"
        "pop                edi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi\n\t"
        "add                esp, 0x0c\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall StartHidingAtWorshipSite__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "sub                esp, 0x18\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "call               dword ptr [eax + 0x30c]\n\t"
        "mov.s              edi, eax\n\t"
        "xor.s              eax, eax\n\t"
        "cmp.s              edi, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c577\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x8c8]\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "add                esp, 0x18\n\t"
        "ret\n"
        "LAB__addr_0x0076c577:\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x14]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], 0x00000000\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x864]\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], edx\n\t"
        "%{disp8%} mov        ecx, dword ptr [eax + 0x04]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], ecx\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x08]\n\t"
        "push               0x000000d5\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x0c]\n\t"
        "push               eax\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x1c], edx\n\t"
        "call               @SetupMoveToOnFootpath__6LivingFR16GameThingWithPosRC9MapCoordsUc@17\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076c5d2\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?AddVillagerToWorshipSite@Villager@@QAEIXZ\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x18\n\t"
        "ret\n"
        "LAB__addr_0x0076c5d2:\n\t"
        "pop                edi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi\n\t"
        "add                esp, 0x18\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall HidingAtWorshipSite__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "sub                esp, 0x18\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "call               dword ptr [eax + 0x30c]\n\t"
        "xor.s              ecx, ecx\n\t"
        "cmp.s              eax, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x0076c662\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x04], ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], ecx\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x10]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, eax\n\t"
        "call               dword ptr [edx + 0x864]\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x04], edx\n\t"
        "%{disp8%} mov        ecx, dword ptr [eax + 0x04]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], ecx\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x08]\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x3f800000\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x08]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, esi\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], edx\n\t"
        "call               dword ptr [eax + 0x85c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076c647\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?ProcessInWorship@Villager@@QAEIXZ\n\t"
        "pop                esi\n\t"
        "add                esp, 0x18\n\t"
        "ret\n"
        "LAB__addr_0x0076c647:\n\t"
        "push               0x000000d5\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x08]\n\t"
        "push               edx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @SetupMoveToWithHug__6LivingFRC9MapCoordsUc@13\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x18\n\t"
        "ret\n"
        "LAB__addr_0x0076c662:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x000000a3\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x8e8]\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x18\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall WorshippingAtWorshipSite__8VillagerFv(struct Villager* this)
{
    void* dummy;
    bool32_t result;
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "xor.s              eax, eax\n\t"
        "%{disp32%} mov       ax, word ptr [esi + 0x000000e0]\n\t"
        "test               al, 0x10\n\t"
        "%{disp8%} je         LAB__addr_0x0076c6ab\n\t"
        "and                eax, 0x0000ffef\n\t"
        "%{disp32%} mov       word ptr [esi + 0x000000e0], ax\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x000000d8]\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x14]\n\t"
        "dec                dword ptr [eax + 0x00000114]\n\t"
        "LAB__addr_0x0076c6ab:\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?ProcessInWorship@Villager@@QAEIXZ\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c6d1\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x000000d8]\n\t"
        "%{disp8%} mov        ecx, dword ptr [eax + 0x5c]\n\t"
        "push               ecx\n\t"
        "%{disp8%} mov        ecx, dword ptr [eax + 0x14]\n\t"
        "add                ecx, 0x14\n\t"
        "push               0x3c\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?PerformDance@Living@@QAEIABUMapCoords@@EK@Z\n\t"
        "LAB__addr_0x0076c6d1:\n\t"
        "pop                esi"
        : "=a"(result), "=c"(dummy) : "c"(this) : "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall StartWorshippingCreature__8VillagerFP8Creature(struct Villager* this, const void* edx, struct Creature* param_1)
{
    asm volatile (
        "sub                esp, 0x0c\n\t"
        "push               ebp\n\t"
        "%{disp8%} mov        ebp, dword ptr [esp + 0x14]\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp32%} mov       ecx, dword ptr [ebp + 0x00001074]\n\t"
        "push               esi\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], 0x00000000\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], 0x00000000\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], 0x00000000\n\t"
        "call               ?FindDanceGroup@GroupBehaviour@@QAEIPAVLiving@@@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x0076c7b6\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x000000d8]\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x0076c7b6\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0xb04]\n\t"
        "and                eax, 0x000000ff\n\t"
        "lea                ecx, dword ptr [eax + eax * 0x8]\n\t"
        "shl                ecx, 4\n\t"
        "add                ecx, 0x00d091b8\n\t"
        "mov.s              edi, ecx\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "cmp                eax, 0x007527e0\n\t"
        "%{disp8%} mov        ecx, dword ptr [edi + 0x04]\n\t"
        "%{disp8%} mov        edx, dword ptr [edi + 0x08]\n\t"
        "%{disp8%} mov        edi, dword ptr [edi + 0x0c]\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c76c\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076c765\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c76c\n\t"
        "test               edx, edx\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c76c\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c76c\n"
        "LAB__addr_0x0076c765:\n\t"
        "%{disp32%} mov       byte ptr [esi + 0x0000008c], -0x34\n"
        "LAB__addr_0x0076c76c:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               0x000000cc\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x8e8]\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x000000d8]\n\t"
        "test               eax, eax\n\t"
        "pop                edi\n\t"
        "%{disp8%} je         LAB__addr_0x0076c7b6\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x08]\n\t"
        "push               eax\n\t"
        "add                ebp, 0x14\n\t"
        "push               ebp\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?CalculateDancePosition@Living@@QAE_NABUMapCoords@@PAU2@@Z\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x28]\n\t"
        "%{disp32%} mov       edx, dword ptr [ecx + 0x00000110]\n\t"
        "push               0x1\n\t"
        "push               edx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?SetSpeed@Villager@@QAEXJH@Z\n\t"
        "pop                esi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebp\n\t"
        "add                esp, 0x0c\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x0076c7b6:\n\t"
        "pop                esi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                ebp\n\t"
        "add                esp, 0x0c\n\t"
        "ret                0x0004"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall WorshippingCreature__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "%{disp32%} mov       eax, dword ptr [ecx + 0x000000d8]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076c7f3\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x14]\n\t"
        "push               esi\n\t"
        "%{disp32%} mov       esi, dword ptr [edx + 0x00000100]\n\t"
        "test               esi, esi\n\t"
        "pop                esi\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c7ee\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x5c]\n\t"
        "push               eax\n\t"
        "push               0x5a\n\t"
        "add                edx, 0x14\n\t"
        "push               edx\n\t"
        "call               ?PerformDance@Living@@QAEIABUMapCoords@@EK@Z\n\t"
        "mov                eax, 0x00000001\n\t"
        "ret\n"
        "LAB__addr_0x0076c7ee:\n\t"
        "call               ?GoHome@Villager@@QAEIXZ\n"
        "LAB__addr_0x0076c7f3:\n\t"
        "mov                eax, 0x00000001\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall ReduceVillagerLifeByChant__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "push               ecx\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "call               dword ptr [eax + 0x30c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076c881\n\t"
        "%{disp32%} fld       dword ptr [eax + 0x00000104]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x28]\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "%{disp32%} fmul      dword ptr [ecx + 0x0000028c]\n\t"
        "push               0x0\n\t"
        "mov.s              ecx, esi\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x0c]\n\t"
        "%{disp8%} mov        edi, dword ptr [esp + 0x0c]\n\t"
        "push               edi\n\t"
        "call               dword ptr [edx + 0x5b8]\n\t"
        "fstp               st(0)\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x11c]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float0p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp8%} je         LAB__addr_0x0076c881\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076c869\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "%{disp8%} jmp        LAB__addr_0x0076c86b\n"
        "LAB__addr_0x0076c869:\n\t"
        "xor.s              eax, eax\n"
        "LAB__addr_0x0076c86b:\n\t"
        "push               0x1\n\t"
        "push               edi\n\t"
        "push               eax\n\t"
        "push               0x4\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?VillagerDead@Villager@@QAEXW4DEATH_REASON@@PAVGPlayer@@MH@Z\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000021\n\t"
        "pop                esi\n\t"
        "pop                ecx\n\t"
        "ret\n"
        "LAB__addr_0x0076c881:\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "pop                ecx\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall ProcessInWorship__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "call               ?CheckVillagerGoBackToTownFromWorship@Villager@@QAEIXZ\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c8a4\n\t"
        "mov                eax, 0x00000023\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x0076c8a4:\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?ReduceVillagerLifeByChant@Villager@@QAEIXZ\n\t"
        "cmp                eax, 0x21\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c8b7\n\t"
        "mov                eax, 0x00000023\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x0076c8b7:\n\t"
        "push               0x1\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?CheckAllowedToRestAtWorshipSite@Villager@@QAEIH@Z\n\t"
        "neg                eax\n\t"
        "sbb.s              eax, eax\n\t"
        "and                eax, 0x22\n\t"
        "inc                eax\n\t"
        "pop                esi\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall CheckRequestGoHome__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "call               dword ptr [eax + 0x30c]\n\t"
        "mov.s              edi, eax\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x0076c920\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               ebx\n\t"
        "%{disp8%} mov        ebx, dword ptr [esi + 0x28]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x11c]\n\t"
        "%{disp32%} fcomp     dword ptr [ebx + 0x0000035c]\n\t"
        "pop                ebx\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x00000118]\n\t"
        "%{disp8%} je         LAB__addr_0x0076c913\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c920\n\t"
        "push               esi\n\t"
        "mov.s              ecx, edi\n\t"
        "call               _jmp_addr_0x0077e0c0\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x0076c913:\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c920\n\t"
        "push               esi\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?RemoveVillagerRequestingToGoHome@WorshipSite@@QAEXPAVVillager@@@Z\n"
        "LAB__addr_0x0076c920:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall CheckNeededForWorshipSiteBuilding__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "call               dword ptr [eax + 0x30c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c963\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x114]\n\t"
        "mov.s              edi, eax\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x0076c997\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, edi\n\t"
        "call               _jmp_addr_0x004631d0\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076c997\n"
        "LAB__addr_0x0076c963:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x0073ce40\n\t"
        "mov.s              edi, eax\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x0076c997\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x000000a3\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x8e8]\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?SetupBuildingObject@Villager@@QAEIPAVBuildingSite@@@Z\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x0076c997\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x0076c997:\n\t"
        "pop                edi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall CheckAllowedToRestAtWorshipSite__8VillagerFi(struct Villager* this, const void* edx, int param_1)
{
    asm volatile (
        "sub                esp, 0x0c\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "call               dword ptr [eax + 0x30c]\n\t"
        "%{disp32%} fld       dword ptr [esi + 0x000000e8]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x28]\n\t"
        "%{disp32%} fcomp     dword ptr [ecx + 0x000002c0]\n\t"
        "mov.s              edi, eax\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x0076ca19\n\t"
        "push               ebx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetAmountOfFoodRequiredForMeal@Villager@@QAEIXZ\n\t"
        "mov.s              ebx, eax\n\t"
        "xor.s              eax, eax\n\t"
        "test               edi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x0076c9de\n\t"
        "mov.s              ecx, edi\n\t"
        "call               _jmp_addr_0x0077bdb0\n"
        "LAB__addr_0x0076c9de:\n\t"
        "cmp.s              eax, ebx\n\t"
        "pop                ebx\n\t"
        "%{disp8%} jl         LAB__addr_0x0076ca19\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x18]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076ca0c\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "push               0x000000f1\n\t"
        "push               0x1\n\t"
        "push               esi\n\t"
        "push               0x0\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x18]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x8d4]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @SetupMoveToWithHug__6LivingFRC9MapCoordsUc@13\n"
        "LAB__addr_0x0076ca0c:\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x0c\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x0076ca19:\n\t"
        "pop                edi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi\n\t"
        "add                esp, 0x0c\n\t"
        "ret                0x0004"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall GetFoodAtWorshipSite__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "sub                esp, 0x0c\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               edi\n\t"
        "call               dword ptr [eax + 0x30c]\n\t"
        "mov.s              edi, eax\n\t"
        "test               edi, edi\n\t"
        "%{disp32%} je        LAB__addr_0x0076cad1\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "push               ebx\n\t"
        "mov                ebx, dword ptr [esi]\n\t"
        "push               0x0\n\t"
        "push               0x1\n\t"
        "push               esi\n\t"
        "push               0x0\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x1c]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x8d4]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [ebx + 0x85c]\n\t"
        "test               eax, eax\n\t"
        "pop                ebx\n\t"
        "%{disp8%} je         LAB__addr_0x0076caa5\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetAmountOfFoodRequiredForMeal@Villager@@QAEIXZ\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076ca86\n\t"
        "push               eax\n\t"
        "push               0x0\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetResourceFrom@Villager@@QAEIPAVObject@@W4RESOURCE_TYPE@@F@Z\n"
        "LAB__addr_0x0076ca86:\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?EatFoodHeld@Villager@@QAEIXZ\n\t"
        "fstp               st(0)\n\t"
        "push               0x1\n\t"
        "push               0x41\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?PlayAnimThenSetState@Living@@QAEXEK@Z\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x0c\n\t"
        "ret\n"
        "LAB__addr_0x0076caa5:\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "push               0x000000f1\n\t"
        "push               0x1\n\t"
        "push               esi\n\t"
        "push               0x0\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x18]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x8d4]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @SetupMoveToWithHug__6LivingFRC9MapCoordsUc@13\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x0c\n\t"
        "ret\n"
        "LAB__addr_0x0076cad1:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               0x000000a3\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x8e8]\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x0c\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

float __fastcall GetFoodDesireAtWorshipSite__8VillagerFv(struct Villager* this)
{
    extern const float rdata_float1p0;
    return rdata_float1p0;
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall GotoAltarForRest__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "sub                esp, 0x0c\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "call               dword ptr [eax + 0x30c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076cb59\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "xor.s              eax, eax\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x04]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, esi\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], eax\n\t"
        "call               dword ptr [edx + 0x30c]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x0077ce70\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               0x3e\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x08]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x30c]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @SetupMoveToOnFootpath__6LivingFR16GameThingWithPosRC9MapCoordsUc@17\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x0c\n\t"
        "ret\n"
        "LAB__addr_0x0076cb59:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x000000a3\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x8e8]\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x0c\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall ArrivesAtAltarForRest__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "push               0x0\n\t"
        "call               ?CheckAllowedToRestAtWorshipSite@Villager@@QAEIH@Z\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x0076cb98\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?AtAltarFinishedRest@Villager@@QAEIXZ\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x0076cb98:\n\t"
        "push               0x1\n\t"
        "push               0x3f\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?PlayAnimThenSetState@Living@@QAEXEK@Z\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall AtAltarRest__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "push               0x0\n\t"
        "call               ?CheckAllowedToRestAtWorshipSite@Villager@@QAEIH@Z\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x0076cbc8\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?AtAltarFinishedRest@Villager@@QAEIXZ\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x0076cbc8:\n\t"
        "push               0x1\n\t"
        "push               0x3f\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?PlayAnimThenSetState@Living@@QAEXEK@Z\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall AtAltarFinishedRest__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "call               ?StartWorshippingAtWorshipSite@Villager@@QAEIXZ\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x0076cbef\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x0076cbef:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x8c8]\n\t"
        "pop                esi\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall CheckSatisfySuppyWorship__8VillagerFv(struct Villager* this)
{
    void* dummy;
    bool32_t result;
    asm volatile (
        "call ?GotoStoragePitForWorshipSupplies@Villager@@QAEIXZ\n\t"
        "dec eax\n\t"
        "neg eax\n\t"
        ".byte 0x1b, 0xc0\n\t"
        "inc eax"
        : "=a"(result), "=c"(dummy) : "c"(this) : "edx", "memory"
    );
    return result;
}
