#include "Villager.h"

const float villager_farmer_num_days_in_year_0x0099a958 = 365.25f;
const float villager_farmer_seconds_in_day_0x0099a95c = 86400.0f;

float villager_farmer_seconds_in_year_0x00db9dfc;

__attribute__((no_ret))
void __cdecl globl_ct_0x00759b90(void)
{
    asm volatile (
        "%{disp32%} mov cl, byte ptr [_DAT_00fac934]\n\t"
        "mov al, 0x01\n\t"
        "test al, cl\n\t"
        "%{disp8%} jne LAB__addr_0x00759ba4\n\t"
        "or.s cl, al\n\t"
        "%{disp32%} mov byte ptr [_DAT_00fac934], cl\n"
        "LAB__addr_0x00759ba4:\n\t"
        "%{disp32%} jmp _crt_global_destruction_register_0x00759bb0"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((prefer_pop_cleanup))
void __cdecl crt_global_destruction_register_0x00759bb0(void)
{
    extern int __cdecl atexit(void (*)(void));
    atexit((void (*)(void))0x00407870);
}

extern void __cdecl FUN_00759bd0__8VillagerFv(void) __attribute__((noinline));

void __cdecl globl_ct_0x00759bc0(void)
{
    __attribute__((musttail)) return FUN_00759bd0__8VillagerFv();
}

__attribute__((prefer_fmul_mem))
void __cdecl FUN_00759bd0__8VillagerFv(void)
{
    extern float __opaque_a asm("_villager_farmer_seconds_in_day_0x0099a95c");
    extern float __opaque_b asm("_villager_farmer_num_days_in_year_0x0099a958");
    extern float __opaque_c asm("_villager_farmer_seconds_in_year_0x00db9dfc");
    __opaque_c = __opaque_a * __opaque_b;
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall FarmerLookForField__8VillagerFv(struct Villager* this)
{
    return 0;
}

__attribute__((no_callee_saves, XOR32rr_REV))
bool32_t __fastcall VillagerBecomesFarmer__8VillagerFP5Field(struct Villager* this, const void* edx, struct Field* param_1)
{
    bool32_t result;
    asm volatile (
        "%{disp8%} mov        eax, dword ptr [esp + 0x04]\n\t"
        "test               eax, eax\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp8%} jne        LAB__addr_0x00759c25\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00759c33\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x08]\n\t"
        "push               ecx\n\t"
        "push               esi\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x0073e870\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00759c33\n"
        "LAB__addr_0x00759c25:\n\t"
        "push               0x0\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?SetFarmerGotoField@Villager@@QAEIPAVField@@H@Z\n\t"
        "pop                esi\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x00759c33:\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV))
bool32_t __fastcall SetFarmerGotoField__8VillagerFP5Fieldi(struct Villager* this, const void* edx, struct Field* param_1, int param_2)
{
    bool32_t result;
    asm volatile (
        "sub                esp, 0x24\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "push               edi\n\t"
        "%{disp8%} mov        edi, dword ptr [esp + 0x30]\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x14]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x104]\n\t"
        "xor.s              ecx, ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], ecx\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], edx\n\t"
        "%{disp8%} mov        ecx, dword ptr [eax + 0x04]\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x34]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], ecx\n\t"
        "%{disp8%} fld        dword ptr [eax + 0x08]\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x10]\n\t"
        "push               edx\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?GetFieldActivity@Field@@QAEHH@Z\n\t"
        "dec                eax\n\t"
        "%{disp8%} je         LAB__addr_0x00759cc8\n\t"
        "dec                eax\n\t"
        "%{disp8%} je         LAB__addr_0x00759c98\n\t"
        "pop                edi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi\n\t"
        "add                esp, 0x24\n\t"
        "ret                0x0008\n"
        "LAB__addr_0x00759c98:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x000000a3\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x8e8]\n\t"
        "push               0x43\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x0c]\n\t"
        "push               ecx\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000118], edi\n\t"
        "call               @SetupMoveToOnFootpath__6LivingFR16GameThingWithPosRC9MapCoordsUc@17\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x00000118]\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x14]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00759cf6\n"
        "LAB__addr_0x00759cc8:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               0x000000a3\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x8e8]\n\t"
        "push               0x43\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x0c]\n\t"
        "push               eax\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000118], edi\n\t"
        "call               @SetupMoveToOnFootpath__6LivingFR16GameThingWithPosRC9MapCoordsUc@17\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x00000118]\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x20]\n"
        "LAB__addr_0x00759cf6:\n\t"
        "push               edx\n\t"
        "call               _jmp_addr_0x00528970\n\t"
        "mov                ecx, dword ptr [eax]\n\t"
        "add                esi, 0x0000011c\n\t"
        "mov                dword ptr [esi], ecx\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x04]\n\t"
        "%{disp8%} mov        dword ptr [esi + 0x04], edx\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x08]\n\t"
        "%{disp8%} mov        dword ptr [esi + 0x08], eax\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x24"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves))
bool32_t __fastcall FarmerArrivesAtFarm__8VillagerFv(struct Villager* this)
{
    bool32_t result;
    asm volatile (
        "sub                esp, 0x24\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x00000118]\n\t"
        "push               0x0\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], 0x00000000\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], 0x00000000\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], 0x00000000\n\t"
        "call               ?GetFieldActivity@Field@@QAEHH@Z\n\t"
        "dec                eax\n\t"
        "%{disp32%} je        LAB__addr_0x00759dd6\n\t"
        "dec                eax\n\t"
        "%{disp8%} jne        LAB__addr_0x00759dbc\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x00000118]\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x08]\n\t"
        "push               eax\n\t"
        "push               esi\n\t"
        "call               _jmp_addr_0x00529240\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00759dbc\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               0x0\n\t"
        "%{disp32%} lea       edi, dword ptr [esi + 0x0000011c]\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x85c]\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x00759e2a\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x00000118]\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x14]\n\t"
        "push               eax\n\t"
        "call               _jmp_addr_0x00528970\n\t"
        "mov                ecx, dword ptr [eax]\n\t"
        "mov                dword ptr [edi], ecx\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x04]\n\t"
        "%{disp8%} mov        dword ptr [edi + 0x04], edx\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x08]\n\t"
        "push               0x1\n\t"
        "push               0x45\n\t"
        "mov.s              ecx, esi\n\t"
        "%{disp8%} mov        dword ptr [edi + 0x08], eax\n\t"
        "call               ?PlayAnimThenSetState@Living@@QAEXEK@Z\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x24\n\t"
        "ret\n"
        "LAB__addr_0x00759dbc:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               0x000000a3\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x8e8]\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x24\n\t"
        "ret\n"
        "LAB__addr_0x00759dd6:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x0\n\t"
        "%{disp32%} lea       edi, dword ptr [esi + 0x0000011c]\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "%{disp32%} mov       byte ptr [esi + 0x000000f1], 0x01\n\t"
        "call               dword ptr [eax + 0x85c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00759e2a\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x00000118]\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x20]\n\t"
        "push               edx\n\t"
        "call               _jmp_addr_0x00528970\n\t"
        "mov                ecx, dword ptr [eax]\n\t"
        "mov                dword ptr [edi], ecx\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x04]\n\t"
        "%{disp8%} mov        dword ptr [edi + 0x04], edx\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x08]\n\t"
        "push               0x1\n\t"
        "push               0x44\n\t"
        "mov.s              ecx, esi\n\t"
        "%{disp8%} mov        dword ptr [edi + 0x08], eax\n\t"
        "call               ?PlayAnimThenSetState@Living@@QAEXEK@Z\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x24\n\t"
        "ret\n"
        "LAB__addr_0x00759e2a:\n\t"
        "push               0x43\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?SetupMoveToPos@Villager@@QAE_NABUMapCoords@@W4VILLAGER_STATES@@@Z\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x24"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves))
bool32_t __fastcall FarmerDigsUpCrop__8VillagerFv(struct Villager* this)
{
    bool32_t result;
    asm volatile (
        "sub                esp, 0x08\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "push               edi\n\t"
        "%{disp32%} mov       edi, dword ptr [esi + 0x00000118]\n\t"
        "call               ?GetFoodCapacity@Villager@@QAEHXZ\n\t"
        "movsx              eax, ax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], eax\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, edi\n\t"
        "%{disp8%} fild       dword ptr [esp + 0x0c]\n\t"
        "fstp               dword ptr [esp]\n\t"
        "call               ?RemoveFood@Field@@QAEMM@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jbe        LAB__addr_0x00759ea8\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?PickupFood@Villager@@QAEXF@Z\n\t"
        "%{disp32%} mov       ecx, dword ptr [data_bytes + 0x3734dc]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], ecx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetFoodCapacity@Villager@@QAEHXZ\n\t"
        "movsx              edx, ax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x08], edx\n\t"
        "%{disp8%} fild       dword ptr [esp + 0x08]\n\t"
        "%{disp8%} fcomp      dword ptr [esp + 0x0c]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x00759ea8\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GotoStoragePitForDropOff@Villager@@QAEIXZ\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "add                esp, 0x08\n\t"
        "ret\n"
        "LAB__addr_0x00759ea8:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x43\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x8e8]\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "add                esp, 0x08"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves))
bool32_t __fastcall FarmerPlantsCrop__8VillagerFv(struct Villager* this)
{
    extern bool32_t __attribute__((thiscall)) __opaque_PlantCrop(void*, const void*) asm("?PlantCrop@Field@@QAEIABUMapCoords@@@Z");
    extern bool32_t __attribute__((thiscall)) __opaque_GetPlantCropPos(void*) asm("?GetPlantCropPos@Field@@QAEIXZ");
    bool32_t result;
    register struct Villager* self asm("esi");
    asm volatile ("push esi\n\tmov.s esi, ecx" : "=r"(self) : "c"(this) : "memory");

    void* field = *(void**)((char*)self + 0x118);
    void* pos = (void*)((char*)self + 0x14);
    bool32_t planted = __opaque_PlantCrop(field, pos);
    asm volatile (
        "test eax, eax\n\t"
        "%{disp8%} je 0f"
        :: "a"(planted), "S"(self) : "memory"
    );
    {
        void* field2 = *(void**)((char*)self + 0x118);
        bool32_t crop_pos = __opaque_GetPlantCropPos(field2);
        asm volatile (
            "test eax, eax\n\t"
            "%{disp8%} je 1f\n\t"
            "mov edx, dword ptr [esi]\n\t"
            "push 0x43\n\t"
            "mov.s ecx, esi\n\t"
            "call dword ptr [edx + 0x8e8]\n\t"
            "mov eax, 0x00000001\n\t"
            "pop esi\n\t"
            "ret\n"
            "1:\n\t"
            "mov eax, dword ptr [esi]\n\t"
            "push 0x000000a3\n\t"
            "mov.s ecx, esi\n\t"
            "call dword ptr [eax + 0x8e8]\n\t"
            "mov eax, 0x00000001\n\t"
            "pop esi\n\t"
            "ret\n"
            "0:\n\t"
            "mov edx, dword ptr [esi]\n\t"
            "push 0x000000a3\n\t"
            "mov.s ecx, esi\n\t"
            "call dword ptr [edx + 0x8e8]\n\t"
            "mov eax, 0x00000001\n\t"
            "pop esi"
            : "=a"(result) : "a"(crop_pos), "S"(self) : "ecx", "edx", "memory"
        );
    }
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV))
bool32_t __fastcall CheckSatisfyFoodDesire__8VillagerFv(struct Villager* this)
{
    bool32_t result;
    asm volatile (
        "sub                esp, 0x40\n\t"
        "push               ebx\n\t"
        "push               ebp\n\t"
        "push               esi\n\t"
        "mov.s              ebx, ecx\n\t"
        "mov                eax, dword ptr [ebx]\n\t"
        "push               edi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "xor.s              ebp, ebp\n\t"
        "mov.s              ecx, eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], ebp\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x1c], ebp\n\t"
        "%{disp8%} jmp        LAB__addr_0x00759f54\n"
        "LAB__addr_0x00759f50:\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x10]\n"
        "LAB__addr_0x00759f54:\n\t"
        "%{disp8%} lea        esi, dword ptr [ebp + ebp * 0x2 + 0x00]\n\t"
        "shl                esi, 2\n\t"
        "mov.s              eax, ebp\n\t"
        "sub                eax, 0x00\n\t"
        "%{disp8%} mov        dword ptr [esp + esi * 0x1 + 0x34], ebp\n\t"
        "%{disp8%} je         LAB__addr_0x00759f8e\n\t"
        "dec                eax\n\t"
        "%{disp8%} je         LAB__addr_0x00759f7d\n\t"
        "dec                eax\n\t"
        "%{disp8%} jne        LAB__addr_0x00759f9d\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x44]\n\t"
        "push               edx\n\t"
        "push               ebx\n\t"
        "call               _jmp_addr_0x0073e7f0\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x48], eax\n\t"
        "%{disp8%} jmp        LAB__addr_0x00759f9d\n"
        "LAB__addr_0x00759f7d:\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x38]\n\t"
        "push               eax\n\t"
        "push               ebx\n\t"
        "call               _jmp_addr_0x0073e870\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x3c], eax\n\t"
        "%{disp8%} jmp        LAB__addr_0x00759f9d\n"
        "LAB__addr_0x00759f8e:\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x2c]\n\t"
        "push               edx\n\t"
        "push               ebx\n\t"
        "call               _jmp_addr_0x0073e750\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x30], eax\n"
        "LAB__addr_0x00759f9d:\n\t"
        "push               0x8\n\t"
        "%{disp8%} lea        edi, dword ptr [esp + esi * 0x1 + 0x30]\n\t"
        "call               ??2@YAPAXI@Z\n\t"
        "xor.s              edx, edx\n\t"
        "add                esp, 0x04\n\t"
        "cmp.s              eax, edx\n\t"
        "%{disp8%} je         LAB__addr_0x00759fba\n\t"
        "mov                dword ptr [eax], edi\n\t"
        "%{disp8%} mov        dword ptr [eax + 0x04], edx\n\t"
        "mov.s              esi, eax\n\t"
        "%{disp8%} jmp        LAB__addr_0x00759fbc\n"
        "LAB__addr_0x00759fba:\n\t"
        "xor.s              esi, esi\n"
        "LAB__addr_0x00759fbc:\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x18]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x00759ff4\n"
        "LAB__addr_0x00759fc4:\n\t"
        "mov                eax, dword ptr [ecx]\n\t"
        "fld                dword ptr [edi]\n\t"
        "fcomp              dword ptr [eax]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp8%} je         LAB__addr_0x00759fdc\n\t"
        "mov.s              edx, ecx\n\t"
        "%{disp8%} mov        ecx, dword ptr [ecx + 0x04]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x00759ff0\n\t"
        "%{disp8%} jmp        LAB__addr_0x00759fc4\n"
        "LAB__addr_0x00759fdc:\n\t"
        "test               edx, edx\n\t"
        "%{disp8%} mov        dword ptr [esi + 0x04], ecx\n\t"
        "%{disp8%} jne        LAB__addr_0x00759fe9\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], esi\n\t"
        "%{disp8%} jmp        LAB__addr_0x00759fec\n"
        "LAB__addr_0x00759fe9:\n\t"
        "%{disp8%} mov        dword ptr [edx + 0x04], esi\n"
        "LAB__addr_0x00759fec:\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} jne        LAB__addr_0x00759ffd\n"
        "LAB__addr_0x00759ff0:\n\t"
        "test               edx, edx\n\t"
        "%{disp8%} jne        LAB__addr_0x00759ffa\n"
        "LAB__addr_0x00759ff4:\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], esi\n\t"
        "%{disp8%} jmp        LAB__addr_0x00759ffd\n"
        "LAB__addr_0x00759ffa:\n\t"
        "%{disp8%} mov        dword ptr [edx + 0x04], esi\n"
        "LAB__addr_0x00759ffd:\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x1c]\n\t"
        "inc                edx\n\t"
        "inc                ebp\n\t"
        "cmp                ebp, 0x03\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x1c], edx\n\t"
        "%{disp32%} jb        LAB__addr_0x00759f50\n\t"
        "%{disp8%} mov        esi, dword ptr [ebx + 0x28]\n\t"
        "mov.s              ecx, ebx\n\t"
        "call               ?GetFoodCapacity@Villager@@QAEHXZ\n\t"
        "%{disp32%} mov       edx, dword ptr [esi + 0x00000264]\n\t"
        "movsx              ecx, ax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], 0x00000000\n\t"
        "push               0x0\n\t"
        "%{disp8%} fild       dword ptr [esp + 0x14]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], edx\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x24]\n\t"
        "push               eax\n\t"
        "%{disp32%} fadd      dword ptr [rdata_bytes + 0xf1100]\n\t"
        "mov.s              ecx, ebx\n\t"
        "%{disp8%} fild       qword ptr [esp + 0x18]\n\t"
        "%{disp32%} fadd      dword ptr [rdata_bytes + 0xf1100]\n\t"
        "fdivp              st(1), st\n\t"
        "%{disp32%} fsubr     dword ptr [_rdata_float1p0]\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x18]\n\t"
        "call               ?GetResourceDropoffPos@Villager@@QAEPAVGameThingWithPos@@W4RESOURCE_TYPE@@@Z\n\t"
        "push               0x43fa0000\n\t"
        "%{disp8%} lea        ecx, dword ptr [ebx + 0x14]\n\t"
        "push               ecx\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x28]\n\t"
        "call               _GetDistanceInMetres__6GUtilsFRC9MapCoordsRC9MapCoords_2\n\t"
        "push               ecx\n\t"
        "fstp               dword ptr [esp]\n\t"
        "call               _GetDistanceModifier__6GUtilsFff@8\n\t"
        "%{disp8%} fmul       dword ptr [esp + 0x18]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x20]\n\t"
        "mov                edx, dword ptr [ecx]\n\t"
        "add                esp, 0x08\n\t"
        "fcomp              dword ptr [edx]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp8%} jne        LAB__addr_0x0075a0c1\n\t"
        "mov.s              ecx, ebx\n\t"
        "call               ?GotoStoragePitForDropOff@Villager@@QAEIXZ\n\t"
        "mov.s              esi, eax\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x18]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0075a0b7\n"
        "LAB__addr_0x0075a0a3:\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "push               edx\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x1c]\n\t"
        "call               @Remove__31LHOrderedLinkedList_9Glocation_Fv@12\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x18]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0075a0a3\n"
        "LAB__addr_0x0075a0b7:\n\t"
        "pop                edi\n\t"
        "mov.s              eax, esi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x40\n\t"
        "ret\n"
        "LAB__addr_0x0075a0c1:\n\t"
        "%{disp8%} mov        eax, dword ptr [edx + 0x04]\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x0075a1f4\n\t"
        "%{disp8%} mov        edx, dword ptr [edx + 0x08]\n\t"
        "sub                edx, 0x00\n\t"
        "%{disp32%} je        LAB__addr_0x0075a188\n\t"
        "dec                edx\n\t"
        "%{disp8%} je         LAB__addr_0x0075a14e\n\t"
        "dec                edx\n\t"
        "%{disp32%} jne       LAB__addr_0x0075a1f4\n\t"
        "push               eax\n\t"
        "mov.s              ecx, ebx\n\t"
        "call               ?VillagerBecomesShepherd@Villager@@QAEIPAVFlock@@@Z\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp32%} jne       LAB__addr_0x0075a1f0\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x18]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x0075a141\n"
        "LAB__addr_0x0075a0fb:\n\t"
        "mov                esi, dword ptr [ecx]\n\t"
        "xor.s              edx, edx\n\t"
        "test               ecx, ecx\n\t"
        "mov.s              eax, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x0075a141\n"
        "LAB__addr_0x0075a105:\n\t"
        "cmp                dword ptr [eax], esi\n\t"
        "%{disp8%} je         LAB__addr_0x0075a114\n\t"
        "mov.s              edx, eax\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x04]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0075a105\n\t"
        "%{disp8%} jmp        LAB__addr_0x0075a13d\n"
        "LAB__addr_0x0075a114:\n\t"
        "test               edx, edx\n\t"
        "%{disp8%} jne        LAB__addr_0x0075a121\n\t"
        "%{disp8%} mov        ecx, dword ptr [ecx + 0x04]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], ecx\n\t"
        "%{disp8%} jmp        LAB__addr_0x0075a127\n"
        "LAB__addr_0x0075a121:\n\t"
        "%{disp8%} mov        ecx, dword ptr [eax + 0x04]\n\t"
        "%{disp8%} mov        dword ptr [edx + 0x04], ecx\n"
        "LAB__addr_0x0075a127:\n\t"
        "push               eax\n\t"
        "call               ??3@YAXPAX@Z\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x20]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x1c]\n\t"
        "add                esp, 0x04\n\t"
        "dec                eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x1c], eax\n"
        "LAB__addr_0x0075a13d:\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} jne        LAB__addr_0x0075a0fb\n"
        "LAB__addr_0x0075a141:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x40\n\t"
        "ret\n"
        "LAB__addr_0x0075a14e:\n\t"
        "push               eax\n\t"
        "mov.s              ecx, ebx\n\t"
        "call               ?VillagerBecomesFarmer@Villager@@QAEIPAVField@@@Z\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp32%} jne       LAB__addr_0x0075a1f0\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x18]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0075a17b\n"
        "LAB__addr_0x0075a167:\n\t"
        "mov                edx, dword ptr [eax]\n\t"
        "push               edx\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x1c]\n\t"
        "call               @Remove__31LHOrderedLinkedList_9Glocation_Fv@12\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x18]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0075a167\n"
        "LAB__addr_0x0075a17b:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x40\n\t"
        "ret\n"
        "LAB__addr_0x0075a188:\n\t"
        "push               eax\n\t"
        "mov.s              ecx, ebx\n\t"
        "call               ?VillagerBecomesFisherman@Villager@@QAEIPAVFishFarm@@@Z\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x0075a1f0\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x18]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x0075a1e3\n"
        "LAB__addr_0x0075a19d:\n\t"
        "mov                esi, dword ptr [ecx]\n\t"
        "xor.s              edx, edx\n\t"
        "test               ecx, ecx\n\t"
        "mov.s              eax, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x0075a1e3\n"
        "LAB__addr_0x0075a1a7:\n\t"
        "cmp                dword ptr [eax], esi\n\t"
        "%{disp8%} je         LAB__addr_0x0075a1b6\n\t"
        "mov.s              edx, eax\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x04]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0075a1a7\n\t"
        "%{disp8%} jmp        LAB__addr_0x0075a1df\n"
        "LAB__addr_0x0075a1b6:\n\t"
        "test               edx, edx\n\t"
        "%{disp8%} jne        LAB__addr_0x0075a1c3\n\t"
        "%{disp8%} mov        ecx, dword ptr [ecx + 0x04]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], ecx\n\t"
        "%{disp8%} jmp        LAB__addr_0x0075a1c9\n"
        "LAB__addr_0x0075a1c3:\n\t"
        "%{disp8%} mov        ecx, dword ptr [eax + 0x04]\n\t"
        "%{disp8%} mov        dword ptr [edx + 0x04], ecx\n"
        "LAB__addr_0x0075a1c9:\n\t"
        "push               eax\n\t"
        "call               ??3@YAXPAX@Z\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x20]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x1c]\n\t"
        "add                esp, 0x04\n\t"
        "dec                eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x1c], eax\n"
        "LAB__addr_0x0075a1df:\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} jne        LAB__addr_0x0075a19d\n"
        "LAB__addr_0x0075a1e3:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x40\n\t"
        "ret\n"
        "LAB__addr_0x0075a1f0:\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x18]\n"
        "LAB__addr_0x0075a1f4:\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x0075a23e\n"
        "LAB__addr_0x0075a1f8:\n\t"
        "mov                esi, dword ptr [ecx]\n\t"
        "xor.s              edx, edx\n\t"
        "test               ecx, ecx\n\t"
        "mov.s              eax, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x0075a23e\n"
        "LAB__addr_0x0075a202:\n\t"
        "cmp                dword ptr [eax], esi\n\t"
        "%{disp8%} je         LAB__addr_0x0075a211\n\t"
        "mov.s              edx, eax\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x04]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0075a202\n\t"
        "%{disp8%} jmp        LAB__addr_0x0075a23a\n"
        "LAB__addr_0x0075a211:\n\t"
        "test               edx, edx\n\t"
        "%{disp8%} jne        LAB__addr_0x0075a21e\n\t"
        "%{disp8%} mov        edx, dword ptr [ecx + 0x04]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], edx\n\t"
        "%{disp8%} jmp        LAB__addr_0x0075a224\n"
        "LAB__addr_0x0075a21e:\n\t"
        "%{disp8%} mov        ecx, dword ptr [eax + 0x04]\n\t"
        "%{disp8%} mov        dword ptr [edx + 0x04], ecx\n"
        "LAB__addr_0x0075a224:\n\t"
        "push               eax\n\t"
        "call               ??3@YAXPAX@Z\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x20]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x1c]\n\t"
        "add                esp, 0x04\n\t"
        "dec                eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x1c], eax\n"
        "LAB__addr_0x0075a23a:\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} jne        LAB__addr_0x0075a1f8\n"
        "LAB__addr_0x0075a23e:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "xor.s              eax, eax\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x40"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV))
bool32_t __fastcall EnterFarming__8VillagerFUcUc(struct Villager* this, const void* edx, unsigned char param_1, unsigned char param_2)
{
    bool32_t result;
    register struct Villager* self asm("esi");
    asm volatile ("push esi\n\tmov.s esi, ecx" : "=r"(self) : "c"(this) : "memory");

    asm volatile (
        "%{disp32%} mov eax, dword ptr [esi + 0x00000118]\n\t"
        "test eax, eax\n\t"
        "%{disp8%} jne 0f\n\t"
        "xor.s eax, eax\n\t"
        "pop esi\n\t"
        "ret 0x0008\n"
        "0:"
        :: "S"(self) : "eax", "memory"
    );
    asm volatile (
        "%{disp8%} mov eax, dword ptr [esp + 0x0c]\n\t"
        "%{disp8%} mov ecx, dword ptr [esp + 0x08]\n\t"
        "and eax, 0x000000ff\n\t"
        "and ecx, 0x000000ff\n\t"
        "push eax\n\t"
        "push ecx\n\t"
        "mov.s ecx, esi\n\t"
        "call ?IsStateEntryFunctionSameAs@Villager@@QBEIKK@Z\n\t"
        "test eax, eax\n\t"
        "%{disp8%} jne 0f\n\t"
        "mov edx, dword ptr [esi]\n\t"
        "mov.s ecx, esi\n\t"
        "call dword ptr [edx + 0x48]\n\t"
        "%{disp32%} mov ecx, dword ptr [esi + 0x00000118]\n\t"
        "push esi\n\t"
        "call _jmp_addr_0x005283e0\n"
        "0:\n\t"
        "mov eax, 0x00000001\n\t"
        "pop esi"
        : "=a"(result) : "S"(self) : "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves))
bool32_t __fastcall ExitFarming__8VillagerFUc(struct Villager* this, const void* edx, unsigned char param_1)
{
    bool32_t result;
    register struct Villager* self asm("esi");
    asm volatile ("push esi\n\tmov.s esi, ecx" : "=r"(self) : "c"(this) : "memory");
    asm volatile (
        "%{disp8%} mov ecx, dword ptr [esp + 0x08]\n\t"
        "mov eax, dword ptr [esi]\n\t"
        "and ecx, 0x000000ff\n\t"
        "push ecx\n\t"
        "mov.s ecx, esi\n\t"
        "call dword ptr [eax + 0x96c]\n\t"
        "test eax, eax\n\t"
        "%{disp8%} jne 2f\n\t"
        "%{disp32%} mov eax, dword ptr [esi + 0x00000118]\n\t"
        "test eax, eax\n\t"
        "%{disp8%} je 2f\n\t"
        "mov edx, dword ptr [esi]\n\t"
        "mov.s ecx, esi\n\t"
        "call dword ptr [edx + 0x48]\n\t"
        "%{disp32%} mov eax, dword ptr [_game]\n\t"
        "%{disp32%} mov eax, dword ptr [eax + 0x00205c04]\n\t"
        "test eax, eax\n\t"
        "%{disp32%} mov ecx, dword ptr [esi + 0x00000118]\n\t"
        "%{disp8%} je 2f\n"
        "LAB_EF_loop:\n\t"
        "cmp.s eax, ecx\n\t"
        "%{disp8%} je 3f\n\t"
        "%{disp32%} mov eax, dword ptr [eax + 0x000000c4]\n\t"
        "test eax, eax\n\t"
        "%{disp8%} jne LAB_EF_loop\n\t"
        "mov eax, 0x00000001\n\t"
        "pop esi\n\t"
        "ret 0x0004\n"
        "3:\n\t"
        "test eax, eax\n\t"
        "%{disp8%} je 2f\n\t"
        "push esi\n\t"
        "call _jmp_addr_0x00528340\n"
        "2:\n\t"
        "mov eax, 0x00000001\n\t"
        "pop esi"
        : "=a"(result) : "S"(self) : "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV))
void __fastcall Remove__31LHOrderedLinkedList_9Glocation_Fv(struct LHOrderedLinkedList__Glocation* this, const void* edx, struct Glocation* param_1)
{
    asm volatile (
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              eax, edx\n\t"
        "xor.s              ecx, ecx\n\t"
        "test               eax, eax\n\t"
        "push               edi\n\t"
        "%{disp8%} je         LAB__addr_0x0075a32f\n\t"
        "%{disp8%} mov        edi, dword ptr [esp + 0x0c]\n"
        "LAB__addr_0x0075a322:\n\t"
        "cmp                dword ptr [eax], edi\n\t"
        "%{disp8%} je         LAB__addr_0x0075a336\n\t"
        "mov.s              ecx, eax\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x04]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0075a322\n"
        "LAB__addr_0x0075a32f:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "xor.s              eax, eax\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x0075a336:\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} jne        LAB__addr_0x0075a341\n\t"
        "%{disp8%} mov        ecx, dword ptr [edx + 0x04]\n\t"
        "mov                dword ptr [esi], ecx\n\t"
        "%{disp8%} jmp        LAB__addr_0x0075a347\n"
        "LAB__addr_0x0075a341:\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x04]\n\t"
        "%{disp8%} mov        dword ptr [ecx + 0x04], edx\n"
        "LAB__addr_0x0075a347:\n\t"
        "push               eax\n\t"
        "call               ??3@YAXPAX@Z\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x04]\n\t"
        "add                esp, 0x04\n\t"
        "dec                eax\n\t"
        "pop                edi\n\t"
        "%{disp8%} mov        dword ptr [esi + 0x04], eax\n\t"
        "pop                esi\n\t"
        "mov                eax, 0x00000001"
        ::: "eax", "ecx", "edx", "memory"
    );
}
