#include "Villager.h"

extern float rdata_float0p5;

const float rdata_float10p0_0x0099a924 = 10.0f;
const float rdata_float_pi_0x0099a928 = 3.1415927f;
const float villager_check_num_days_in_year_0x0099a92c = 365.25f;
const float villager_check_seconds_in_day_0x0099a930 = 86400.0f;

__attribute__((section(".bss"))) struct
{
    float seconds_in_year_0x00db9dc0;
    float float_0x00db9dc4;
    float float_0x00db9dc8;
    struct Villager* villager_0x00db9dcc;
} VillagerCheck_bss_globals;

__attribute__((no_ret))
void __cdecl globl_ct_0x00756c80(void)
{
    asm volatile (
        "%{disp32%} mov cl, byte ptr [_DAT_00fac934]\n\t"
        "mov al, 0x01\n\t"
        "test al, cl\n\t"
        "%{disp8%} jne LAB__addr_0x00756c94\n\t"
        "or.s cl, al\n\t"
        "%{disp32%} mov byte ptr [_DAT_00fac934], cl\n"
        "LAB__addr_0x00756c94:\n\t"
        "%{disp32%} jmp _crt_global_destruction_register_0x00756ca0"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

void __cdecl crt_global_destruction_register_0x00756ca0(void)
{
    asm volatile (
        "push               0x00407870\n\t"
        "call               _atexit\n\t"
        "pop                ecx"
        ::: "eax", "ecx", "edx", "memory"
    );
}

extern void __cdecl FUN_00756cc0__8VillagerFv(void) __attribute__((noinline));

void __cdecl globl_ct_0x00756cb0(void)
{
    __attribute__((musttail)) return FUN_00756cc0__8VillagerFv();
}

void __cdecl FUN_00756cc0__8VillagerFv(void)
{
    VillagerCheck_bss_globals.float_0x00db9dc4 = 0.125f;
}

extern void __cdecl FUN_00756ce0__8VillagerFv(void) __attribute__((noinline));

void __cdecl globl_ct_0x00756cd0(void)
{
    __attribute__((musttail)) return FUN_00756ce0__8VillagerFv();
}

void __cdecl FUN_00756ce0__8VillagerFv(void)
{
    asm volatile (
        "%{disp32%} fld       dword ptr [_rdata_float_pi_0x0099a928]\n\t"
        "%{disp32%} fmul      dword ptr [_rdata_float0p5]\n\t"
        "%{disp32%} fstp      dword ptr [_VillagerCheck_bss_globals + 8]"
        ::: "memory"
    );
}

extern void __cdecl FUN_00756d10__8VillagerFv(void) __attribute__((noinline));

void __cdecl globl_ct_0x00756d00(void)
{
    __attribute__((musttail)) return FUN_00756d10__8VillagerFv();
}

void __cdecl FUN_00756d10__8VillagerFv(void)
{
    asm volatile (
        "%{disp32%} fld  dword ptr [_villager_check_seconds_in_day_0x0099a930]\n\t"
        "%{disp32%} fmul dword ptr [_villager_check_num_days_in_year_0x0099a92c]\n\t"
        "%{disp32%} fstp dword ptr [_VillagerCheck_bss_globals + 0]"
        ::: "memory"
    );
}

__attribute__((no_callee_saves))
void __fastcall InteractDecideWhatToDoForOtherVillager__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "sub                esp, 0x14\n\t"
        "push               ebp\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "mov.s              edi, ecx\n\t"
        "%{disp8%} lea        eax, dword ptr [edi + 0x14]\n\t"
        "mov                ecx, dword ptr [eax]\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x04]\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x08]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], edx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x1c], eax\n\t"
        "mov                ebp, 0x00000009\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], 0x00000001\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x0c], 0x00000001\n"
        "LAB__addr_0x00756d64:\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x14]\n\t"
        "call               ?GetFirstObjectFixed@MapCoords@@QBEPAVObject@@XZ\n\t"
        "mov.s              esi, eax\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x00756dc6\n"
        "LAB__addr_0x00756d73:\n\t"
        "cmp.s              esi, edi\n\t"
        "%{disp8%} je         LAB__addr_0x00756db4\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x2c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00756db4\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x208]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00756db4\n\t"
        "push               0x0\n\t"
        "push               0x009c7fa0\n\t"
        "push               0x009c7f50\n\t"
        "push               0x0\n\t"
        "push               esi\n\t"
        "call               ___RTDynamicCast\n\t"
        "add                esp, 0x14\n\t"
        "push               eax\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?CheckMoveHouse@Villager@@QAEIPAVObject@@@Z\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x00756dfc\n"
        "LAB__addr_0x00756db4:\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x14]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               @GetMapChild__6ObjectFRC9MapCoords@12\n\t"
        "mov.s              esi, eax\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} jne        LAB__addr_0x00756d73\n"
        "LAB__addr_0x00756dc6:\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x0c]\n\t"
        "push               edx\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x14]\n\t"
        "push               eax\n\t"
        "dec                ebp\n\t"
        "call               ?Spiral@GUtils@@SAPBUJustMapXZ@@AAJ0@Z\n\t"
        "add                esp, 0x08\n\t"
        "push               eax\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x18]\n\t"
        "call               @__apl__9MapCoordsFRC9JustMapXZ@12\n\t"
        "test               ebp, ebp\n\t"
        "%{disp32%} jne       LAB__addr_0x00756d64\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x8c8]\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "add                esp, 0x14\n\t"
        "ret\n"
        "LAB__addr_0x00756dfc:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebp\n\t"
        "add                esp, 0x14"
        :: "c"(this) : "eax", "edx", "memory"
    );
}

__attribute__((no_ret))
void __fastcall InteractDecideWhatToDo__8VillagerFv(struct Villager* this)
{
    asm volatile (
        "mov eax, dword ptr [ecx]\n\t"
        "jmp dword ptr [eax + 0x8c8]"
        : : "c"(this) : "eax", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((no_callee_saves, XOR32rr_REV, trailing_asm(".byte 0x8b, 0xff\n.byte 0x35, 0x6e, 0x75, 0x00\n.byte 0x3b, 0x6e, 0x75, 0x00\n.byte 0x41, 0x6e, 0x75, 0x00\n.byte 0x4d, 0x6e, 0x75, 0x00\n.byte 0x47, 0x6e, 0x75, 0x00\n.byte 0x53, 0x6e, 0x75, 0x00\n.byte 0x4d, 0x6e, 0x75, 0x00\n.byte 0x4d, 0x6e, 0x75, 0x00\n.byte 0x53, 0x6e, 0x75, 0x00\n.byte 0x4d, 0x6e, 0x75, 0x00")))
uint32_t __fastcall GetDiscipleInteractState__8VillagerFv(struct Villager* this)
{
    asm("xor.s              eax, eax");                                      // 0x00756e20    33c0
    asm("{disp32} mov       al, byte ptr [ecx + 0x000000f2]");               // 0x00756e22    8a81f2000000
    asm("dec                eax");                                           // 0x00756e28    48
    asm("cmp                eax, 0x09");                                     // 0x00756e29    83f809
    asm("{disp8} ja         LAB__addr_0x00756e53");                          // 0x00756e2c    7725
    asm("jmp                dword ptr [eax*4 + 0x756e58]");                  // 0x00756e2e    ff2485586e7500
    asm("mov                eax, 0x000000ad");                               // 0x00756e35    b8ad000000
    asm("ret");                                                              // 0x00756e3a    c3
    asm("mov                eax, 0x000000af");                               // 0x00756e3b    b8af000000
    asm("ret");                                                              // 0x00756e40    c3
    asm("mov                eax, 0x000000ae");                               // 0x00756e41    b8ae000000
    asm("ret");                                                              // 0x00756e46    c3
    asm("mov                eax, 0x000000b3");                               // 0x00756e47    b8b3000000
    asm("ret");                                                              // 0x00756e4c    c3
    asm("mov                eax, 0x000000ac");                               // 0x00756e4d    b8ac000000
    asm("ret");                                                              // 0x00756e52    c3
    asm("LAB__addr_0x00756e53:");
    asm("xor.s              eax, eax");                                      // 0x00756e53    33c0
    // Snippet: db, [0x00756e56, 0x00756e58)
    // Snippet: jmptbl, [0x00756e58, 0x00756e80)
}

__attribute__((no_callee_saves, XOR32rr_REV))
bool32_t __fastcall FindCloseObjectsForInteract__8VillagerFP35LHOrderedLinkedList_12SortedObject_RC9MapCoords(struct Villager* this, const void* edx, struct LHOrderedLinkedList__SortedObject* param_1, const struct MapCoords* param_2)
{
    bool32_t result;
    asm volatile (
        "sub                esp, 0x48\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x50]\n\t"
        "push               ebx\n\t"
        "%{disp8%} mov        ebx, dword ptr [esp + 0x50]\n\t"
        "test               ebx, ebx\n\t"
        "push               ebp\n\t"
        "mov.s              ebp, ecx\n\t"
        "mov                ecx, dword ptr [eax]\n\t"
        "%{disp8%} mov        edx, dword ptr [eax + 0x04]\n\t"
        "%{disp8%} mov        eax, dword ptr [eax + 0x08]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x2c], ebp\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x44], ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x48], edx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x4c], eax\n\t"
        "%{disp8%} jne        LAB__addr_0x00756eb5\n\t"
        "pop                ebp\n\t"
        "xor.s              eax, eax\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x48\n\t"
        "ret                0x0008\n"
        "LAB__addr_0x00756eb5:\n\t"
        "push               esi\n\t"
        "mov                eax, 0x00000001\n\t"
        "push               edi\n\t"
        "%{disp32%} mov       dword ptr [_VillagerCheck_bss_globals + 0xc], ebp\n\t"
        "xor.s              esi, esi\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x3c], eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x38], eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x20], 0x00000009\n"
        "LAB__addr_0x00756ed4:\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x4c]\n\t"
        "call               ?InBounds@MapCoords@@QBEIXZ\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x00757148\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x40]\n\t"
        "push               ecx\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x50]\n\t"
        "call               @GetFirstIterator__9MapCoordsCFv@12\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x40]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp32%} je        LAB__addr_0x00757148\n"
        "LAB__addr_0x00756eff:\n\t"
        "cmp.s              ecx, ebp\n\t"
        "%{disp32%} je        LAB__addr_0x0075710b\n\t"
        "mov                edx, dword ptr [ecx]\n\t"
        "call               dword ptr [edx + 0x2c]\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x00757107\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x40]\n\t"
        "%{disp32%} mov       edx, dword ptr [_VillagerCheck_bss_globals + 0xc]\n\t"
        "mov                eax, dword ptr [ecx]\n\t"
        "push               edx\n\t"
        "mov.s              edi, ecx\n\t"
        "call               dword ptr [eax + 0x6c4]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float0p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp8%} jne        LAB__addr_0x00756f4d\n\t"
        "%{disp32%} mov       ecx, dword ptr [_VillagerCheck_bss_globals + 0xc]\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x6c4]\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x14]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00756f55\n"
        "LAB__addr_0x00756f4d:\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], 0x00000000\n"
        "LAB__addr_0x00756f55:\n\t"
        "%{disp8%} mov        edx, dword ptr [edi + 0x28]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x14]\n\t"
        "%{disp32%} mov       eax, dword ptr [edx + 0x000000e0]\n\t"
        "push               0x40c00000\n\t"
        "push               ecx\n\t"
        "%{disp32%} mov       ecx, dword ptr [_VillagerCheck_bss_globals + 0xc]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x2c], eax\n\t"
        "call               _jmp_addr_0x005eca20\n\t"
        "%{disp8%} fmul       dword ptr [esp + 0x24]\n\t"
        "%{disp8%} fst        dword ptr [esp + 0x10]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float0p001]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp32%} jne       LAB__addr_0x00757107\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x10]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x60]\n\t"
        "push               0x3f800000\n\t"
        "push               edx\n\t"
        "%{disp8%} lea        eax, dword ptr [edi + 0x14]\n\t"
        "push               eax\n\t"
        "push               ecx\n\t"
        "push               0xb\n\t"
        "call               _jmp_addr_0x00648290\n\t"
        "push               0x8\n\t"
        "call               ??2@YAPAXI@Z\n\t"
        "xor.s              ebp, ebp\n\t"
        "add                esp, 0x18\n\t"
        "cmp.s              eax, ebp\n\t"
        "%{disp8%} je         LAB__addr_0x00756fc5\n\t"
        "mov                dword ptr [eax], edi\n\t"
        "%{disp8%} mov        dword ptr [eax + 0x04], ebp\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], eax\n\t"
        "%{disp8%} jmp        LAB__addr_0x00756fc9\n"
        "LAB__addr_0x00756fc5:\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], ebp\n"
        "LAB__addr_0x00756fc9:\n\t"
        "mov                esi, dword ptr [ebx]\n\t"
        "cmp.s              esi, ebp\n\t"
        "%{disp32%} je        LAB__addr_0x007570de\n"
        "LAB__addr_0x00756fd3:\n\t"
        "%{disp32%} mov       eax, dword ptr [_VillagerCheck_bss_globals + 0xc]\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov                ebx, dword ptr [esi]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x6c4]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float0p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp8%} jne        LAB__addr_0x00757008\n\t"
        "%{disp32%} mov       eax, dword ptr [_VillagerCheck_bss_globals + 0xc]\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x6c4]\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x18]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00757010\n"
        "LAB__addr_0x00757008:\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x18], 0x00000000\n"
        "LAB__addr_0x00757010:\n\t"
        "%{disp8%} mov        ecx, dword ptr [edi + 0x28]\n\t"
        "%{disp32%} mov       edx, dword ptr [ecx + 0x000000e0]\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x18]\n\t"
        "%{disp32%} mov       ecx, dword ptr [_VillagerCheck_bss_globals + 0xc]\n\t"
        "push               0x40c00000\n\t"
        "push               eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x34], edx\n\t"
        "call               _jmp_addr_0x005eca20\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x28]\n\t"
        "%{disp32%} mov       eax, dword ptr [_VillagerCheck_bss_globals + 0xc]\n\t"
        "mov                edx, dword ptr [ebx]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, ebx\n\t"
        "call               dword ptr [edx + 0x6c4]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float0p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp8%} jne        LAB__addr_0x00757069\n\t"
        "%{disp32%} mov       eax, dword ptr [_VillagerCheck_bss_globals + 0xc]\n\t"
        "mov                edx, dword ptr [ebx]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, ebx\n\t"
        "call               dword ptr [edx + 0x6c4]\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x1c]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00757071\n"
        "LAB__addr_0x00757069:\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x1c], 0x00000000\n"
        "LAB__addr_0x00757071:\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x28]\n\t"
        "%{disp8%} mov        ecx, dword ptr [ebx + 0x28]\n\t"
        "%{disp8%} fmul       dword ptr [esp + 0x2c]\n\t"
        "%{disp32%} mov       edx, dword ptr [ecx + 0x000000e0]\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x1c]\n\t"
        "%{disp32%} mov       ecx, dword ptr [_VillagerCheck_bss_globals + 0xc]\n\t"
        "push               0x40c00000\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x2c]\n\t"
        "push               eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x38], edx\n\t"
        "call               _jmp_addr_0x005eca20\n\t"
        "%{disp8%} fmul       dword ptr [esp + 0x30]\n\t"
        "%{disp8%} fcomp      dword ptr [esp + 0x28]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x007570bc\n\t"
        "mov.s              ebp, esi\n\t"
        "%{disp8%} mov        esi, dword ptr [esi + 0x04]\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x007570d6\n\t"
        "%{disp32%} jmp       LAB__addr_0x00756fd3\n"
        "LAB__addr_0x007570bc:\n\t"
        "test               ebp, ebp\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x10]\n\t"
        "%{disp8%} mov        dword ptr [eax + 0x04], esi\n\t"
        "%{disp8%} jne        LAB__addr_0x007570cf\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x5c]\n\t"
        "mov                dword ptr [ecx], eax\n\t"
        "%{disp8%} jmp        LAB__addr_0x007570d2\n"
        "LAB__addr_0x007570cf:\n\t"
        "%{disp8%} mov        dword ptr [ebp + 0x04], eax\n"
        "LAB__addr_0x007570d2:\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} jne        LAB__addr_0x007570ed\n"
        "LAB__addr_0x007570d6:\n\t"
        "test               ebp, ebp\n\t"
        "%{disp8%} jne        LAB__addr_0x007570e6\n\t"
        "%{disp8%} mov        ebx, dword ptr [esp + 0x5c]\n"
        "LAB__addr_0x007570de:\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x10]\n\t"
        "mov                dword ptr [ebx], edx\n\t"
        "%{disp8%} jmp        LAB__addr_0x007570f1\n"
        "LAB__addr_0x007570e6:\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x10]\n\t"
        "%{disp8%} mov        dword ptr [ebp + 0x04], eax\n"
        "LAB__addr_0x007570ed:\n\t"
        "%{disp8%} mov        ebx, dword ptr [esp + 0x5c]\n"
        "LAB__addr_0x007570f1:\n\t"
        "%{disp8%} mov        eax, dword ptr [ebx + 0x04]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x40]\n\t"
        "%{disp8%} mov        ebp, dword ptr [esp + 0x34]\n\t"
        "inc                eax\n\t"
        "%{disp8%} mov        dword ptr [ebx + 0x04], eax\n\t"
        "mov                esi, 0x00000001\n\t"
        "%{disp8%} jmp        LAB__addr_0x0075710b\n"
        "LAB__addr_0x00757107:\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x40]\n"
        "LAB__addr_0x0075710b:\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x48]\n\t"
        "mov                edx, dword ptr [ecx]\n\t"
        "push               eax\n\t"
        "call               dword ptr [edx + 0x53c]\n\t"
        "mov.s              ecx, eax\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x40], ecx\n\t"
        "%{disp32%} jne       LAB__addr_0x00756eff\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x44]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00757148\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x48]\n\t"
        "mov                ecx, dword ptr [ecx]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x40], ecx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x44], 0x00000000\n\t"
        "%{disp32%} jne       LAB__addr_0x00756eff\n"
        "LAB__addr_0x00757148:\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x38]\n\t"
        "push               edx\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x40]\n\t"
        "push               eax\n\t"
        "call               ?Spiral@GUtils@@SAPBUJustMapXZ@@AAJ0@Z\n\t"
        "add                esp, 0x08\n\t"
        "push               eax\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x50]\n\t"
        "call               @__apl__9MapCoordsFRC9JustMapXZ@12\n\t"
        "dec                dword ptr [esp + 0x20]\n\t"
        "%{disp32%} jne       LAB__addr_0x00756ed4\n\t"
        "pop                edi\n\t"
        "mov.s              eax, esi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x48"
        : "=a"(result) : "c"(this) : "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV))
bool32_t __fastcall CheckMoveHouse__8VillagerFP6Object(struct Villager* this, const void* edx, struct Object* object)
{
    bool32_t result;
    asm volatile (
        "%{disp8%} mov        eax, dword ptr [esp + 0x04]\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "push               0x0\n\t"
        "push               0x009c7fa0\n\t"
        "push               0x009c7f50\n\t"
        "push               0x0\n\t"
        "push               eax\n\t"
        "mov.s              edi, ecx\n\t"
        "call               ___RTDynamicCast\n\t"
        "mov.s              esi, eax\n\t"
        "add                esp, 0x14\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x00757200\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0xaf8]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x007571bf\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x8a0]\n\t"
        "%{disp8%} jmp        LAB__addr_0x007571c9\n"
        "LAB__addr_0x007571bf:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x89c]\n"
        "LAB__addr_0x007571c9:\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float1p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x007571e8\n\t"
        "push               esi\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?ForceMoveVillagerToAbode@Villager@@QAEXPAVAbode@@@Z\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x007571e8:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00757200\n\t"
        "push               eax\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?CheckMoveIntoTown@Villager@@QAEIAAVTown@@@Z\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x00757200:\n\t"
        "pop                edi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi"
        : "=a"(result) : "c"(this) : "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV))
bool32_t __fastcall CheckMoveIntoTown__8VillagerFR4Town(struct Villager* this, const void* edx, struct Town* param_1)
{
    bool32_t result;
    asm volatile (
        "push               esi\n\t"
        "%{disp8%} mov        esi, dword ptr [esp + 0x08]\n\t"
        "push               edi\n\t"
        "mov.s              edi, ecx\n\t"
        "push               0x0\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?FindAbodeWithSpaceInTown@Town@@QAEPAVAbode@@PAVVillager@@M@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x00757245\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?IsSpaceForNewVillager@Town@@QAE_NXZ\n\t"
        "test               al, al\n\t"
        "%{disp8%} je         LAB__addr_0x00757257\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x000009a4]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x00757245\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x00000754]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00757257\n"
        "LAB__addr_0x00757245:\n\t"
        "push               eax\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?ForceMoveVillagerToAbode@Villager@@QAEXPAVAbode@@@Z\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x00757257:\n\t"
        "pop                edi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi"
        : "=a"(result) : "c"(this) : "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall CheckInteractWithAnimal__8VillagerFv(struct Villager* this)
{
    return 0;
}

__attribute__((no_callee_saves, XOR32rr_REV))
bool32_t __fastcall CheckInteractWithWorshipSite__8VillagerFv(struct Villager* this)
{
    bool32_t result;
    asm volatile (
        "sub                esp, 0x08\n\t"
        "push               ebx\n\t"
        "push               ebp\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "push               0x0\n\t"
        "push               0x009c7f80\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x00000118]\n\t"
        "push               0x009c7f50\n\t"
        "push               0x0\n\t"
        "push               eax\n\t"
        "call               ___RTDynamicCast\n\t"
        "mov.s              edi, eax\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "add                esp, 0x14\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x890]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x007572bd\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x8d8]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float0p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp8%} jne        LAB__addr_0x0075730f\n"
        "LAB__addr_0x007572bd:\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x1c]\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "mov.s              ebx, eax\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "cmp.s              ebx, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0075730f\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?SetupBuildingObject@Villager@@QAEIPAVMultiMapFixed@@@Z\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x0075730f\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x1c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00757302\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "%{disp8%} lea        ecx, dword ptr [esi + 0x14]\n\t"
        "push               ecx\n\t"
        "push               0x3f000000\n\t"
        "push               0x9\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x004c80f0\n"
        "LAB__addr_0x00757302:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x08\n\t"
        "ret\n"
        "LAB__addr_0x0075730f:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "mov.s              ebp, eax\n\t"
        "test               ebp, ebp\n\t"
        "%{disp32%} je        LAB__addr_0x0075740f\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x30c]\n\t"
        "mov.s              edi, eax\n\t"
        "test               edi, edi\n\t"
        "%{disp32%} je        LAB__addr_0x0075740f\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "%{disp32%} mov       ebx, dword ptr [esi + 0x00000118]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x1c]\n\t"
        "mov.s              edx, eax\n\t"
        "mov                eax, dword ptr [ebx]\n\t"
        "mov.s              ecx, ebx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], edx\n\t"
        "call               dword ptr [eax + 0x1c]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x10]\n\t"
        "cmp.s              eax, ecx\n\t"
        "%{disp32%} jne       LAB__addr_0x0075740f\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0xd4]\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x0075740f\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x1c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00757390\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "%{disp8%} lea        ecx, dword ptr [esi + 0x14]\n\t"
        "push               ecx\n\t"
        "push               0x3f000000\n\t"
        "push               0x7\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x004c80f0\n"
        "LAB__addr_0x00757390:\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?CheckNeededForWorship@Villager@@QAEMXZ\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x007573a4\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x08\n\t"
        "ret\n"
        "LAB__addr_0x007573a4:\n\t"
        "%{disp32%} mov       eax, dword ptr [ebp + 0x0000061c]\n\t"
        "add                eax, dword ptr [ebp + 0x00000618]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], 0x00000000\n\t"
        "%{disp8%} fild       qword ptr [esp + 0x10]\n\t"
        "%{disp32%} fdivr     qword ptr [__real@8@3fff8000000000000000]\n\t"
        "%{disp32%} fadd      dword ptr [ebp + 0x000005c0]\n\t"
        "%{disp8%} fst        dword ptr [esp + 0x10]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float1p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp8%} je         LAB__addr_0x007573fb\n\t"
        "mov.s              ecx, ebp\n\t"
        "call               ?GetTotemStatue@Town@@QAEPAVTotemStatue@@XZ\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x007573fb\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x10]\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, ebp\n\t"
        "call               ?GetTotemStatue@Town@@QAEPAVTotemStatue@@XZ\n\t"
        "mov.s              ecx, eax\n\t"
        "call               @SetWorshipPercentage__11TotemStatueFf@12\n"
        "LAB__addr_0x007573fb:\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?CheckNeededForWorship@Villager@@QAEMXZ\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x0075740f\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x08\n\t"
        "ret\n"
        "LAB__addr_0x0075740f:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebp\n\t"
        "xor.s              eax, eax\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x08"
        : "=a"(result) : "c"(this) : "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV))
bool32_t __fastcall CheckInteractWithAbode__8VillagerFv(struct Villager* this)
{
    bool32_t result;
    asm volatile (
        "push               ebx\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "push               0x0\n\t"
        "push               0x009c7f80\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x00000118]\n\t"
        "push               0x009c7f50\n\t"
        "push               0x0\n\t"
        "push               eax\n\t"
        "call               ___RTDynamicCast\n\t"
        "mov.s              edi, eax\n\t"
        "add                esp, 0x14\n\t"
        "test               edi, edi\n\t"
        "%{disp32%} je        LAB__addr_0x0075757d\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x2c]\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} je        LAB__addr_0x0075757d\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x890]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00757480\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x8d8]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float0p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp8%} jne        LAB__addr_0x007574fb\n"
        "LAB__addr_0x00757480:\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "mov.s              ebx, eax\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x1c]\n\t"
        "cmp.s              ebx, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x007574fb\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "mov.s              ebx, eax\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x48]\n\t"
        "cmp.s              eax, ebx\n\t"
        "%{disp8%} je         LAB__addr_0x007574be\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x1e0]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x007574fb\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?ForceMoveVillagerToAbode@Villager@@QAEXPAVAbode@@@Z\n"
        "LAB__addr_0x007574be:\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?SetupBuildingObject@Villager@@QAEIPAVMultiMapFixed@@@Z\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x007574ed\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "%{disp8%} lea        eax, dword ptr [esi + 0x14]\n\t"
        "push               eax\n\t"
        "push               0x3f000000\n\t"
        "push               0x5\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x004c80f0\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebx\n\t"
        "ret\n"
        "LAB__addr_0x007574ed:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x8c8]\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebx\n\t"
        "ret\n"
        "LAB__addr_0x007574fb:\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?CheckMoveHouse@Villager@@QAEIPAVObject@@@Z\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x0075750c\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebx\n\t"
        "ret\n"
        "LAB__addr_0x0075750c:\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "mov.s              ebx, eax\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x1c]\n\t"
        "cmp.s              ebx, eax\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "%{disp8%} je         LAB__addr_0x00757545\n\t"
        "call               dword ptr [edx + 0x48]\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x0000011c], eax\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x000000a3\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x8e8]\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebx\n\t"
        "ret\n"
        "LAB__addr_0x00757545:\n\t"
        "call               dword ptr [edx + 0x310]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00757567\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x000000a3\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x8e8]\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebx\n\t"
        "ret\n"
        "LAB__addr_0x00757567:\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GetAbode@Villager@@QAEPAVAbode@@XZ\n\t"
        "cmp.s              edi, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x0075757d\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?GoHome@Villager@@QAEIXZ\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "pop                ebx\n\t"
        "ret\n"
        "LAB__addr_0x0075757d:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                ebx"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV))
bool32_t __fastcall CheckInteractWithField__8VillagerFv(struct Villager* this)
{
    bool32_t result;
    asm volatile (
        "push               ebx\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "push               0x0\n\t"
        "push               0x00be9d68\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x00000118]\n\t"
        "push               0x009c7f50\n\t"
        "push               0x0\n\t"
        "push               eax\n\t"
        "call               ___RTDynamicCast\n\t"
        "mov.s              edi, eax\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "add                esp, 0x14\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x1c]\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "mov.s              ebx, eax\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "cmp.s              ebx, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x00757604\n\t"
        "push               0x1\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?SetFarmerGotoField@Villager@@QAEIPAVField@@H@Z\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x00757604\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x1c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x007575fb\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "%{disp8%} lea        ecx, dword ptr [esi + 0x14]\n\t"
        "push               ecx\n\t"
        "push               0x3f000000\n\t"
        "push               0x0\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x004c80f0\n"
        "LAB__addr_0x007575fb:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebx\n\t"
        "ret\n"
        "LAB__addr_0x00757604:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                ebx"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves, XOR32rr_REV))
bool32_t __fastcall CheckInteractWithFishFarm__8VillagerFv(struct Villager* this)
{
    bool32_t result;
    asm volatile (
        "push               ebx\n\t"
        "push               esi\n\t"
        "push               edi\n\t"
        "push               0x0\n\t"
        "push               0x009d97c8\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x00000118]\n\t"
        "push               0x009c7f50\n\t"
        "push               0x0\n\t"
        "push               eax\n\t"
        "call               ___RTDynamicCast\n\t"
        "mov.s              edi, eax\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "add                esp, 0x14\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x1c]\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "mov.s              ebx, eax\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "cmp.s              ebx, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x00757682\n\t"
        "push               edi\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?VillagerBecomesFisherman@Villager@@QAEIPAVFishFarm@@@Z\n\t"
        "cmp                eax, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x00757682\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x1c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00757679\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "%{disp8%} lea        ecx, dword ptr [esi + 0x14]\n\t"
        "push               ecx\n\t"
        "push               0x3f000000\n\t"
        "push               0x0\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x004c80f0\n"
        "LAB__addr_0x00757679:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                ebx\n\t"
        "ret\n"
        "LAB__addr_0x00757682:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                ebx"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves))
bool32_t __fastcall CheckInteractWithTree__8VillagerFv(struct Villager* this)
{
    bool32_t result;
    asm volatile (
        "push               ecx\n\t"
        "push               esi\n\t"
        "push               0x0\n\t"
        "push               0x009d96e0\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x00000118]\n\t"
        "push               0x009c7f50\n\t"
        "push               0x0\n\t"
        "push               eax\n\t"
        "call               ___RTDynamicCast\n\t"
        "add                esp, 0x14\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x04], eax\n\t"
        "%{disp8%} je         LAB__addr_0x00757703\n\t"
        "%{disp8%} lea        eax, dword ptr [esp + 0x04]\n\t"
        "push               eax\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?FindTreeNearVillager@Villager@@QAEIPAPAVTree@@@Z\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00757703\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x007576ed\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "%{disp8%} lea        eax, dword ptr [esi + 0x14]\n\t"
        "push               eax\n\t"
        "push               0x3f000000\n\t"
        "push               0x1\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "mov.s              ecx, eax\n\t"
        "call               _jmp_addr_0x004c80f0\n"
        "LAB__addr_0x007576ed:\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "push               0x31\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0x8e8]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?ForesterArrivesAtForest@Villager@@QAEIXZ\n\t"
        "pop                esi\n\t"
        "pop                ecx\n\t"
        "ret\n"
        "LAB__addr_0x00757703:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               0x000000a4\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x8e8]\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "pop                ecx"
        : "=a"(result) : "c"(this) : "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall CheckInteractWithBall__8VillagerFv(struct Villager* this)
{
    return 0;
}

bool32_t __fastcall CheckInteractWithPot__8VillagerFv(struct Villager* this)
{
    return 1;
}

bool32_t __fastcall CheckInteractWithRock__8VillagerFv(struct Villager* this)
{
    return 1;
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall CheckInteractWithFootBall__8VillagerFv(struct Villager* this)
{
    return 0;
}

__attribute__((no_callee_saves, XOR32rr_REV))
bool32_t __fastcall CheckInteractWithVillager__8VillagerFv(struct Villager* this)
{
    bool32_t result;
    asm volatile (
        "push               esi\n\t"
        "push               edi\n\t"
        "push               0x0\n\t"
        "push               0x009cafc8\n\t"
        "mov.s              edi, ecx\n\t"
        "%{disp32%} mov       eax, dword ptr [edi + 0x00000118]\n\t"
        "push               0x009c7f50\n\t"
        "push               0x0\n\t"
        "push               eax\n\t"
        "call               ___RTDynamicCast\n\t"
        "mov.s              esi, eax\n\t"
        "add                esp, 0x14\n\t"
        "test               esi, esi\n\t"
        "%{disp32%} je        LAB__addr_0x00757816\n\t"
        "mov                eax, dword ptr [esi]\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [eax + 0xd4]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00757816\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "push               ebx\n\t"
        "mov.s              ecx, esi\n\t"
        "call               dword ptr [edx + 0x1c]\n\t"
        "mov.s              ebx, eax\n\t"
        "mov                eax, dword ptr [edi]\n\t"
        "mov.s              ecx, edi\n\t"
        "call               dword ptr [eax + 0x1c]\n\t"
        "cmp.s              ebx, eax\n\t"
        "pop                ebx\n\t"
        "%{disp8%} jne        LAB__addr_0x007577fc\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?IsSexuallyActive@Villager@@QAEIXZ\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x007577fc\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?IsSexuallyActive@Villager@@QAEIXZ\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x007577fc\n\t"
        "%{disp8%} mov        edx, dword ptr [edi + 0x28]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x28]\n\t"
        "%{disp32%} mov       eax, dword ptr [edx + 0x000001f8]\n\t"
        "cmp                eax, dword ptr [ecx + 0x000001f8]\n\t"
        "%{disp8%} je         LAB__addr_0x007577fc\n\t"
        "push               0x3f0fdf3b\n\t"
        "push               0x7a\n\t"
        "push               esi\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?MakeVillagesMeet@Villager@@QAEIPAV1@W4VILLAGER_STATES@@M@Z\n\t"
        "%{disp32%} mov       dword ptr [edi + 0x00000118], esi\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000118], edi\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x007577fc:\n\t"
        "push               0x40400000\n\t"
        "push               0x000000a9\n\t"
        "push               esi\n\t"
        "mov.s              ecx, edi\n\t"
        "call               ?MakeVillagesMeet@Villager@@QAEIPAV1@W4VILLAGER_STATES@@M@Z\n\t"
        "pop                edi\n\t"
        "mov                eax, 0x00000001\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x00757816:\n\t"
        "pop                edi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                esi"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((no_callee_saves))
void __fastcall SetDiscipleFollower__8VillagerF17VILLAGER_DISCIPLE(struct Villager* this, const void* edx, enum VILLAGER_DISCIPLE param_1)
{
    asm volatile (
        "%{disp8%} mov        al, byte ptr [esp + 0x04]\n\t"
        "mov                edx, dword ptr [ecx]\n\t"
        "or                 byte ptr [ecx + 0xe1], 4\n\t"
        "push               0x000000a3\n\t"
        "%{disp32%} mov       byte ptr [ecx + 0x000000f2], al\n\t"
        "call               dword ptr [edx + 0x8e8]"
        :: "c"(this) : "eax", "edx", "memory"
    );
}

__attribute__((XOR32rr_REV))
bool32_t __fastcall CheckInteractWithMagicLiving__8VillagerFv(struct Villager* this)
{
    return 0;
}
