#include "VillagerNames.h"

char s_Villagernames_cpp[] = "C:\\dev\\MP\\Black\\villagernames.cpp";

struct VillagerNameBlock* CurrentVillagerNameBlock;
void* PTR_00db9e28;

void __cdecl globl_ct_0x007626f0(void)
{
    asm volatile (
        "%{disp32%} mov cl, byte ptr [_DAT_00fac934]\n\t"
        "mov al, 0x01\n\t"
        "test al, cl\n\t"
        "%{disp8%} jne LAB__addr_0x00762704\n\t"
        "or.s cl, al\n\t"
        "%{disp32%} mov byte ptr [_DAT_00fac934], cl\n"
        "LAB__addr_0x00762704:\n\t"
        "%{disp32%} jmp _crt_global_destruction_register_0x00762710"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

void __cdecl crt_global_destruction_register_0x00762710(void)
{
    asm volatile (
        "push               0x00407870\n\t"
        "call               _atexit\n\t"
        "pop                ecx"
        ::: "eax", "ecx", "edx", "memory"
    );
}

__attribute__((XOR32rr_REV))
struct VillagerName* __cdecl Alloc__17VillagerNameBlockFv(void)
{
    struct VillagerName* result;
    asm volatile (
        "%{disp32%} mov       ecx, dword ptr [_CurrentVillagerNameBlock]\n\t"
        "test               ecx, ecx\n\t"
        "push               esi\n\t"
        "%{disp8%} je         LAB__addr_0x0076273a\n\t"
        "LAB__addr_0x0076272b:\n\t"
        "%{disp8%} mov        eax, dword ptr [ecx + 0x0c]\n\t"
        "cmp                eax, dword ptr [ecx + 0x04]\n\t"
        "%{disp8%} jl         LAB__addr_0x0076275c\n\t"
        "%{disp8%} mov        ecx, dword ptr [ecx + 0x10]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} jne        LAB__addr_0x0076272b\n\t"
        "LAB__addr_0x0076273a:\n\t"
        "push               0x16\n\t"
        "push               0x00c24534\n\t"
        "push               0x14\n\t"
        "call               ___nw__FUl\n\t"
        "add                esp, 0x0c\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076275a\n\t"
        "mov.s              ecx, eax\n\t"
        "call               ??0VillagerNameBlock@@QAE@XZ\n\t"
        "mov.s              ecx, eax\n\t"
        "%{disp8%} jmp        LAB__addr_0x0076275c\n\t"
        "LAB__addr_0x0076275a:\n\t"
        "xor.s              ecx, ecx\n\t"
        "LAB__addr_0x0076275c:\n\t"
        "%{disp8%} inc        dword ptr [ecx + 0x08]\n\t"
        "%{disp8%} mov        edx, dword ptr [ecx + 0x0c]\n\t"
        "mov                esi, dword ptr [ecx]\n\t"
        "%{disp32%} lea       eax, dword ptr [edx * 0x8 + 0x00000000]\n\t"
        "sub.s              eax, edx\n\t"
        "lea                eax, dword ptr [eax + eax * 0x4]\n\t"
        "lea                eax, dword ptr [edx + eax * 0x8]\n\t"
        "inc                edx\n\t"
        "lea                eax, dword ptr [esi + eax * 0x4]\n\t"
        "%{disp8%} mov        dword ptr [ecx + 0x0c], edx\n\t"
        "pop                esi"
        : "=a"(result) :  : "ecx", "edx", "memory"
    );
    return result;
}

void __cdecl Delete__17VillagerNameBlockFP12VillagerName(struct VillagerName* name)
{
    asm volatile (
        "push               esi\n\t"
        "%{disp32%} mov       esi, dword ptr [_CurrentVillagerNameBlock]\n\t"
        "test               esi, esi\n\t"
        "push               edi\n\t"
        "%{disp8%} je         LAB__addr_0x007627da\n\t"
        "%{disp8%} mov        edi, dword ptr [esp + 0x0c]\n"
        "LAB__addr_0x00762790:\n\t"
        "mov                edx, dword ptr [esi]\n\t"
        "cmp.s              edi, edx\n\t"
        ".byte              0x72, 0x19\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x04]\n\t"
        "%{disp32%} lea       eax, dword ptr [ecx * 0x8 + 0x00000000]\n\t"
        "sub.s              eax, ecx\n\t"
        "lea                eax, dword ptr [eax + eax * 0x4]\n\t"
        "lea                ecx, dword ptr [ecx + eax * 0x8]\n\t"
        "lea                edx, dword ptr [edx + ecx * 0x4]\n\t"
        "cmp.s              edi, edx\n\t"
        ".byte              0x72, 0xa\n"
        "LAB__addr_0x007627af:\n\t"
        "%{disp8%} mov        esi, dword ptr [esi + 0x10]\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} jne        LAB__addr_0x00762790\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x007627b9:\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x08]\n\t"
        "dec                ecx\n\t"
        "mov.s              eax, ecx\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} mov        dword ptr [esi + 0x08], ecx\n\t"
        "%{disp8%} jg         LAB__addr_0x007627da\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x007627da\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?FreeAll@VillagerNameBlock@@QAEXXZ\n\t"
        "push               esi\n\t"
        "call               ??3@YAXPAX@Z\n\t"
        "add                esp, 0x04\n"
        "LAB__addr_0x007627da:\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

bool32_t __fastcall DeleteAll__17VillagerNameBlockFv(struct VillagerNameBlock* this)
{
    void* dummy;
    bool32_t result;
    asm volatile (
        "push               esi\n\t"
        "%{disp32%} mov       esi, dword ptr [_CurrentVillagerNameBlock]\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} je         LAB__addr_0x00762805\n\t"
        "LAB__addr_0x007627eb:\n\t"
        "mov.s              ecx, esi\n\t"
        "call               ?FreeAll@VillagerNameBlock@@QAEXXZ\n\t"
        "push               esi\n\t"
        "call               ??3@YAXPAX@Z\n\t"
        "%{disp32%} mov       esi, dword ptr [_CurrentVillagerNameBlock]\n\t"
        "add                esp, 0x04\n\t"
        "test               esi, esi\n\t"
        "%{disp8%} jne        LAB__addr_0x007627eb\n\t"
        "LAB__addr_0x00762805:\n\t"
        "%{disp32%} mov       dword ptr [_PTR_00db9e28], 0x00000000\n\t"
        "pop                esi"
        : "=a"(result), "=c"(dummy) : "c"(this) : "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV))
struct VillagerNameBlock* __fastcall __ct__17VillagerNameBlockFv(struct VillagerNameBlock* this)
{
    asm volatile (
        "push               esi\n\t"
        "push               0x35\n\t"
        "mov.s              esi, ecx\n\t"
        "push               0x00c24534\n\t"
        "push               0x00011904\n\t"
        "%{disp8%} mov        dword ptr [esi + 0x04], 0x00000040\n\t"
        "%{disp8%} mov        dword ptr [esi + 0x08], 0x00000000\n\t"
        "%{disp8%} mov        dword ptr [esi + 0x0c], 0x00000000\n\t"
        "call               ___nw__FUl\n\t"
        "add                esp, 0x0c\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x00762882\n\t"
        "%{disp8%} lea        edx, dword ptr [eax + 0x04]\n\t"
        "mov                dword ptr [eax], 0x00000040\n\t"
        "mov.s              eax, edx\n\t"
        "mov                ecx, 0x00000040\n"
        "LAB__addr_0x00762860:\n\t"
        "mov                dword ptr [eax], 0x0099a9bc\n\t"
        "add                eax, 0x00000464\n\t"
        "dec                ecx\n\t"
        "%{disp8%} jne        LAB__addr_0x00762860\n\t"
        "mov                dword ptr [esi], edx\n\t"
        "%{disp32%} mov       eax, dword ptr [_CurrentVillagerNameBlock]\n\t"
        "%{disp8%} mov        dword ptr [esi + 0x10], eax\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x3f3e24], esi\n\t"
        "mov.s              eax, esi\n\t"
        "pop                esi\n\t"
        "ret\n"
        "LAB__addr_0x00762882:\n\t"
        "xor.s              edx, edx\n\t"
        "mov                dword ptr [esi], edx\n\t"
        "%{disp32%} mov       eax, dword ptr [_CurrentVillagerNameBlock]\n\t"
        "%{disp8%} mov        dword ptr [esi + 0x10], eax\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x3f3e24], esi\n\t"
        "mov.s              eax, esi\n\t"
        "pop                esi\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

void __fastcall AddDrawing__12VillagerNameFv(struct VillagerName* this)
{
    asm volatile (
        "%{disp32%} mov       eax, dword ptr [data_bytes + 0x504644]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x007628fb\n\t"
        "%{disp32%} fld       dword ptr [ecx + 0x0000045c]\n\t"
        "push               0x0\n\t"
        "%{disp32%} fsub      dword ptr [data_bytes + 0x4dbdc0]\n\t"
        "push               ecx\n\t"
        "%{disp32%} fld       dword ptr [ecx + 0x00000458]\n\t"
        "mov.s              edx, ecx\n\t"
        "%{disp32%} fsub      dword ptr [data_bytes + 0x4dbdbc]\n\t"
        "%{disp32%} fld       dword ptr [ecx + 0x00000454]\n\t"
        "%{disp32%} mov       ecx, dword ptr [data_bytes + 0x504648]\n\t"
        "%{disp32%} fsub      dword ptr [data_bytes + 0x4dbdb8]\n\t"
        "fld                st(0)\n\t"
        "fmul               st, st(1)\n\t"
        "fld                st(2)\n\t"
        "fmul               st, st(3)\n\t"
        "faddp              st(1), st\n\t"
        "fld                st(3)\n\t"
        "fmul               st, st(4)\n\t"
        "faddp              st(1), st\n\t"
        "fstp               dword ptr [esp]\n\t"
        "push               0x00762dc0\n\t"
        "fstp               st(0)\n\t"
        "fstp               st(0)\n\t"
        "fstp               st(0)\n\t"
        "call               _jmp_addr_0x0083f310\n"
        "LAB__addr_0x007628fb:\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((section(".rdata$r"), aligned(8)))
const struct RTTIBaseClassDescriptor __RTTIBaseClassDescriptor__12VillagerName = {
    .pTypeDescriptor = &__RTTITypeDescriptor__12VillagerName,
    .numContainedBases = 0x00000001,
    .where = {
        .mdisp = 0x00000000,
        .pdisp = 0xFFFFFFFF,
        .vdisp = 0x00000000,
    },
    .attributes = 0x0000000,
};

__attribute__((section(".rdata$r"), aligned(8)))
const struct RTTIBaseClassArray __RTTIBaseClassArray__12VillagerName = {
    .arrayOfBaseClassDescriptors = {
        &__RTTIBaseClassDescriptor__12VillagerName,
        &__RTTIBaseClassDescriptor__13DrawingObject,
        NULL,
    }
};

__attribute__((section(".rdata$r"), aligned(8)))
const struct RTTIClassHierarchyDescriptor __RTTIClassHierarchyDescriptor__12VillagerName = {
  .signature = 0x00000000,
  .attributes = 0x00000000,
  .numBaseClasses = 0x00000002,
  .pBaseClassArray = &__RTTIBaseClassArray__12VillagerName,
};

__attribute__((section(".rdata$r"), aligned(8)))
const struct RTTICompleteObjectLocator __RTTICompleteObjectLocator__12VillagerName = {
  .signature = 0x00000000,
  .offset = 0x00000000,
  .cdOffset = 0x00000000,
  .pTypeDescriptor = &__RTTITypeDescriptor__12VillagerName,
  .pClassDescriptor = &__RTTIClassHierarchyDescriptor__12VillagerName,
};

const struct RTTICompleteObjectLocator* const p__RTTICompleteObjectLocator__12VillagerName = &__RTTICompleteObjectLocator__12VillagerName;

const struct VillagerNameVftable __vt__12VillagerName = {
  AddDrawing__12VillagerNameFv,
};

struct RTTITypeDescriptor __RTTITypeDescriptor__12VillagerName = {
    .pVFTable = &__vt__9type_info,
    .spare = 0,
    .name = ".?AUVillagerName@@",
};

void __fastcall __dt__17VillagerNameBlockFv(struct VillagerNameBlock* this)
{
    asm volatile (
        "%{disp8%} mov        dl, byte ptr [esp + 0x04]\n\t"
        "test               dl, 0x02\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x0076294d\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + -0x04]\n\t"
        "push               edi\n\t"
        "%{disp8%} lea        edi, dword ptr [esi + -0x04]\n\t"
        "%{disp32%} lea       ecx, dword ptr [eax * 0x8 + 0x00000000]\n\t"
        "sub.s              ecx, eax\n\t"
        "lea                ecx, dword ptr [ecx + ecx * 0x4]\n\t"
        "lea                ecx, dword ptr [eax + ecx * 0x8]\n\t"
        "dec                eax\n\t"
        "lea                ecx, dword ptr [esi + ecx * 0x4]\n\t"
        "%{disp8%} js         LAB__addr_0x00762938\n\t"
        "inc                eax\n"
        "LAB__addr_0x00762929:\n\t"
        "sub                ecx, 0x00000464\n\t"
        "dec                eax\n\t"
        "mov                dword ptr [ecx], 0x0099a9bc\n\t"
        "%{disp8%} jne        LAB__addr_0x00762929\n"
        "LAB__addr_0x00762938:\n\t"
        "test               dl, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x00762946\n\t"
        "push               edi\n\t"
        "call               ??3@YAXPAX@Z\n\t"
        "add                esp, 0x04\n"
        "LAB__addr_0x00762946:\n\t"
        "mov.s              eax, edi\n\t"
        "pop                edi\n\t"
        "pop                esi\n\t"
        "ret                0x0004\n"
        "LAB__addr_0x0076294d:\n\t"
        "test               dl, 0x01\n\t"
        "mov                dword ptr [esi], 0x0099a9bc\n\t"
        "%{disp8%} je         LAB__addr_0x00762961\n\t"
        "push               esi\n\t"
        "call               ??3@YAXPAX@Z\n\t"
        "add                esp, 0x04\n"
        "LAB__addr_0x00762961:\n\t"
        "mov.s              eax, esi\n\t"
        "pop                esi\n\t"
        "ret                0x0004"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

void __fastcall FreeAll__17VillagerNameBlockFv(struct VillagerNameBlock* this)
{
    asm volatile (
        "push               edi\n\t"
        "mov.s              edi, ecx\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "test               edx, edx\n\t"
        "%{disp8%} je         LAB__addr_0x007629af\n\t"
        "%{disp8%} mov        eax, dword ptr [edx + -0x04]\n\t"
        "push               esi\n\t"
        "%{disp8%} lea        esi, dword ptr [edx + -0x04]\n\t"
        "%{disp32%} lea       ecx, dword ptr [eax * 0x8 + 0x00000000]\n\t"
        "sub.s              ecx, eax\n\t"
        "lea                ecx, dword ptr [ecx + ecx * 0x4]\n\t"
        "lea                ecx, dword ptr [eax + ecx * 0x8]\n\t"
        "dec                eax\n\t"
        "lea                ecx, dword ptr [edx + ecx * 0x4]\n\t"
        "%{disp8%} js         LAB__addr_0x007629a5\n\t"
        "inc                eax\n"
        "LAB__addr_0x00762996:\n\t"
        "sub                ecx, 0x00000464\n\t"
        "dec                eax\n\t"
        "mov                dword ptr [ecx], 0x0099a9bc\n\t"
        "%{disp8%} jne        LAB__addr_0x00762996\n"
        "LAB__addr_0x007629a5:\n\t"
        "push               esi\n\t"
        "call               ??3@YAXPAX@Z\n\t"
        "add                esp, 0x04\n\t"
        "pop                esi\n"
        "LAB__addr_0x007629af:\n\t"
        "%{disp32%} mov       eax, dword ptr [_CurrentVillagerNameBlock]\n\t"
        "cmp.s              eax, edi\n\t"
        "%{disp8%} jne        LAB__addr_0x007629c3\n\t"
        "%{disp8%} mov        edx, dword ptr [edi + 0x10]\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x3f3e24], edx\n\t"
        "pop                edi\n\t"
        "ret\n"
        "LAB__addr_0x007629c3:\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x007629dc\n"
        "LAB__addr_0x007629c7:\n\t"
        "%{disp8%} mov        ecx, dword ptr [eax + 0x10]\n\t"
        "cmp.s              ecx, edi\n\t"
        "%{disp8%} je         LAB__addr_0x007629d6\n\t"
        "mov.s              eax, ecx\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x007629c7\n\t"
        "pop                edi\n\t"
        "ret\n"
        "LAB__addr_0x007629d6:\n\t"
        "%{disp8%} mov        ecx, dword ptr [edi + 0x10]\n\t"
        "%{disp8%} mov        dword ptr [eax + 0x10], ecx\n"
        "LAB__addr_0x007629dc:\n\t"
        "pop                edi\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}

__attribute__((XOR32rr_REV))
struct VillagerName* __cdecl Add__12VillagerNameFf7LHPointPwR9LH3DColor(float text_size, struct LHPoint point, const char16_t* text, const struct LH3DColor* p_color)
{
    struct VillagerName* result;
    asm volatile (
        "%{disp32%} mov       eax, dword ptr [_game]\n\t"
        "%{disp32%} mov       eax, dword ptr [eax + 0x0025005c]\n\t"
        "sub                esp, 0x10\n\t"
        "push               ebx\n\t"
        "xor.s              ebx, ebx\n\t"
        "cmp.s              eax, ebx\n\t"
        "push               esi\n\t"
        "%{disp8%} je         LAB__addr_0x00762a06\n\t"
        "cmp                dword ptr [eax + 0x000045e8], ebx\n\t"
        "%{disp8%} je         LAB__addr_0x00762a06\n\t"
        "pop                esi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x10\n\t"
        "%{disp8%} jmp        __Add_exit__\n"
        "LAB__addr_0x00762a06:\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x1c]\n\t"
        "%{disp32%} fcomp     dword ptr [rdata_bytes + 0x1c840]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x00762a1f\n\t"
        "pop                esi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x10\n\t"
        "%{disp8%} jmp        __Add_exit__\n"
        "LAB__addr_0x00762a1f:\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x1c]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float1p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp8%} jne        LAB__addr_0x00762a38\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x1c], 0x3f800000\n"
        "LAB__addr_0x00762a38:\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x10]\n\t"
        "push               ecx\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x10]\n\t"
        "push               edx\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x10]\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x28]\n\t"
        "xor.s              esi, esi\n\t"
        "call               ?ProjectPoint@LH3DTech@@SAIPAULHPoint@@PAH1PAM@Z\n\t"
        "cmp                eax, 0x02\n\t"
        "%{disp32%} jne       LAB__addr_0x00762db1\n\t"
        "call               ?Alloc@VillagerNameBlock@@SAPAUVillagerName@@XZ\n\t"
        "mov.s              esi, eax\n\t"
        "%{disp8%} mov        dword ptr [esi + 0x28], 0x00000001\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x20]\n\t"
        "%{disp32%} lea       eax, dword ptr [esi + 0x00000454]\n\t"
        "mov                dword ptr [eax], ecx\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x24]\n\t"
        "%{disp8%} mov        dword ptr [eax + 0x04], edx\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x1c]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x28]\n\t"
        "%{disp8%} mov        dword ptr [esi + 0x24], edx\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x30]\n\t"
        "%{disp8%} mov        dword ptr [eax + 0x08], ecx\n\t"
        "cmp                byte ptr [edx + 0x02], 0x0a\n\t"
        "%{disp8%} jae        LAB__addr_0x00762aa4\n\t"
        "cmp                byte ptr [edx + 0x01], 0x0a\n\t"
        "%{disp8%} jae        LAB__addr_0x00762aa4\n\t"
        "cmp                byte ptr [edx], 0x0a\n\t"
        "%{disp8%} jae        LAB__addr_0x00762aa4\n\t"
        "mov                dword ptr [edx], 0x00ffffff\n"
        "LAB__addr_0x00762aa4:\n\t"
        "mov                ecx, dword ptr [edx]\n\t"
        "push               ebp\n\t"
        "push               edi\n\t"
        "mov.s              eax, ecx\n\t"
        "and                eax, 0x00ff0000\n\t"
        "shl                eax, 7\n\t"
        "mov.s              edi, eax\n\t"
        "mov                eax, 0x7f800000\n\t"
        "sub.s              eax, edi\n\t"
        "shr                eax, 8\n\t"
        "mov.s              edi, ecx\n\t"
        "and                edi, 0xffff0000\n\t"
        "add.s              eax, edi\n\t"
        "mov.s              edi, ecx\n\t"
        "and                edi, 0x0000ff00\n\t"
        "shl                edi, 7\n\t"
        "mov                ebp, 0x007f8000\n\t"
        "sub.s              ebp, edi\n\t"
        "shr                ebp, 8\n\t"
        "mov.s              edi, ecx\n\t"
        "and                edi, 0xffffff00\n\t"
        "add.s              ebp, edi\n\t"
        "and                ebp, 0x0000ff00\n\t"
        "and                eax, 0xffff0000\n\t"
        "or.s               eax, ebp\n\t"
        "mov.s              edi, ecx\n\t"
        "and                edi, 0x000000ff\n\t"
        "shl                edi, 7\n\t"
        "mov                ebp, 0x00007f80\n\t"
        "sub.s              ebp, edi\n\t"
        "shr                ebp, 8\n\t"
        "add.s              ebp, ecx\n\t"
        "and                ebp, 0x000000ff\n\t"
        "or.s               eax, ebp\n\t"
        "%{disp8%} mov        ebp, dword ptr [esp + 0x34]\n\t"
        "or                 eax, 0xff000000\n\t"
        "mov                dword ptr [edx], eax\n\t"
        "push               0x000000ff\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000450], eax\n\t"
        "%{disp8%} lea        eax, dword ptr [esi + 0x30]\n\t"
        "push               ebp\n\t"
        "%{disp32%} lea       edi, dword ptr [esi + 0x00000430]\n\t"
        "push               eax\n\t"
        "mov                dword ptr [edi], eax\n\t"
        "call               _wcsncpy\n\t"
        "add                esp, 0x0c\n\t"
        "%{disp32%} mov       word ptr [esi + 0x0000022e], bx\n\t"
        "xor.s              ecx, ecx\n\t"
        "%{disp8%} lea        eax, dword ptr [esi + 0x32]\n"
        "LAB__addr_0x00762b4a:\n\t"
        "%{disp8%} mov        dx, word ptr [ebp + 0x00]\n\t"
        "cmp.s              dx, bx\n\t"
        "%{disp8%} je         LAB__addr_0x00762b82\n\t"
        "cmp                dx, 0x0a\n\t"
        "%{disp8%} jne        LAB__addr_0x00762b73\n\t"
        "%{disp8%} mov        word ptr [eax + -0x02], bx\n\t"
        "%{disp8%} mov        edx, dword ptr [esi + 0x28]\n\t"
        "%{disp32%} mov       dword ptr [esi + edx * 0x4 + 0x00000430], eax\n\t"
        "%{disp8%} mov        edx, dword ptr [esi + 0x28]\n\t"
        "inc                edx\n\t"
        "cmp                edx, 0x08\n\t"
        "%{disp8%} mov        dword ptr [esi + 0x28], edx\n\t"
        "%{disp8%} je         LAB__addr_0x00762b82\n"
        "LAB__addr_0x00762b73:\n\t"
        "inc                ecx\n\t"
        "add                ebp, 0x02\n\t"
        "add                eax, 0x02\n\t"
        "cmp                ecx, 0x000000ff\n\t"
        "%{disp8%} jl         LAB__addr_0x00762b4a\n"
        "LAB__addr_0x00762b82:\n\t"
        "%{disp8%} fild       dword ptr [esp + 0x10]\n\t"
        "xor.s              ebp, ebp\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x38], 0x00000000\n\t"
        "%{disp8%} fstp       dword ptr [esi + 0x14]\n\t"
        "%{disp8%} fild       dword ptr [esp + 0x14]\n\t"
        "%{disp8%} fstp       dword ptr [esi + 0x18]\n\t"
        "%{disp8%} mov        eax, dword ptr [esp + 0x18]\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x24]\n\t"
        "%{disp8%} mov        dword ptr [esi + 0x1c], eax\n\t"
        "%{disp32%} fmul      dword ptr [rdata_bytes + 0x26e8]\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x28]\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} fstp       dword ptr [esi + 0x20]\n\t"
        "%{disp32%} mov       ebx, dword ptr [data_bytes + 0x506d08]\n\t"
        "%{disp8%} jle        LAB__addr_0x00762c0d\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x24]\n\t"
        "%{disp32%} fmul      dword ptr [rdata_bytes + 0x235c]\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x1c]\n"
        "LAB__addr_0x00762bc9:\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x20]\n\t"
        "push               edx\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x38], ecx\n\t"
        "call               _wcslen\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x38]\n\t"
        "mov                ecx, dword ptr [edi]\n\t"
        "add                esp, 0x04\n\t"
        "push               edx\n\t"
        "push               eax\n\t"
        "push               ecx\n\t"
        "mov.s              ecx, ebx\n\t"
        "call               @GetStringWidth__13GatheringTextFPwif@20\n\t"
        "%{disp8%} fadd       dword ptr [esp + 0x1c]\n\t"
        "%{disp8%} fcom       dword ptr [esp + 0x38]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp8%} jne        LAB__addr_0x00762c00\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x38]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00762c02\n"
        "LAB__addr_0x00762c00:\n\t"
        "fstp               st(0)\n"
        "LAB__addr_0x00762c02:\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x28]\n\t"
        "inc                ebp\n\t"
        "add                edi, 0x04\n\t"
        "cmp.s              ebp, eax\n\t"
        "%{disp8%} jl         LAB__addr_0x00762bc9\n"
        "LAB__addr_0x00762c0d:\n\t"
        "%{disp32%} mov       ecx, dword ptr [data_bytes + 0x4bf058]\n\t"
        "mov.s              eax, ecx\n\t"
        "and                eax, 0x0000ffff\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x34], eax\n\t"
        "%{disp8%} fild       dword ptr [esp + 0x34]\n\t"
        "pop                edi\n\t"
        "pop                ebp\n\t"
        "%{disp8%} fcomp      dword ptr [esp + 0x30]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x00762c44\n\t"
        "shr                cx, 1\n\t"
        "and                ecx, 0x0000ffff\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x30], ecx\n\t"
        "%{disp8%} fild       dword ptr [esp + 0x30]\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x30]\n"
        "LAB__addr_0x00762c44:\n\t"
        "%{disp8%} fild       dword ptr [esp + 0x08]\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x30]\n\t"
        "%{disp32%} fmul      dword ptr [_rdata_float0p5]\n\t"
        "fsubp              st(1), st\n\t"
        "%{disp8%} fst        dword ptr [esi + 0x04]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float0p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x00762c6b\n\t"
        "%{disp8%} mov        dword ptr [esi + 0x04], 0x00000000\n"
        "LAB__addr_0x00762c6b:\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x30]\n\t"
        "%{disp8%} fadd       dword ptr [esi + 0x04]\n\t"
        "%{disp8%} fst        dword ptr [esi + 0x0c]\n\t"
        "%{disp32%} mov       ecx, dword ptr [data_bytes + 0x4bf058]\n\t"
        "and                ecx, 0x0000ffff\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x2c], ecx\n\t"
        "%{disp8%} fild       dword ptr [esp + 0x2c]\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x2c]\n\t"
        "%{disp8%} fcomp      dword ptr [esp + 0x2c]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp8%} jne        LAB__addr_0x00762caa\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x2c]\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x2c]\n\t"
        "%{disp8%} fsub       dword ptr [esp + 0x30]\n\t"
        "%{disp8%} mov        dword ptr [esi + 0x0c], edx\n\t"
        "%{disp8%} fstp       dword ptr [esi + 0x04]\n"
        "LAB__addr_0x00762caa:\n\t"
        "%{disp8%} fld        dword ptr [esi + 0x18]\n\t"
        "%{disp32%} fsub      dword ptr [rdata_bytes + 0x1dca4]\n\t"
        "%{disp8%} fst        dword ptr [esi + 0x10]\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x1c]\n\t"
        "fadd.s             st(0), st(0)\n\t"
        "%{disp8%} fstp       dword ptr [esi + 0x2c]\n\t"
        "%{disp8%} fild       dword ptr [esi + 0x28]\n\t"
        "%{disp8%} fmul       dword ptr [esi + 0x20]\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x1c]\n\t"
        "%{disp32%} fmul      dword ptr [rdata_bytes + 0x2418]\n\t"
        "faddp              st(1), st\n\t"
        "fsubr              st, st(1)\n\t"
        "%{disp8%} fstp       dword ptr [esi + 0x08]\n\t"
        "%{disp32%} mov       ecx, dword ptr [_PTR_00db9e28]\n\t"
        "test               ecx, ecx\n\t"
        "fstp               st(0)\n\t"
        "%{disp8%} je         LAB__addr_0x00762d5e\n"
        "LAB__addr_0x00762ce2:\n\t"
        "%{disp8%} fld        dword ptr [ecx + 0x04]\n\t"
        "%{disp8%} fcomp      dword ptr [esi + 0x0c]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x00762d5e\n"
        "LAB__addr_0x00762cef:\n\t"
        "%{disp8%} fld        dword ptr [ecx + 0x0c]\n\t"
        "%{disp8%} fcomp      dword ptr [esi + 0x04]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp8%} jne        LAB__addr_0x00762d54\n\t"
        "%{disp8%} fld        dword ptr [ecx + 0x08]\n\t"
        "%{disp8%} fcomp      dword ptr [esi + 0x10]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp8%} je         LAB__addr_0x00762d54\n\t"
        "%{disp8%} fld        dword ptr [ecx + 0x10]\n\t"
        "%{disp8%} fcomp      dword ptr [esi + 0x08]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x00762d54\n\t"
        "%{disp8%} fld        dword ptr [esi + 0x08]\n\t"
        "%{disp8%} fsub       dword ptr [esi + 0x10]\n\t"
        "%{disp8%} fstp       dword ptr [esi + 0x08]\n\t"
        "%{disp8%} fld        dword ptr [ecx + 0x08]\n\t"
        "%{disp32%} fsub      dword ptr [_rdata_float1p0]\n\t"
        "%{disp8%} fst        dword ptr [esi + 0x10]\n\t"
        "%{disp8%} fadd       dword ptr [esi + 0x08]\n\t"
        "%{disp8%} fstp       dword ptr [esi + 0x08]\n\t"
        "%{disp8%} fld        dword ptr [ecx + 0x08]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float0p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x00762d5e\n\t"
        "%{disp32%} mov       ecx, dword ptr [_PTR_00db9e28]\n\t"
        "%{disp8%} fld        dword ptr [ecx + 0x04]\n\t"
        "%{disp8%} fcomp      dword ptr [esi + 0x0c]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} jne        LAB__addr_0x00762cef\n"
        "LAB__addr_0x00762d54:\n\t"
        "%{disp32%} mov       ecx, dword ptr [ecx + 0x00000460]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} jne        LAB__addr_0x00762ce2\n"
        "LAB__addr_0x00762d5e:\n\t"
        "%{disp8%} fld        dword ptr [esi + 0x08]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float0p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x00762d7f\n\t"
        "push               esi\n\t"
        "call               ?Delete@VillagerNameBlock@@SAXPAUVillagerName@@@Z\n\t"
        "add                esp, 0x04\n\t"
        "pop                esi\n\t"
        "xor.s              eax, eax\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x10\n\t"
        "%{disp8%} jmp        __Add_exit__\n"
        "LAB__addr_0x00762d7f:\n\t"
        "%{disp32%} mov       ecx, dword ptr [_PTR_00db9e28]\n\t"
        "test               ecx, ecx\n\t"
        "mov                edx, OFFSET _PTR_00db9e28\n\t"
        "%{disp8%} je         LAB__addr_0x00762da7\n"
        "LAB__addr_0x00762d8e:\n\t"
        "%{disp8%} fld        dword ptr [ecx + 0x04]\n\t"
        "%{disp8%} fcomp      dword ptr [esi + 0x04]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x00762da7\n\t"
        "%{disp32%} lea       edx, dword ptr [ecx + 0x00000460]\n\t"
        "mov                ecx, dword ptr [edx]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} jne        LAB__addr_0x00762d8e\n"
        "LAB__addr_0x00762da7:\n\t"
        "mov                eax, dword ptr [edx]\n\t"
        "%{disp32%} mov       dword ptr [esi + 0x00000460], eax\n\t"
        "mov                dword ptr [edx], esi\n"
        "LAB__addr_0x00762db1:\n\t"
        "mov.s              eax, esi\n\t"
        "pop                esi\n\t"
        "pop                ebx\n\t"
        "add                esp, 0x10\n"
        "__Add_exit__:"
        : "=a"(result) :: "ecx", "edx", "memory"
    );
    return result;
}

__attribute__((XOR32rr_REV))
void __fastcall Draw__12VillagerNameFv(struct VillagerName* this)
{
    asm volatile (
        "sub                esp, 0x10\n\t"
        "push               esi\n\t"
        "mov.s              esi, ecx\n\t"
        "%{disp8%} fld        dword ptr [esi + 0x24]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float0p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x41\n\t"
        "%{disp8%} jne        LAB__addr_0x00762df3\n\t"
        "%{disp8%} fld        dword ptr [esi + 0x24]\n\t"
        "%{disp32%} fcomp     dword ptr [_rdata_float1p0]\n\t"
        "fnstsw             ax\n\t"
        "test               ah, 0x01\n\t"
        "%{disp8%} je         LAB__addr_0x00762deb\n\t"
        "%{disp8%} fld        dword ptr [esi + 0x24]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00762df9\n"
        "LAB__addr_0x00762deb:\n\t"
        "%{disp32%} fld       dword ptr [_rdata_float1p0]\n\t"
        "%{disp8%} jmp        LAB__addr_0x00762df9\n"
        "LAB__addr_0x00762df3:\n\t"
        "%{disp32%} fld       dword ptr [_rdata_float0p0]\n"
        "LAB__addr_0x00762df9:\n\t"
        "push               ebx\n\t"
        "%{disp8%} fst        dword ptr [esi + 0x24]\n\t"
        "%{disp32%} fmul      dword ptr [rdata_bytes + 0x26338]\n\t"
        "push               ebp\n\t"
        "push               edi\n\t"
        "call               _jmp_addr_0x007a1400\n\t"
        "mov.s              edi, eax\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x1c]\n\t"
        "push               eax\n\t"
        "call               _jmp_addr_0x005766e0\n\t"
        "%{disp8%} fstp       dword ptr [esp + 0x1c]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x10]\n\t"
        "%{disp8%} mov        edx, dword ptr [esi + 0x08]\n\t"
        "%{disp8%} mov        ebx, dword ptr [esp + 0x1c]\n\t"
        "add                esp, 0x04\n\t"
        "push               edi\n\t"
        "push               edi\n\t"
        "push               0x0\n\t"
        "push               0xff000000\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x20], ecx\n\t"
        "%{disp8%} fld        dword ptr [esp + 0x20]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x24], edx\n\t"
        "%{disp8%} fsub       dword ptr [esp + 0x24]\n\t"
        "push               0x0\n\t"
        "push               0x0\n\t"
        "push               ecx\n\t"
        "%{disp32%} fmul      dword ptr [rdata_bytes + 0x23d4]\n\t"
        "mov.s              eax, ecx\n\t"
        "%{disp8%} mov        ecx, dword ptr [esi + 0x0c]\n\t"
        "fstp               dword ptr [esp]\n\t"
        "push               ebx\n\t"
        "push               eax\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x04]\n\t"
        "push               ecx\n\t"
        "push               edx\n\t"
        "push               eax\n\t"
        "call               _jmp_addr_0x008334c0\n\t"
        "%{disp32%} mov       eax, dword ptr [data_bytes + 0x5132dc]\n\t"
        "add                esp, 0x30\n\t"
        "test               eax, eax\n\t"
        "%{disp32%} mov       dword ptr [data_bytes + 0x2078], edi\n\t"
        "%{disp32%} je        LAB__addr_0x00762f71\n\t"
        "%{disp8%} fld        dword ptr [esi + 0x18]\n\t"
        "push               ebx\n\t"
        "%{disp32%} fsub      dword ptr [rdata_bytes + 0x26e8]\n\t"
        "xor.s              ecx, ecx\n\t"
        "%{disp32%} mov       cx, word ptr [data_bytes + 0x4bf05a]\n\t"
        "push               0x1\n\t"
        "%{disp8%} lea        edx, dword ptr [esp + 0x18]\n\t"
        "%{disp8%} mov        byte ptr [esp + 0x18], 0x00\n\t"
        "%{disp8%} mov        byte ptr [esp + 0x19], 0x00\n\t"
        "%{disp8%} mov        byte ptr [esp + 0x1a], 0x00\n\t"
        "%{disp8%} mov        byte ptr [esp + 0x1b], -0x01\n\t"
        "push               ecx\n\t"
        "push               0x0\n\t"
        "push               0x0\n\t"
        "push               edx\n\t"
        "push               eax\n\t"
        "push               0x3d4ccccd\n\t"
        "push               0x3f180000\n\t"
        "push               0x3d4ccccd\n\t"
        "push               0x3f080000\n\t"
        "call               _jmp_addr_0x007a1400\n\t"
        "%{disp8%} fld        dword ptr [esi + 0x14]\n\t"
        "%{disp32%} fadd      dword ptr [rdata_bytes + 0x19c50]\n\t"
        "push               eax\n\t"
        "call               _jmp_addr_0x007a1400\n\t"
        "%{disp8%} fld        dword ptr [esi + 0x10]\n\t"
        "push               eax\n\t"
        "call               _jmp_addr_0x007a1400\n\t"
        "%{disp8%} fld        dword ptr [esi + 0x14]\n\t"
        "%{disp32%} fsub      dword ptr [rdata_bytes + 0x19c50]\n\t"
        "push               eax\n\t"
        "call               _jmp_addr_0x007a1400\n\t"
        "push               eax\n\t"
        "call               ?DrawBox@SetupThing@@SAXHHHHMMMMPAULH3DMaterial@@PAULH3DColor@@HHH_NM@Z\n\t"
        "%{disp8%} fld        dword ptr [esi + 0x18]\n\t"
        "%{disp32%} mov       edx, dword ptr [data_bytes + 0x5132dc]\n\t"
        "push               ebx\n\t"
        "xor.s              eax, eax\n\t"
        "%{disp32%} mov       ax, word ptr [data_bytes + 0x4bf05a]\n\t"
        "push               0x1\n\t"
        "%{disp8%} lea        ecx, dword ptr [esp + 0x54]\n\t"
        "%{disp8%} mov        byte ptr [esp + 0x54], 0x00\n\t"
        "%{disp8%} mov        byte ptr [esp + 0x55], 0x00\n\t"
        "%{disp8%} mov        byte ptr [esp + 0x56], 0x00\n\t"
        "%{disp8%} mov        byte ptr [esp + 0x57], -0x01\n\t"
        "push               eax\n\t"
        "push               0x0\n\t"
        "push               0x0\n\t"
        "push               ecx\n\t"
        "push               edx\n\t"
        "push               0x3e000000\n\t"
        "push               0x3f200000\n\t"
        "push               0x3d4ccccd\n\t"
        "push               0x3f000000\n\t"
        "call               _jmp_addr_0x007a1400\n\t"
        "%{disp8%} fld        dword ptr [esi + 0x14]\n\t"
        "%{disp32%} fadd      dword ptr [rdata_bytes + 0x235c]\n\t"
        "push               eax\n\t"
        "call               _jmp_addr_0x007a1400\n\t"
        "%{disp8%} fld        dword ptr [esi + 0x18]\n\t"
        "%{disp32%} fsub      dword ptr [rdata_bytes + 0x26e8]\n\t"
        "push               eax\n\t"
        "call               _jmp_addr_0x007a1400\n\t"
        "%{disp8%} fld        dword ptr [esi + 0x14]\n\t"
        "%{disp32%} fsub      dword ptr [rdata_bytes + 0x235c]\n\t"
        "push               eax\n\t"
        "call               _jmp_addr_0x007a1400\n\t"
        "push               eax\n\t"
        "call               ?DrawBox@SetupThing@@SAXHHHHMMMMPAULH3DMaterial@@PAULH3DColor@@HHH_NM@Z\n\t"
        "add                esp, 0x78\n"
        "LAB__addr_0x00762f71:\n\t"
        "%{disp8%} fld        dword ptr [esi + 0x24]\n\t"
        "%{disp32%} mov       eax, dword ptr [data_bytes + 0x506d08]\n\t"
        "%{disp32%} fmul      dword ptr [__real@437f0000]\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x1c], eax\n\t"
        "call               _jmp_addr_0x007a1400\n\t"
        "%{disp32%} mov       byte ptr [esi + 0x00000453], al\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x28]\n\t"
        "xor.s              ebp, ebp\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], ebp\n\t"
        "%{disp8%} jle        LAB__addr_0x00763017\n\t"
        "%{disp32%} lea       edi, dword ptr [esi + 0x00000430]\n"
        "LAB__addr_0x00762fa1:\n\t"
        "%{disp32%} mov       cx, word ptr [data_bytes + 0x4bf05a]\n\t"
        "%{disp8%} mov        word ptr [esp + 0x18], cx\n\t"
        "%{disp8%} mov        edx, dword ptr [esp + 0x18]\n\t"
        "and                edx, 0x0000ffff\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x10], edx\n\t"
        "%{disp8%} fild       dword ptr [esp + 0x10]\n\t"
        "%{disp32%} lea       eax, dword ptr [esi + 0x00000450]\n\t"
        "push               ecx\n\t"
        "fstp               dword ptr [esp]\n\t"
        "push               0x0\n\t"
        "%{disp8%} fild       dword ptr [esp + 0x1c]\n\t"
        "push               0x0\n\t"
        "push               0x1\n\t"
        "push               eax\n\t"
        "%{disp8%} fmul       dword ptr [esi + 0x20]\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x20]\n\t"
        "push               eax\n\t"
        "push               ebx\n\t"
        "%{disp8%} fadd       dword ptr [esi + 0x2c]\n\t"
        "push               ecx\n\t"
        "%{disp8%} fadd       dword ptr [esi + 0x08]\n\t"
        "fstp               dword ptr [esp]\n\t"
        "push               ecx\n\t"
        "%{disp8%} fld        dword ptr [esi + 0x04]\n\t"
        "mov                ecx, dword ptr [edi]\n\t"
        "%{disp8%} fadd       dword ptr [esi + 0x2c]\n\t"
        "fstp               dword ptr [esp]\n\t"
        "push               ecx\n\t"
        "call               _wcslen\n\t"
        "mov                edx, dword ptr [edi]\n\t"
        "%{disp8%} mov        ecx, dword ptr [esp + 0x44]\n\t"
        "add                esp, 0x04\n\t"
        "push               eax\n\t"
        "push               edx\n\t"
        "call               @DrawTextRaw__13GatheringTextFPwiffffP9LH3DColoriP9LH3DColorff@52\n\t"
        "%{disp8%} mov        eax, dword ptr [esi + 0x28]\n\t"
        "inc                ebp\n\t"
        "add                edi, 0x04\n\t"
        "cmp.s              ebp, eax\n\t"
        "%{disp8%} mov        dword ptr [esp + 0x14], ebp\n\t"
        "%{disp8%} jl         LAB__addr_0x00762fa1\n"
        "LAB__addr_0x00763017:\n\t"
        "%{disp32%} mov       eax, dword ptr [_PTR_00db9e28]\n\t"
        "cmp.s              esi, eax\n\t"
        "pop                edi\n\t"
        "pop                ebp\n\t"
        "pop                ebx\n\t"
        "%{disp8%} jne        LAB__addr_0x0076303c\n\t"
        "%{disp32%} mov       eax, dword ptr [esi + 0x00000460]\n\t"
        "push               esi\n\t"
        "%{disp32%} mov       dword ptr [_PTR_00db9e28], eax\n\t"
        "call               ?Delete@VillagerNameBlock@@SAXPAUVillagerName@@@Z\n\t"
        "add                esp, 0x04\n\t"
        "pop                esi\n\t"
        "add                esp, 0x10\n\t"
        "ret\n"
        "LAB__addr_0x0076303c:\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} je         LAB__addr_0x0076306e\n"
        "LAB__addr_0x00763040:\n\t"
        "%{disp32%} mov       ecx, dword ptr [eax + 0x00000460]\n\t"
        "test               ecx, ecx\n\t"
        "%{disp8%} je         LAB__addr_0x0076306e\n\t"
        "cmp.s              ecx, esi\n\t"
        "%{disp8%} je         LAB__addr_0x00763062\n\t"
        "mov.s              eax, ecx\n\t"
        "test               eax, eax\n\t"
        "%{disp8%} jne        LAB__addr_0x00763040\n\t"
        "push               esi\n\t"
        "call               ?Delete@VillagerNameBlock@@SAXPAUVillagerName@@@Z\n\t"
        "add                esp, 0x04\n\t"
        "pop                esi\n\t"
        "add                esp, 0x10\n\t"
        "ret\n"
        "LAB__addr_0x00763062:\n\t"
        "%{disp32%} mov       ecx, dword ptr [esi + 0x00000460]\n\t"
        "%{disp32%} mov       dword ptr [eax + 0x00000460], ecx\n"
        "LAB__addr_0x0076306e:\n\t"
        "push               esi\n\t"
        "call               ?Delete@VillagerNameBlock@@SAXPAUVillagerName@@@Z\n\t"
        "add                esp, 0x04\n\t"
        "pop                esi\n\t"
        "add                esp, 0x10\n\t"
        "ret"
        ::: "eax", "ecx", "edx", "memory"
    );
    __builtin_unreachable();
}
